exclude: (?:^flake.lock$|/__GENERATED__/|^tests/tests/mc-(?:analysis|generated)|\.snap$)
repos:
  # Common
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: (?:\.patch$)
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-xml
      - id: check-yaml
      - id: check-json
        exclude: (?:^tests/tests/files/test_talosconfig_browser_config.json$)
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs

  # C++
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v19.1.4'
    hooks:
      - id: clang-format
        exclude: (?:\.js$|\.json$|\.java$|\.mjs$)

  # Rust
  - repo: https://github.com/kykosic/pre-commit-rust
    rev: '0.4.0'
    hooks:
      - id: cargo-fmt
      - id: cargo-clippy
