#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

$MOZSEARCH_ROOT/scripts/cpp-configure.sh

cd $TREE_ROOT/objdir
make
cd -

$MOZSEARCH_ROOT/scripts/find-repo-files.py

$MOZSEARCH_ROOT/scripts/build-codesearch.sh

$MOZSEARCH_ROOT/scripts/mkdirs.sh

$MOZSEARCH_ROOT/scripts/js-analyze.sh

$MOZSEARCH_ROOT/scripts/crossref.sh

$MOZSEARCH_ROOT/scripts/output.sh
