#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

echo Updating mercurial
pushd $HG_ROOT
hg pull -u
popd

date

echo Updating git
pushd $TREE_ROOT
git pull
popd

date

echo Generating blame information
$VENV/bin/python $MOZSEARCH_ROOT/blame/transform-repo.py $TREE_ROOT $BLAME_ROOT $HG_ROOT

date
