#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

pushd $HG_ROOT
hg pull -u
popd

date

pushd $TREE_ROOT
git pull
popd

date

$VENV/bin/python $MOZSEARCH_ROOT/blame/transform-repo.py $TREE_ROOT $BLAME_ROOT $HG_ROOT

date
