{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasicParent.cpp","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/PTestBasicParent@2Ecpp"}
{"loc":"00007:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00008:9-35","target":1,"kind":"use","pretty":"tools/profiler/public/ProfilerLabels.h","sym":"FILE_tools/profiler/public/ProfilerLabels@2Eh"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"ipc/ipdl/test/gtest/TestBasicParent.h","sym":"FILE_ipc/ipdl/test/gtest/TestBasicParent@2Eh"}
{"loc":"00012:9-32","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh"}
{"loc":"00013:9-47","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh"}
{"loc":"00014:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_android-armv7@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00015:9-33","target":1,"kind":"use","pretty":"ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh"}
{"loc":"00016:9-45","target":1,"kind":"use","pretty":"ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh"}
{"loc":"00017:9-38","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh"}
{"loc":"00018:9-42","target":1,"kind":"use","pretty":"ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh"}
{"loc":"00019:9-41","target":1,"kind":"use","pretty":"ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh"}
{"loc":"00021:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00022:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00025:23-38","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::ProcessingError","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc","peekRange":"25-27"}
{"loc":"00025:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::ProcessingError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc"}
{"loc":"00026:8-14","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","context":"mozilla::_ipdltest::PTestBasicParent::ProcessingError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc"}
{"loc":"00031:23-53","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::ShouldContinueFromReplyTimeout","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent30ShouldContinueFromReplyTimeoutEv","peekRange":"31-31"}
{"loc":"00031:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::ShouldContinueFromReplyTimeout","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent30ShouldContinueFromReplyTimeoutEv"}
{"loc":"00036:0-12","target":1,"kind":"use","pretty":"MOZ_IMPLICIT","sym":"M_5f65895d5a5258f7"}
{"loc":"00036:13-29","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev"}
{"loc":"00036:31-47","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","sym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev"}
{"loc":"00037:18-35","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol","sym":"T_mozilla::ipc::IToplevelProtocol","context":"mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev"}
{"loc":"00037:4-11","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::IToplevelProtocol","sym":"_ZN7mozilla3ipc17IToplevelProtocolC1EPKc15IPCMessageStartNS0_4SideE","context":"mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev"}
{"loc":"00037:56-74","target":1,"kind":"use","pretty":"IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","context":"mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev"}
{"loc":"00037:90-100","target":1,"kind":"use","pretty":"mozilla::ipc::Side::ParentSide","sym":"E_<T_mozilla::ipc::Side>_ParentSide","context":"mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev"}
{"loc":"00039:19-35","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev"}
{"loc":"00039:4-18","target":1,"kind":"use","pretty":"MOZ_COUNT_CTOR","sym":"M_d9d58f5149d9f0f2"}
{"loc":"00042:0-16","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::~PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentD1Ev"}
{"loc":"00042:19-35","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::~PTestBasicParent","sym":"_ZN7mozilla9_ipdltest16PTestBasicParentD1Ev","peekRange":"42-42"}
{"loc":"00042:19-35","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::~PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentD1Ev"}
{"loc":"00044:19-35","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::~PTestBasicParent","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParentD1Ev"}
{"loc":"00044:4-18","target":1,"kind":"use","pretty":"MOZ_COUNT_DTOR","sym":"M_f9e8c16149d9f0f2"}
{"loc":"00047:23-39","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::AllManagedActors","sym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE","peekRange":"47-47"}
{"loc":"00047:40-48","target":1,"kind":"use","pretty":"nsTArray","sym":"T_nsTArray","context":"mozilla::_ipdltest::PTestBasicParent::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00047:49-55","target":1,"kind":"use","pretty":"RefPtr","sym":"T_RefPtr","context":"mozilla::_ipdltest::PTestBasicParent::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00047:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00047:70-89","target":1,"kind":"use","pretty":"mozilla::ipc::ActorLifecycleProxy","sym":"T_mozilla::ipc::ActorLifecycleProxy","context":"mozilla::_ipdltest::PTestBasicParent::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00049:4-12","target":1,"kind":"use","pretty":"uint32_t","sym":"T_uint32_t","context":"mozilla::_ipdltest::PTestBasicParent::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00050:10-21","target":1,"kind":"use","pretty":"nsTArray_Impl::SetCapacity","sym":"_ZN13nsTArray_Impl11SetCapacityEN13nsTArray_baseIT0_N27nsTArray_RelocationStrategyIT_E4TypeEE9size_typeE","context":"mozilla::_ipdltest::PTestBasicParent::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00054:23-32","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::SendHello","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv","peekRange":"54-54"}
{"loc":"00054:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00056:19-26","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00056:4-13","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicParent::UniquePtr","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00056:48-57","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00056:58-77","target":1,"kind":"use","pretty":"SpecialRoutingIDs::MSG_ROUTING_CONTROL","sym":"E_<T_SpecialRoutingIDs>_MSG_ROUTING_CONTROL","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00057:23-31","target":1,"kind":"use","pretty":"IPC::MessageWriter::MessageWriter","sym":"_ZN3IPC13MessageWriterC1ERNS_7MessageEPN7mozilla3ipc9IProtocolE","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00057:9-22","target":1,"kind":"use","pretty":"IPC::MessageWriter","sym":"T_IPC::MessageWriter","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00058:13-14","target":1,"kind":"use","pretty":"mozilla::UniquePtr::operator*","sym":"_ZNK7mozilla9UniquePtrdeEv","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00065:22-39","target":1,"kind":"use","pretty":"mozilla::ipc::LoggingEnabledFor","sym":"_ZN7mozilla3ipc17LoggingEnabledForEPKc","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00066:22-43","target":1,"kind":"use","pretty":"mozilla::ipc::LogMessageForProtocol","sym":"_ZN7mozilla3ipc21LogMessageForProtocolEPKciS2_jNS0_16MessageDirectionE","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00068:18-34","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ToplevelProtocol","sym":"_ZN7mozilla3ipc9IProtocol16ToplevelProtocolEv","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00068:38-58","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::OtherPidMaybeInvalid","sym":"_ZNK7mozilla3ipc17IToplevelProtocol20OtherPidMaybeInvalidEv","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00070:17-19","target":1,"kind":"use","pretty":"mozilla::UniquePtr::operator->","sym":"_ZNK7mozilla9UniquePtrptEv","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00070:19-23","target":1,"kind":"use","pretty":"IPC::Message::type","sym":"_ZNK3IPC7Message4typeEv","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00071:26-42","target":1,"kind":"use","pretty":"mozilla::ipc::MessageDirection","sym":"T_mozilla::ipc::MessageDirection","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00071:44-52","target":1,"kind":"use","pretty":"mozilla::ipc::MessageDirection::eSending","sym":"E_<T_mozilla::ipc::MessageDirection>_eSending","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00073:4-23","target":1,"kind":"use","pretty":"AUTO_PROFILER_LABEL","sym":"M_99e0335dc782f2d6"}
{"loc":"00073:49-54","target":1,"kind":"use","pretty":"JS::ProfilingCategoryPair::OTHER","sym":"E_<T_JS::ProfilingCategoryPair>_OTHER","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00075:20-31","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ChannelSend","sym":"_ZN7mozilla3ipc9IProtocol11ChannelSendENS_9UniquePtrIN3IPC7MessageENS_13DefaultDeleteIS4_EEEE","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00075:32-35","target":1,"kind":"use","pretty":"mozilla::UniquePtr::UniquePtr<T, D>","sym":"_ZN7mozilla9UniquePtrC1EONS_9UniquePtrIT_T0_EE","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00075:37-41","target":1,"kind":"use","pretty":"std::move","sym":"_ZNSt6__ndk14moveEOT_","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00079:23-36","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::RemoveManagee","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent13RemoveManageeEiPNS_3ipc9IProtocolE","peekRange":"79-81"}
{"loc":"00079:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::RemoveManagee","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent13RemoveManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00080:8-15","target":1,"kind":"use","pretty":"int32_t","sym":"T_int32_t","context":"mozilla::_ipdltest::PTestBasicParent::RemoveManagee","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent13RemoveManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00081:8-17","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::IProtocol","sym":"T_mozilla::_ipdltest::PTestBasicParent::IProtocol","context":"mozilla::_ipdltest::PTestBasicParent::RemoveManagee","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent13RemoveManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00083:4-14","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"mozilla::_ipdltest::PTestBasicParent::RemoveManagee","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent13RemoveManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00087:23-37","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::DeallocManagee","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14DeallocManageeEiPNS_3ipc9IProtocolE","peekRange":"87-89"}
{"loc":"00087:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::DeallocManagee","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14DeallocManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00088:8-15","target":1,"kind":"use","pretty":"int32_t","sym":"T_int32_t","context":"mozilla::_ipdltest::PTestBasicParent::DeallocManagee","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14DeallocManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00089:8-17","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::IProtocol","sym":"T_mozilla::_ipdltest::PTestBasicParent::IProtocol","context":"mozilla::_ipdltest::PTestBasicParent::DeallocManagee","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14DeallocManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00091:4-14","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"mozilla::_ipdltest::PTestBasicParent::DeallocManagee","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14DeallocManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00095:23-40","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE","peekRange":"95-95"}
{"loc":"00095:47-54","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00095:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00095:66-82","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00095:84-90","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00097:18-22","target":1,"kind":"use","pretty":"IPC::Message::type","sym":"_ZNK3IPC7Message4typeEv","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00099:15-26","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00100:9-35","target":1,"kind":"use","pretty":"SHMEM_CREATED_MESSAGE_TYPE","sym":"E_<T_b078e220e89184de>_SHMEM_CREATED_MESSAGE_TYPE","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00102:12-22","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00103:19-30","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00105:9-37","target":1,"kind":"use","pretty":"SHMEM_DESTROYED_MESSAGE_TYPE","sym":"E_<T_b078e220e89184de>_SHMEM_DESTROYED_MESSAGE_TYPE","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00107:12-22","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00108:19-30","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00113:23-40","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","peekRange":"113-115"}
{"loc":"00113:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00114:14-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00115:18-25","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00115:40-56","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00115:58-64","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00115:8-17","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicParent::UniquePtr","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00117:4-26","target":1,"kind":"use","pretty":"MOZ_ASSERT_UNREACHABLE","sym":"M_0d9562839add515c"}
{"loc":"00118:11-22","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00121:23-37","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","peekRange":"121-123"}
{"loc":"00121:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00122:14-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","context":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00123:18-25","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","context":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00123:40-56","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00123:58-64","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","context":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00123:8-17","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicParent::UniquePtr","context":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00125:4-26","target":1,"kind":"use","pretty":"MOZ_ASSERT_UNREACHABLE","sym":"M_0d9562839add515c"}
{"loc":"00126:11-22","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00129:23-37","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv","peekRange":"129-129"}
{"loc":"00129:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv"}
{"loc":"00131:19-33","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ActorDestroyReason::NormalShutdown","sym":"E_<T_mozilla::ipc::IProtocol::ActorDestroyReason>_NormalShutdown","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv"}
{"loc":"00131:4-18","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::DestroySubtree","sym":"_ZN7mozilla3ipc9IProtocol14DestroySubtreeENS1_18ActorDestroyReasonE","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv"}
{"loc":"00132:4-16","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::ClearSubtree","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent12ClearSubtreeEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv"}
{"loc":"00133:4-17","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::DeallocShmems","sym":"_ZN7mozilla3ipc17IToplevelProtocol13DeallocShmemsEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv"}
{"loc":"00134:8-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv"}
{"loc":"00135:29-36","target":1,"kind":"use","pretty":"mozilla::ipc::ActorLifecycleProxy::Release","sym":"_ZN7mozilla3ipc19ActorLifecycleProxy7ReleaseEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv"}
{"loc":"00135:8-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv"}
{"loc":"00139:23-37","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv","peekRange":"139-139"}
{"loc":"00139:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv"}
{"loc":"00141:19-35","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ActorDestroyReason::AbnormalShutdown","sym":"E_<T_mozilla::ipc::IProtocol::ActorDestroyReason>_AbnormalShutdown","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv"}
{"loc":"00141:4-18","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::DestroySubtree","sym":"_ZN7mozilla3ipc9IProtocol14DestroySubtreeENS1_18ActorDestroyReasonE","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv"}
{"loc":"00142:4-16","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent::ClearSubtree","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent12ClearSubtreeEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv"}
{"loc":"00143:4-17","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::DeallocShmems","sym":"_ZN7mozilla3ipc17IToplevelProtocol13DeallocShmemsEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv"}
{"loc":"00144:8-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv"}
{"loc":"00145:29-36","target":1,"kind":"use","pretty":"mozilla::ipc::ActorLifecycleProxy::Release","sym":"_ZN7mozilla3ipc19ActorLifecycleProxy7ReleaseEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv"}
{"loc":"00145:8-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","context":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv"}
{"loc":"00149:23-35","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicParent::ClearSubtree","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent12ClearSubtreeEv","peekRange":"149-149"}
{"loc":"00149:5-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasicParent::ClearSubtree","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent12ClearSubtreeEv"}
{"loc":"00157:10-13","target":1,"kind":"def","pretty":"IPC","sym":"NS_IPC"}
{"loc":"00158:37-53","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00158:5-16","target":1,"kind":"use","pretty":"IPC::ParamTraits","sym":"T_IPC::ParamTraits","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00158:57-62","target":1,"kind":"def","pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_","peekRange":"158-160"}
{"loc":"00159:13-26","target":1,"kind":"use","pretty":"IPC::MessageWriter","sym":"T_IPC::MessageWriter","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00160:14-23","target":1,"kind":"use","pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::paramType","sym":"T_IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent_*>::paramType","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00162:4-22","target":1,"kind":"use","pretty":"MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00163:17-25","target":1,"kind":"use","pretty":"IPC::MessageWriter::GetActor","sym":"_ZNK3IPC13MessageWriter8GetActorEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00166:4-11","target":1,"kind":"use","pretty":"int32_t","sym":"T_int32_t","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00170:19-21","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::Id","sym":"_ZNK7mozilla3ipc9IProtocol2IdEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00172:18-28","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00174:8-26","target":1,"kind":"use","pretty":"MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00175:21-29","target":1,"kind":"use","pretty":"IPC::MessageWriter::GetActor","sym":"_ZNK3IPC13MessageWriter8GetActorEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00175:33-46","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetIPCChannel","sym":"_ZN7mozilla3ipc9IProtocol13GetIPCChannelEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00175:58-71","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::GetIPCChannel","sym":"_ZN7mozilla3ipc17IToplevelProtocol13GetIPCChannelEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00178:8-26","target":1,"kind":"use","pretty":"MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00179:18-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::CanSend","sym":"_ZNK7mozilla3ipc9IProtocol7CanSendEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00183:9-19","target":1,"kind":"use","pretty":"IPC::WriteParam","sym":"_ZN3IPCL10WriteParamEPNS_13MessageWriterEOT_","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00186:37-53","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00186:5-16","target":1,"kind":"use","pretty":"IPC::ParamTraits","sym":"T_IPC::ParamTraits","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00186:57-61","target":1,"kind":"def","pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_","peekRange":"186-188"}
{"loc":"00187:13-26","target":1,"kind":"use","pretty":"IPC::MessageReader","sym":"T_IPC::MessageReader","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00188:8-17","target":1,"kind":"use","pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::paramType","sym":"T_IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent_*>::paramType","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00190:4-22","target":1,"kind":"use","pretty":"MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00191:17-25","target":1,"kind":"use","pretty":"IPC::MessageReader::GetActor","sym":"_ZNK3IPC13MessageReader8GetActorEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00194:13-18","target":1,"kind":"use","pretty":"mozilla::Maybe","sym":"T_mozilla::Maybe","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00194:33-42","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol","sym":"T_mozilla::ipc::IProtocol","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00195:17-25","target":1,"kind":"use","pretty":"IPC::MessageReader::GetActor","sym":"_ZNK3IPC13MessageReader8GetActorEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00195:29-38","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ReadActor","sym":"_ZN7mozilla3ipc9IProtocol9ReadActorEPN3IPC13MessageReaderEbPKci","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00195:68-86","target":1,"kind":"use","pretty":"IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00196:14-23","target":1,"kind":"use","pretty":"mozilla::Maybe::isNothing","sym":"_ZNK7mozilla5Maybe9isNothingEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00200:44-60","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00200:69-74","target":1,"kind":"use","pretty":"mozilla::Maybe::value","sym":"_ZNKR7mozilla5Maybe5valueEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasicParent.cpp","sym":"FILE_linux@__GENERATED__/ipc/ipdl/PTestBasicParent@2Ecpp"}
{"loc":"00007:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00014:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_linux@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00075:37-41","target":1,"kind":"use","pretty":"std::move","sym":"_ZSt4moveOT_","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasicParent.cpp","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/PTestBasicParent@2Ecpp"}
{"loc":"00007:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00014:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_macosx@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00075:37-41","target":1,"kind":"use","pretty":"std::move","sym":"_ZNSt3__14moveEOT_","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasicParent.cpp","sym":"FILE_windows@__GENERATED__/ipc/ipdl/PTestBasicParent@2Ecpp"}
{"loc":"00007:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00014:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_windows@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00066:22-43","target":1,"kind":"use","pretty":"mozilla::ipc::LogMessageForProtocol","sym":"_ZN7mozilla3ipc21LogMessageForProtocolEPKcmS2_jNS0_16MessageDirectionE","context":"mozilla::_ipdltest::PTestBasicParent::SendHello","contextsym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv"}
{"loc":"00001:0","source":1,"syntax":"def,file","pretty":"file __GENERATED__/ipc/ipdl/PTestBasicParent.cpp","sym":"FILE_windows@__GENERATED__/ipc/ipdl/PTestBasicParent@2Ecpp,FILE_macosx@__GENERATED__/ipc/ipdl/PTestBasicParent@2Ecpp,FILE_linux@__GENERATED__/ipc/ipdl/PTestBasicParent@2Ecpp,FILE_android-armv7@__GENERATED__/ipc/ipdl/PTestBasicParent@2Ecpp"}
{"loc":"00007:9-47","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00008:9-35","source":1,"syntax":"file,use","pretty":"file tools/profiler/public/ProfilerLabels.h","sym":"FILE_tools/profiler/public/ProfilerLabels@2Eh"}
{"loc":"00009:9-46","source":1,"syntax":"file,use","pretty":"file ipc/ipdl/test/gtest/TestBasicParent.h","sym":"FILE_ipc/ipdl/test/gtest/TestBasicParent@2Eh"}
{"loc":"00012:9-32","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh"}
{"loc":"00013:9-47","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh"}
{"loc":"00014:9-20","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/nsIFile.h","sym":"FILE_windows@__GENERATED__/dist/include/nsIFile@2Eh,FILE_macosx@__GENERATED__/dist/include/nsIFile@2Eh,FILE_linux@__GENERATED__/dist/include/nsIFile@2Eh,FILE_android-armv7@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00015:9-33","source":1,"syntax":"file,use","pretty":"file ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh"}
{"loc":"00016:9-45","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh"}
{"loc":"00017:9-38","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh"}
{"loc":"00018:9-42","source":1,"syntax":"file,use","pretty":"file ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh"}
{"loc":"00019:9-41","source":1,"syntax":"file,use","pretty":"file ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh"}
{"loc":"00021:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"21:19-156:0"}
{"loc":"00022:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"22:21-155:0"}
{"loc":"00025:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00025:23-38","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::ProcessingError","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc","nestingRange":"28:0-29:0","type":"auto (enum mozilla::ipc::HasResultCodes::Result, const char *) -> void"}
{"loc":"00026:8-14","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00026:15-20","source":1,"syntax":"","pretty":"variable aCode","sym":"V_272dfa605a27c74b_1ebe00f013,V_23bc09de47846456_1ebe00f013,V_7faff616f658d82b_1ebe00f013,V_2659a3d8d0861239_1ebe00f013","no_crossref":1,"type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00027:20-27","source":1,"syntax":"","pretty":"variable aReason","sym":"V_fee50b605a27c74b_ea97235f0b0d,V_fa7519de47846456_ea97235f0b0d,V_47780716f658d82b_ea97235f0b0d,V_fd12b3d8d0861239_ea97235f0b0d","no_crossref":1,"type":"const char *"}
{"loc":"00031:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00031:23-53","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::ShouldContinueFromReplyTimeout","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent30ShouldContinueFromReplyTimeoutEv","nestingRange":"32:0-34:0","type":"auto (void) -> _Bool"}
{"loc":"00036:0-12","source":1,"syntax":"macro,use","pretty":"macro MOZ_IMPLICIT","sym":"M_5f65895d5a5258f7"}
{"loc":"00036:13-29","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00036:31-47","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","sym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev","nestingRange":"38:0-40:0","type":"void (void)"}
{"loc":"00037:4-11","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::ipc::IToplevelProtocol::IToplevelProtocol","sym":"_ZN7mozilla3ipc17IToplevelProtocolC1EPKc15IPCMessageStartNS0_4SideE"}
{"loc":"00037:18-35","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::IToplevelProtocol","sym":"T_mozilla::ipc::IToplevelProtocol","type":"class mozilla::ipc::IToplevelProtocol","typesym":"T_mozilla::ipc::IToplevelProtocol"}
{"loc":"00037:56-74","source":1,"syntax":"enum,use","pretty":"enum IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","type":"enum IPCMessageStart","typesym":"T_IPCMessageStart"}
{"loc":"00037:90-100","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::Side::ParentSide","sym":"E_<T_mozilla::ipc::Side>_ParentSide","type":"enum mozilla::ipc::Side","typesym":"T_mozilla::ipc::Side"}
{"loc":"00039:4-18","source":1,"syntax":"macro,use","pretty":"macro MOZ_COUNT_CTOR","sym":"M_d9d58f5149d9f0f2"}
{"loc":"00039:19-35","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00042:0-16","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00042:19-35","source":1,"syntax":"def,destructor","pretty":"destructor mozilla::_ipdltest::PTestBasicParent::~PTestBasicParent","sym":"_ZN7mozilla9_ipdltest16PTestBasicParentD1Ev","nestingRange":"43:0-45:0","type":"void (void) noexcept"}
{"loc":"00042:19-35","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00044:4-18","source":1,"syntax":"macro,use","pretty":"macro MOZ_COUNT_DTOR","sym":"M_f9e8c16149d9f0f2"}
{"loc":"00044:19-35","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00047:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00047:23-39","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::AllManagedActors","sym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE","nestingRange":"48:0-52:0","type":"auto (nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy> > &) const -> void"}
{"loc":"00047:40-48","source":1,"syntax":"type,use","pretty":"type nsTArray","sym":"T_nsTArray"}
{"loc":"00047:49-55","source":1,"syntax":"type,use","pretty":"type RefPtr","sym":"T_RefPtr"}
{"loc":"00047:70-89","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::ActorLifecycleProxy","sym":"T_mozilla::ipc::ActorLifecycleProxy","type":"class mozilla::ipc::ActorLifecycleProxy","typesym":"T_mozilla::ipc::ActorLifecycleProxy"}
{"loc":"00047:93-98","source":1,"syntax":"","pretty":"variable arr__","sym":"V_bd094d605a27c74b_8cdba1f013,V_b9985bde47846456_8cdba1f013,V_069b4916f658d82b_8cdba1f013,V_bc35f5d8d0861239_8cdba1f013","no_crossref":1,"type":"nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy> > &"}
{"loc":"00049:4-12","source":1,"syntax":"type,use","pretty":"type uint32_t","sym":"T_uint32_t","type":"uint32_t"}
{"loc":"00049:13-18","source":1,"syntax":"","pretty":"variable total","sym":"V_598a5d605a27c74b_903f070113,V_551a6bde47846456_903f070113,V_a11d5916f658d82b_903f070113,V_58b606d8d0861239_903f070113","no_crossref":1,"type":"uint32_t"}
{"loc":"00050:4-9","source":1,"syntax":"","pretty":"variable arr__","sym":"V_bd094d605a27c74b_8cdba1f013,V_b9985bde47846456_8cdba1f013,V_069b4916f658d82b_8cdba1f013,V_bc35f5d8d0861239_8cdba1f013","no_crossref":1,"type":"nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy> > &"}
{"loc":"00050:10-21","source":1,"syntax":"function,use","pretty":"function nsTArray_Impl::SetCapacity","sym":"_ZN13nsTArray_Impl11SetCapacityEN13nsTArray_baseIT0_N27nsTArray_RelocationStrategyIT_E4TypeEE9size_typeE","type":"typename struct nsTArrayInfallibleAllocator::ResultType"}
{"loc":"00050:22-27","source":1,"syntax":"","pretty":"variable total","sym":"V_598a5d605a27c74b_903f070113,V_551a6bde47846456_903f070113,V_a11d5916f658d82b_903f070113,V_58b606d8d0861239_903f070113","no_crossref":1,"type":"uint32_t"}
{"loc":"00054:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00054:23-32","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::SendHello","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv","nestingRange":"55:0-77:0","type":"auto (void) -> _Bool"}
{"loc":"00056:4-13","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicParent::UniquePtr"}
{"loc":"00056:19-26","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00056:28-33","source":1,"syntax":"","pretty":"variable msg__","sym":"V_91c16e605a27c74b_a6144ff013,V_9d417cde47846456_a6144ff013,V_e9446a16f658d82b_a6144ff013,V_90fd07d8d0861239_a6144ff013","no_crossref":1,"type":"UniquePtr<IPC::Message>","typesym":"T_mozilla::UniquePtr"}
{"loc":"00056:48-57","source":1,"syntax":"function,use","pretty":"function mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi","type":"mozilla::UniquePtr<IPC::Message> (int32_t)"}
{"loc":"00056:58-77","source":1,"syntax":"enum,use","pretty":"enum SpecialRoutingIDs::MSG_ROUTING_CONTROL","sym":"E_<T_SpecialRoutingIDs>_MSG_ROUTING_CONTROL","type":"enum SpecialRoutingIDs","typesym":"T_SpecialRoutingIDs"}
{"loc":"00057:9-22","source":1,"syntax":"type,use","pretty":"type IPC::MessageWriter","sym":"T_IPC::MessageWriter","type":"class IPC::MessageWriter","typesym":"T_IPC::MessageWriter"}
{"loc":"00057:23-31","source":1,"syntax":"constructor,use","pretty":"constructor IPC::MessageWriter::MessageWriter","sym":"_ZN3IPC13MessageWriterC1ERNS_7MessageEPN7mozilla3ipc9IProtocolE"}
{"loc":"00057:23-31","source":1,"syntax":"","pretty":"variable writer__","sym":"V_578a6e605a27c74b_0e4661393b7ea1,V_531a7cde47846456_0e4661393b7ea1,V_af0d6a16f658d82b_0e4661393b7ea1,V_56b617d8d0861239_0e4661393b7ea1","no_crossref":1,"type":"IPC::MessageWriter","typesym":"T_IPC::MessageWriter"}
{"loc":"00058:13-14","source":1,"syntax":"function,use","pretty":"function mozilla::UniquePtr::operator*","sym":"_ZNK7mozilla9UniquePtrdeEv","type":"std::add_lvalue_reference_t<Message>"}
{"loc":"00058:15-20","source":1,"syntax":"","pretty":"variable msg__","sym":"V_91c16e605a27c74b_a6144ff013,V_9d417cde47846456_a6144ff013,V_e9446a16f658d82b_a6144ff013,V_90fd07d8d0861239_a6144ff013","no_crossref":1,"type":"UniquePtr<IPC::Message>","typesym":"T_mozilla::UniquePtr"}
{"loc":"00065:22-39","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::LoggingEnabledFor","sym":"_ZN7mozilla3ipc17LoggingEnabledForEPKc","type":"_Bool (const char *)"}
{"loc":"00066:22-43","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::LogMessageForProtocol","sym":"_ZN7mozilla3ipc21LogMessageForProtocolEPKcmS2_jNS0_16MessageDirectionE,_ZN7mozilla3ipc21LogMessageForProtocolEPKciS2_jNS0_16MessageDirectionE","type":"void (const char *, base::ProcessId, const char *, uint32_t, enum mozilla::ipc::MessageDirection)"}
{"loc":"00068:18-34","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::ToplevelProtocol","sym":"_ZN7mozilla3ipc9IProtocol16ToplevelProtocolEv","type":"class mozilla::ipc::IToplevelProtocol *"}
{"loc":"00068:38-58","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IToplevelProtocol::OtherPidMaybeInvalid","sym":"_ZNK7mozilla3ipc17IToplevelProtocol20OtherPidMaybeInvalidEv","type":"base::ProcessId"}
{"loc":"00070:12-17","source":1,"syntax":"","pretty":"variable msg__","sym":"V_91c16e605a27c74b_a6144ff013,V_9d417cde47846456_a6144ff013,V_e9446a16f658d82b_a6144ff013,V_90fd07d8d0861239_a6144ff013","no_crossref":1,"type":"UniquePtr<IPC::Message>","typesym":"T_mozilla::UniquePtr"}
{"loc":"00070:17-19","source":1,"syntax":"function,use","pretty":"function mozilla::UniquePtr::operator->","sym":"_ZNK7mozilla9UniquePtrptEv","type":"mozilla::UniquePtr<class IPC::Message>::Pointer"}
{"loc":"00070:19-23","source":1,"syntax":"function,use","pretty":"function IPC::Message::type","sym":"_ZNK3IPC7Message4typeEv","type":"IPC::Message::msgid_t"}
{"loc":"00071:26-42","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::MessageDirection","sym":"T_mozilla::ipc::MessageDirection","type":"enum mozilla::ipc::MessageDirection","typesym":"T_mozilla::ipc::MessageDirection"}
{"loc":"00071:44-52","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::MessageDirection::eSending","sym":"E_<T_mozilla::ipc::MessageDirection>_eSending","type":"enum mozilla::ipc::MessageDirection","typesym":"T_mozilla::ipc::MessageDirection"}
{"loc":"00073:4-23","source":1,"syntax":"macro,use","pretty":"macro AUTO_PROFILER_LABEL","sym":"M_99e0335dc782f2d6"}
{"loc":"00073:4-23","source":1,"syntax":"","pretty":"variable raiiObject73","sym":"V_5e5b2_b669d3b76a0990ad","no_crossref":1,"type":"mozilla::AutoProfilerLabel","typesym":"T_mozilla::AutoProfilerLabel"}
{"loc":"00073:49-54","source":1,"syntax":"enum,use","pretty":"enum JS::ProfilingCategoryPair::OTHER","sym":"E_<T_JS::ProfilingCategoryPair>_OTHER","type":"enum JS::ProfilingCategoryPair","typesym":"T_JS::ProfilingCategoryPair"}
{"loc":"00075:9-17","source":1,"syntax":"","pretty":"variable sendok__","sym":"V_948b2b0f6c935d97_7ac97e30887ea1,V_90997fe031685921_7ac97e30887ea1,V_e246d1e9bf5c4f33_7ac97e30887ea1,V_93dd87eb55db9e5d_7ac97e30887ea1","no_crossref":1,"type":"_Bool"}
{"loc":"00075:20-31","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::ChannelSend","sym":"_ZN7mozilla3ipc9IProtocol11ChannelSendENS_9UniquePtrIN3IPC7MessageENS_13DefaultDeleteIS4_EEEE","type":"_Bool"}
{"loc":"00075:32-35","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::UniquePtr::UniquePtr<T, D>","sym":"_ZN7mozilla9UniquePtrC1EONS_9UniquePtrIT_T0_EE"}
{"loc":"00075:37-41","source":1,"syntax":"function,use","pretty":"function std::move","sym":"_ZSt4moveOT_,_ZNSt3__14moveEOT_,_ZNSt6__ndk14moveEOT_","type":"typename remove_reference<class UniquePtr<class Message> &>::type &&(class mozilla::UniquePtr<class IPC::Message> &) noexcept"}
{"loc":"00075:42-47","source":1,"syntax":"","pretty":"variable msg__","sym":"V_91c16e605a27c74b_a6144ff013,V_9d417cde47846456_a6144ff013,V_e9446a16f658d82b_a6144ff013,V_90fd07d8d0861239_a6144ff013","no_crossref":1,"type":"UniquePtr<IPC::Message>","typesym":"T_mozilla::UniquePtr"}
{"loc":"00076:11-19","source":1,"syntax":"","pretty":"variable sendok__","sym":"V_948b2b0f6c935d97_7ac97e30887ea1,V_90997fe031685921_7ac97e30887ea1,V_e246d1e9bf5c4f33_7ac97e30887ea1,V_93dd87eb55db9e5d_7ac97e30887ea1","no_crossref":1,"type":"_Bool"}
{"loc":"00079:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00079:23-36","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::RemoveManagee","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent13RemoveManageeEiPNS_3ipc9IProtocolE","nestingRange":"82:0-85:0","type":"auto (int32_t, mozilla::_ipdltest::PTestBasicParent::IProtocol *) -> void"}
{"loc":"00080:8-15","source":1,"syntax":"type,use","pretty":"type int32_t","sym":"T_int32_t","type":"int32_t"}
{"loc":"00080:16-27","source":1,"syntax":"","pretty":"variable aProtocolId","sym":"V_33b191705a27c74b_542cb52f47aba60c,V_3f31afde47846456_542cb52f47aba60c,V_8b349d16f658d82b_542cb52f47aba60c,V_32ed3ad8d0861239_542cb52f47aba60c","no_crossref":1,"type":"int32_t"}
{"loc":"00081:8-17","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::IProtocol","sym":"T_mozilla::_ipdltest::PTestBasicParent::IProtocol","type":"mozilla::_ipdltest::PTestBasicParent::IProtocol","typesym":"T_mozilla::ipc::IProtocol"}
{"loc":"00081:19-28","source":1,"syntax":"","pretty":"variable aListener","sym":"V_797a91705a27c74b_c681f10e880c773,V_750aafde47846456_c681f10e880c773,V_c10d9d16f658d82b_c681f10e880c773,V_78a64ad8d0861239_c681f10e880c773","no_crossref":1,"type":"mozilla::_ipdltest::PTestBasicParent::IProtocol *"}
{"loc":"00083:4-14","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00087:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00087:23-37","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::DeallocManagee","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14DeallocManageeEiPNS_3ipc9IProtocolE","nestingRange":"90:0-93:0","type":"auto (int32_t, mozilla::_ipdltest::PTestBasicParent::IProtocol *) -> void"}
{"loc":"00088:8-15","source":1,"syntax":"type,use","pretty":"type int32_t","sym":"T_int32_t","type":"int32_t"}
{"loc":"00088:16-27","source":1,"syntax":"","pretty":"variable aProtocolId","sym":"V_b3e7d1705a27c74b_542cb52f47aba60c,V_bf67efde47846456_542cb52f47aba60c,V_0c6add16f658d82b_542cb52f47aba60c,V_b2148ad8d0861239_542cb52f47aba60c","no_crossref":1,"type":"int32_t"}
{"loc":"00089:8-17","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::IProtocol","sym":"T_mozilla::_ipdltest::PTestBasicParent::IProtocol","type":"mozilla::_ipdltest::PTestBasicParent::IProtocol","typesym":"T_mozilla::ipc::IProtocol"}
{"loc":"00089:19-28","source":1,"syntax":"","pretty":"variable aListener","sym":"V_f9a0e1705a27c74b_c681f10e880c773,V_f530ffde47846456_c681f10e880c773,V_4233ed16f658d82b_c681f10e880c773,V_f8dc8ad8d0861239_c681f10e880c773","no_crossref":1,"type":"mozilla::_ipdltest::PTestBasicParent::IProtocol *"}
{"loc":"00091:4-14","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00095:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00095:23-40","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE","nestingRange":"96:0-111:0","type":"auto (const mozilla::_ipdltest::PTestBasicParent::Message &) -> class PTestBasicParent::Result"}
{"loc":"00095:47-54","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","type":"mozilla::_ipdltest::PTestBasicParent::Message","typesym":"T_IPC::Message"}
{"loc":"00095:56-61","source":1,"syntax":"","pretty":"variable msg__","sym":"V_d12fd2705a27c74b_a6144ff013,V_ddaee0ee47846456_a6144ff013,V_2aa1ee16f658d82b_a6144ff013,V_d05b8bd8d0861239_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicParent::Message &"}
{"loc":"00095:66-82","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00095:84-90","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00097:12-17","source":1,"syntax":"","pretty":"variable msg__","sym":"V_d12fd2705a27c74b_a6144ff013,V_ddaee0ee47846456_a6144ff013,V_2aa1ee16f658d82b_a6144ff013,V_d05b8bd8d0861239_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicParent::Message &"}
{"loc":"00097:18-22","source":1,"syntax":"function,use","pretty":"function IPC::Message::type","sym":"_ZNK3IPC7Message4typeEv","type":"IPC::Message::msgid_t"}
{"loc":"00099:15-26","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00100:9-35","source":1,"syntax":"enum,use","pretty":"enum SHMEM_CREATED_MESSAGE_TYPE","sym":"E_<T_b078e220e89184de>_SHMEM_CREATED_MESSAGE_TYPE","type":"enum (anonymous namespace)::(unnamed at /builds/worker/workspace/obj-build/dist/include/mozilla/ipc/ProtocolUtils.h:57:1)","typesym":"T_b078e220e89184de"}
{"loc":"00102:12-22","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00103:19-30","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00105:9-37","source":1,"syntax":"enum,use","pretty":"enum SHMEM_DESTROYED_MESSAGE_TYPE","sym":"E_<T_b078e220e89184de>_SHMEM_DESTROYED_MESSAGE_TYPE","type":"enum (anonymous namespace)::(unnamed at /builds/worker/workspace/obj-build/dist/include/mozilla/ipc/ProtocolUtils.h:57:1)","typesym":"T_b078e220e89184de"}
{"loc":"00107:12-22","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00108:19-30","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00113:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00113:23-40","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","nestingRange":"116:0-119:0","type":"auto (const mozilla::_ipdltest::PTestBasicParent::Message &, UniquePtr<mozilla::_ipdltest::PTestBasicParent::Message> &) -> class PTestBasicParent::Result"}
{"loc":"00114:14-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","type":"mozilla::_ipdltest::PTestBasicParent::Message","typesym":"T_IPC::Message"}
{"loc":"00114:23-28","source":1,"syntax":"","pretty":"variable msg__","sym":"V_fe9c1f805a27c74b_a6144ff013,V_fa2c2dfe47846456_a6144ff013,V_472f1b36f658d82b_a6144ff013,V_fdc8c7f8d0861239_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicParent::Message &"}
{"loc":"00115:8-17","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicParent::UniquePtr"}
{"loc":"00115:18-25","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","type":"mozilla::_ipdltest::PTestBasicParent::Message","typesym":"T_IPC::Message"}
{"loc":"00115:28-35","source":1,"syntax":"","pretty":"variable reply__","sym":"V_55652f805a27c74b_f83bfee36b0d,V_51f43dfe47846456_f83bfee36b0d,V_ade72b36f658d82b_f83bfee36b0d,V_5491d7f8d0861239_f83bfee36b0d","no_crossref":1,"type":"UniquePtr<mozilla::_ipdltest::PTestBasicParent::Message> &"}
{"loc":"00115:40-56","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00115:58-64","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00117:4-26","source":1,"syntax":"macro,use","pretty":"macro MOZ_ASSERT_UNREACHABLE","sym":"M_0d9562839add515c"}
{"loc":"00118:11-22","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00121:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00121:23-37","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::OnCallReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","nestingRange":"124:0-127:0","type":"auto (const mozilla::_ipdltest::PTestBasicParent::Message &, UniquePtr<mozilla::_ipdltest::PTestBasicParent::Message> &) -> class PTestBasicParent::Result"}
{"loc":"00122:14-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","type":"mozilla::_ipdltest::PTestBasicParent::Message","typesym":"T_IPC::Message"}
{"loc":"00122:23-28","source":1,"syntax":"","pretty":"variable msg__","sym":"V_ea9c20905a27c74b_a6144ff013,V_e62c3efe47846456_a6144ff013,V_332f2c36f658d82b_a6144ff013,V_e9c8d8f8d0861239_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicParent::Message &"}
{"loc":"00123:8-17","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicParent::UniquePtr"}
{"loc":"00123:18-25","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent::Message","sym":"T_mozilla::_ipdltest::PTestBasicParent::Message","type":"mozilla::_ipdltest::PTestBasicParent::Message","typesym":"T_IPC::Message"}
{"loc":"00123:28-35","source":1,"syntax":"","pretty":"variable reply__","sym":"V_416530905a27c74b_f83bfee36b0d,V_4de44efe47846456_f83bfee36b0d,V_99e73c36f658d82b_f83bfee36b0d,V_4091e8f8d0861239_f83bfee36b0d","no_crossref":1,"type":"UniquePtr<mozilla::_ipdltest::PTestBasicParent::Message> &"}
{"loc":"00123:40-56","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00123:58-64","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00125:4-26","source":1,"syntax":"macro,use","pretty":"macro MOZ_ASSERT_UNREACHABLE","sym":"M_0d9562839add515c"}
{"loc":"00126:11-22","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00129:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00129:23-37","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::OnChannelClose","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv","nestingRange":"130:0-137:0","type":"auto (void) -> void"}
{"loc":"00131:4-18","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::DestroySubtree","sym":"_ZN7mozilla3ipc9IProtocol14DestroySubtreeENS1_18ActorDestroyReasonE","type":"void"}
{"loc":"00131:19-33","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::IProtocol::ActorDestroyReason::NormalShutdown","sym":"E_<T_mozilla::ipc::IProtocol::ActorDestroyReason>_NormalShutdown","type":"enum mozilla::ipc::IProtocol::ActorDestroyReason","typesym":"T_mozilla::ipc::IProtocol::ActorDestroyReason"}
{"loc":"00132:4-16","source":1,"syntax":"function,use","pretty":"function mozilla::_ipdltest::PTestBasicParent::ClearSubtree","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent12ClearSubtreeEv","type":"void"}
{"loc":"00133:4-17","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IToplevelProtocol::DeallocShmems","sym":"_ZN7mozilla3ipc17IToplevelProtocol13DeallocShmemsEv","type":"void"}
{"loc":"00134:8-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","type":"class mozilla::ipc::ActorLifecycleProxy *"}
{"loc":"00135:8-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","type":"class mozilla::ipc::ActorLifecycleProxy *"}
{"loc":"00135:29-36","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::ActorLifecycleProxy::Release","sym":"_ZN7mozilla3ipc19ActorLifecycleProxy7ReleaseEv","type":"MozExternalRefCountType"}
{"loc":"00139:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00139:23-37","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::OnChannelError","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv","nestingRange":"140:0-147:0","type":"auto (void) -> void"}
{"loc":"00141:4-18","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::DestroySubtree","sym":"_ZN7mozilla3ipc9IProtocol14DestroySubtreeENS1_18ActorDestroyReasonE","type":"void"}
{"loc":"00141:19-35","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::IProtocol::ActorDestroyReason::AbnormalShutdown","sym":"E_<T_mozilla::ipc::IProtocol::ActorDestroyReason>_AbnormalShutdown","type":"enum mozilla::ipc::IProtocol::ActorDestroyReason","typesym":"T_mozilla::ipc::IProtocol::ActorDestroyReason"}
{"loc":"00142:4-16","source":1,"syntax":"function,use","pretty":"function mozilla::_ipdltest::PTestBasicParent::ClearSubtree","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent12ClearSubtreeEv","type":"void"}
{"loc":"00143:4-17","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IToplevelProtocol::DeallocShmems","sym":"_ZN7mozilla3ipc17IToplevelProtocol13DeallocShmemsEv","type":"void"}
{"loc":"00144:8-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","type":"class mozilla::ipc::ActorLifecycleProxy *"}
{"loc":"00145:8-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","type":"class mozilla::ipc::ActorLifecycleProxy *"}
{"loc":"00145:29-36","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::ActorLifecycleProxy::Release","sym":"_ZN7mozilla3ipc19ActorLifecycleProxy7ReleaseEv","type":"MozExternalRefCountType"}
{"loc":"00149:5-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00149:23-35","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicParent::ClearSubtree","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent12ClearSubtreeEv","nestingRange":"150:0-151:0","type":"auto (void) -> void"}
{"loc":"00157:10-13","source":1,"syntax":"def,namespace","pretty":"namespace IPC","sym":"NS_IPC","nestingRange":"157:15-204:0"}
{"loc":"00158:5-16","source":1,"syntax":"type,use","pretty":"type IPC::ParamTraits","sym":"T_IPC::ParamTraits"}
{"loc":"00158:37-53","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00158:57-62","source":1,"syntax":"def,function","pretty":"function IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_","nestingRange":"161:0-184:0","type":"auto (IPC::MessageWriter *, const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType &) -> void"}
{"loc":"00159:13-26","source":1,"syntax":"type,use","pretty":"type IPC::MessageWriter","sym":"T_IPC::MessageWriter","type":"class IPC::MessageWriter","typesym":"T_IPC::MessageWriter"}
{"loc":"00159:28-35","source":1,"syntax":"","pretty":"variable aWriter","sym":"V_dd9ec3905a27c74b_369ebc101b0d,V_d92ed10f47846456_369ebc101b0d,V_2621df36f658d82b_369ebc101b0d,V_dcca7cf8d0861239_369ebc101b0d","no_crossref":1,"type":"IPC::MessageWriter *"}
{"loc":"00160:14-23","source":1,"syntax":"type,use","pretty":"type IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::paramType","sym":"T_IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent_*>::paramType","type":"IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType"}
{"loc":"00160:25-29","source":1,"syntax":"","pretty":"variable aVar","sym":"V_2f21a4905a27c74b_f0bb39c71,V_2bb0b20f47846456_f0bb39c71,V_77b3a046f658d82b_f0bb39c71,V_2e5d4df8d0861239_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType &"}
{"loc":"00162:4-22","source":1,"syntax":"macro,use","pretty":"macro MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00163:8-15","source":1,"syntax":"","pretty":"variable aWriter","sym":"V_dd9ec3905a27c74b_369ebc101b0d,V_d92ed10f47846456_369ebc101b0d,V_2621df36f658d82b_369ebc101b0d,V_dcca7cf8d0861239_369ebc101b0d","no_crossref":1,"type":"IPC::MessageWriter *"}
{"loc":"00163:17-25","source":1,"syntax":"function,use","pretty":"function IPC::MessageWriter::GetActor","sym":"_ZNK3IPC13MessageWriter8GetActorEv","type":"mozilla::ipc::IProtocol *"}
{"loc":"00166:4-11","source":1,"syntax":"type,use","pretty":"type int32_t","sym":"T_int32_t","type":"int32_t"}
{"loc":"00166:12-14","source":1,"syntax":"","pretty":"variable id","sym":"V_41d5d4905a27c74b_238795,V_4d55e20f47846456_238795,V_9958d046f658d82b_238795,V_40028df8d0861239_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00167:9-13","source":1,"syntax":"","pretty":"variable aVar","sym":"V_2f21a4905a27c74b_f0bb39c71,V_2bb0b20f47846456_f0bb39c71,V_77b3a046f658d82b_f0bb39c71,V_2e5d4df8d0861239_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType &"}
{"loc":"00168:8-10","source":1,"syntax":"","pretty":"variable id","sym":"V_41d5d4905a27c74b_238795,V_4d55e20f47846456_238795,V_9958d046f658d82b_238795,V_40028df8d0861239_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00170:8-10","source":1,"syntax":"","pretty":"variable id","sym":"V_41d5d4905a27c74b_238795,V_4d55e20f47846456_238795,V_9958d046f658d82b_238795,V_40028df8d0861239_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00170:13-17","source":1,"syntax":"","pretty":"variable aVar","sym":"V_2f21a4905a27c74b_f0bb39c71,V_2bb0b20f47846456_f0bb39c71,V_77b3a046f658d82b_f0bb39c71,V_2e5d4df8d0861239_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType &"}
{"loc":"00170:19-21","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::Id","sym":"_ZNK7mozilla3ipc9IProtocol2IdEv","type":"int32_t"}
{"loc":"00171:12-14","source":1,"syntax":"","pretty":"variable id","sym":"V_41d5d4905a27c74b_238795,V_4d55e20f47846456_238795,V_9958d046f658d82b_238795,V_40028df8d0861239_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00172:12-16","source":1,"syntax":"","pretty":"variable aVar","sym":"V_2f21a4905a27c74b_f0bb39c71,V_2bb0b20f47846456_f0bb39c71,V_77b3a046f658d82b_f0bb39c71,V_2e5d4df8d0861239_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType &"}
{"loc":"00172:18-28","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00174:8-26","source":1,"syntax":"macro,use","pretty":"macro MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00175:12-19","source":1,"syntax":"","pretty":"variable aWriter","sym":"V_dd9ec3905a27c74b_369ebc101b0d,V_d92ed10f47846456_369ebc101b0d,V_2621df36f658d82b_369ebc101b0d,V_dcca7cf8d0861239_369ebc101b0d","no_crossref":1,"type":"IPC::MessageWriter *"}
{"loc":"00175:21-29","source":1,"syntax":"function,use","pretty":"function IPC::MessageWriter::GetActor","sym":"_ZNK3IPC13MessageWriter8GetActorEv","type":"mozilla::ipc::IProtocol *"}
{"loc":"00175:33-46","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetIPCChannel","sym":"_ZN7mozilla3ipc9IProtocol13GetIPCChannelEv","type":"class mozilla::ipc::MessageChannel *"}
{"loc":"00175:52-56","source":1,"syntax":"","pretty":"variable aVar","sym":"V_2f21a4905a27c74b_f0bb39c71,V_2bb0b20f47846456_f0bb39c71,V_77b3a046f658d82b_f0bb39c71,V_2e5d4df8d0861239_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType &"}
{"loc":"00175:58-71","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IToplevelProtocol::GetIPCChannel","sym":"_ZN7mozilla3ipc17IToplevelProtocol13GetIPCChannelEv","type":"class mozilla::ipc::MessageChannel *"}
{"loc":"00178:8-26","source":1,"syntax":"macro,use","pretty":"macro MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00179:12-16","source":1,"syntax":"","pretty":"variable aVar","sym":"V_2f21a4905a27c74b_f0bb39c71,V_2bb0b20f47846456_f0bb39c71,V_77b3a046f658d82b_f0bb39c71,V_2e5d4df8d0861239_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType &"}
{"loc":"00179:18-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::CanSend","sym":"_ZNK7mozilla3ipc9IProtocol7CanSendEv","type":"_Bool"}
{"loc":"00183:9-19","source":1,"syntax":"function,use","pretty":"function IPC::WriteParam","sym":"_ZN3IPCL10WriteParamEPNS_13MessageWriterEOT_","type":"void (class IPC::MessageWriter *, int &)"}
{"loc":"00183:20-27","source":1,"syntax":"","pretty":"variable aWriter","sym":"V_dd9ec3905a27c74b_369ebc101b0d,V_d92ed10f47846456_369ebc101b0d,V_2621df36f658d82b_369ebc101b0d,V_dcca7cf8d0861239_369ebc101b0d","no_crossref":1,"type":"IPC::MessageWriter *"}
{"loc":"00183:29-31","source":1,"syntax":"","pretty":"variable id","sym":"V_41d5d4905a27c74b_238795,V_4d55e20f47846456_238795,V_9958d046f658d82b_238795,V_40028df8d0861239_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00186:5-16","source":1,"syntax":"type,use","pretty":"type IPC::ParamTraits","sym":"T_IPC::ParamTraits"}
{"loc":"00186:37-53","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00186:57-61","source":1,"syntax":"def,function","pretty":"function IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_","nestingRange":"189:0-202:0","type":"auto (IPC::MessageReader *, IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType *) -> _Bool"}
{"loc":"00187:13-26","source":1,"syntax":"type,use","pretty":"type IPC::MessageReader","sym":"T_IPC::MessageReader","type":"class IPC::MessageReader","typesym":"T_IPC::MessageReader"}
{"loc":"00187:28-35","source":1,"syntax":"","pretty":"variable aReader","sym":"V_e9a127905a27c74b_9983235f0b0d,V_e531350f47846456_9983235f0b0d,V_32342346f658d82b_9983235f0b0d,V_e8ddcff8d0861239_9983235f0b0d","no_crossref":1,"type":"IPC::MessageReader *"}
{"loc":"00188:8-17","source":1,"syntax":"type,use","pretty":"type IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::paramType","sym":"T_IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent_*>::paramType","type":"IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType"}
{"loc":"00188:19-23","source":1,"syntax":"","pretty":"variable aVar","sym":"V_fd6a27905a27c74b_f0bb39c71,V_f9f9350f47846456_f0bb39c71,V_46fc2346f658d82b_f0bb39c71,V_fc96dff8d0861239_f0bb39c71","no_crossref":1,"type":"IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType *"}
{"loc":"00190:4-22","source":1,"syntax":"macro,use","pretty":"macro MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00191:8-15","source":1,"syntax":"","pretty":"variable aReader","sym":"V_e9a127905a27c74b_9983235f0b0d,V_e531350f47846456_9983235f0b0d,V_32342346f658d82b_9983235f0b0d,V_e8ddcff8d0861239_9983235f0b0d","no_crossref":1,"type":"IPC::MessageReader *"}
{"loc":"00191:17-25","source":1,"syntax":"function,use","pretty":"function IPC::MessageReader::GetActor","sym":"_ZNK3IPC13MessageReader8GetActorEv","type":"mozilla::ipc::IProtocol *"}
{"loc":"00194:13-18","source":1,"syntax":"type,use","pretty":"type mozilla::Maybe","sym":"T_mozilla::Maybe"}
{"loc":"00194:33-42","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::IProtocol","sym":"T_mozilla::ipc::IProtocol","type":"class mozilla::ipc::IProtocol","typesym":"T_mozilla::ipc::IProtocol"}
{"loc":"00194:45-50","source":1,"syntax":"","pretty":"variable actor","sym":"V_b3e828905a27c74b_ebe821f013,V_bf68360f47846456_ebe821f013,V_0c6b2446f658d82b_ebe821f013,V_b215d009d0861239_ebe821f013","no_crossref":1,"type":"mozilla::Maybe<mozilla::ipc::IProtocol *>","typesym":"T_mozilla::Maybe"}
{"loc":"00195:8-15","source":1,"syntax":"","pretty":"variable aReader","sym":"V_e9a127905a27c74b_9983235f0b0d,V_e531350f47846456_9983235f0b0d,V_32342346f658d82b_9983235f0b0d,V_e8ddcff8d0861239_9983235f0b0d","no_crossref":1,"type":"IPC::MessageReader *"}
{"loc":"00195:17-25","source":1,"syntax":"function,use","pretty":"function IPC::MessageReader::GetActor","sym":"_ZNK3IPC13MessageReader8GetActorEv","type":"mozilla::ipc::IProtocol *"}
{"loc":"00195:29-38","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::ReadActor","sym":"_ZN7mozilla3ipc9IProtocol9ReadActorEPN3IPC13MessageReaderEbPKci","type":"Maybe<class mozilla::ipc::IProtocol *>","typesym":"T_mozilla::Maybe"}
{"loc":"00195:39-46","source":1,"syntax":"","pretty":"variable aReader","sym":"V_e9a127905a27c74b_9983235f0b0d,V_e531350f47846456_9983235f0b0d,V_32342346f658d82b_9983235f0b0d,V_e8ddcff8d0861239_9983235f0b0d","no_crossref":1,"type":"IPC::MessageReader *"}
{"loc":"00195:68-86","source":1,"syntax":"enum,use","pretty":"enum IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","type":"enum IPCMessageStart","typesym":"T_IPCMessageStart"}
{"loc":"00196:8-13","source":1,"syntax":"","pretty":"variable actor","sym":"V_b3e828905a27c74b_ebe821f013,V_bf68360f47846456_ebe821f013,V_0c6b2446f658d82b_ebe821f013,V_b215d009d0861239_ebe821f013","no_crossref":1,"type":"mozilla::Maybe<mozilla::ipc::IProtocol *>","typesym":"T_mozilla::Maybe"}
{"loc":"00196:14-23","source":1,"syntax":"function,use","pretty":"function mozilla::Maybe::isNothing","sym":"_ZNK7mozilla5Maybe9isNothingEv","type":"_Bool"}
{"loc":"00200:5-9","source":1,"syntax":"","pretty":"variable aVar","sym":"V_fd6a27905a27c74b_f0bb39c71,V_f9f9350f47846456_f0bb39c71,V_46fc2346f658d82b_f0bb39c71,V_fc96dff8d0861239_f0bb39c71","no_crossref":1,"type":"IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicParent *>::paramType *"}
{"loc":"00200:44-60","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00200:63-68","source":1,"syntax":"","pretty":"variable actor","sym":"V_b3e828905a27c74b_ebe821f013,V_bf68360f47846456_ebe821f013,V_0c6b2446f658d82b_ebe821f013,V_b215d009d0861239_ebe821f013","no_crossref":1,"type":"mozilla::Maybe<mozilla::ipc::IProtocol *>","typesym":"T_mozilla::Maybe"}
{"loc":"00200:69-74","source":1,"syntax":"function,use","pretty":"function mozilla::Maybe::value","sym":"_ZNKR7mozilla5Maybe5valueEv","type":"class mozilla::ipc::IProtocol *"}
{"loc":"00186:57-61","structured":1,"pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Read","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE4ReadEPNS_13MessageReaderEPS4_","kind":"method","parentsym":"T_IPC::ParamTraits","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["static","user"]}
{"loc":"00158:57-62","structured":1,"pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicParent *>::Write","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest16PTestBasicParentEE5WriteEPNS_13MessageWriterERKS4_","kind":"method","parentsym":"T_IPC::ParamTraits","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["static","user"]}
{"loc":"00149:23-35","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::ClearSubtree","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent12ClearSubtreeEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["instance","user"]}
{"loc":"00079:23-36","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::RemoveManagee","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent13RemoveManageeEiPNS_3ipc9IProtocolE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::RemoveManagee","sym":"_ZN7mozilla3ipc9IProtocol13RemoveManageeEiPS1_"}],"props":["instance","virtual","user"]}
{"loc":"00087:23-37","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::DeallocManagee","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14DeallocManageeEiPNS_3ipc9IProtocolE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::DeallocManagee","sym":"_ZN7mozilla3ipc9IProtocol14DeallocManageeEiPS1_"}],"props":["instance","virtual","user"]}
{"loc":"00121:23-37","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::OnCallReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::OnCallReceived","sym":"_ZN7mozilla3ipc9IProtocol14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}],"props":["instance","virtual","user"]}
{"loc":"00129:23-37","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::OnChannelClose","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelCloseEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::OnChannelClose","sym":"_ZN7mozilla3ipc17IToplevelProtocol14OnChannelCloseEv"}],"props":["instance","virtual","user"]}
{"loc":"00139:23-37","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::OnChannelError","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent14OnChannelErrorEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::OnChannelError","sym":"_ZN7mozilla3ipc17IToplevelProtocol14OnChannelErrorEv"}],"props":["instance","virtual","user"]}
{"loc":"00025:23-38","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::ProcessingError","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::ProcessingError","sym":"_ZN7mozilla3ipc17IToplevelProtocol15ProcessingErrorENS0_14HasResultCodes6ResultEPKc"}],"props":["instance","virtual","user"]}
{"loc":"00095:23-40","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::OnMessageReceived","sym":"_ZN7mozilla3ipc9IProtocol17OnMessageReceivedERKN3IPC7MessageE"}],"props":["instance","virtual","user"]}
{"loc":"00113:23-40","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::OnMessageReceived","sym":"_ZN7mozilla3ipc9IProtocol17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}],"props":["instance","virtual","user"]}
{"loc":"00031:23-53","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::ShouldContinueFromReplyTimeout","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent30ShouldContinueFromReplyTimeoutEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::ShouldContinueFromReplyTimeout","sym":"_ZN7mozilla3ipc17IToplevelProtocol30ShouldContinueFromReplyTimeoutEv"}],"props":["instance","virtual","user"]}
{"loc":"00054:23-32","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::SendHello","sym":"_ZN7mozilla9_ipdltest16PTestBasicParent9SendHelloEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["instance","user"]}
{"loc":"00036:31-47","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::PTestBasicParent","sym":"_ZN7mozilla9_ipdltest16PTestBasicParentC1Ev","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["instance","user"]}
{"loc":"00042:19-35","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::~PTestBasicParent","sym":"_ZN7mozilla9_ipdltest16PTestBasicParentD1Ev","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::~IToplevelProtocol","sym":"_ZN7mozilla3ipc17IToplevelProtocolD1Ev"}],"props":["instance","virtual","user"]}
{"loc":"00047:23-39","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicParent::AllManagedActors","sym":"_ZNK7mozilla9_ipdltest16PTestBasicParent16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicParent","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::AllManagedActors","sym":"_ZNK7mozilla3ipc9IProtocol16AllManagedActorsER8nsTArrayI6RefPtrINS0_19ActorLifecycleProxyEEE"}],"props":["instance","virtual","user"]}
