{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00011:9-32","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00012:9-47","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_linux64-opt@__GENERATED__/dist/include/nsIFile@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00014:9-33","target":1,"kind":"use","pretty":"ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00015:9-45","target":1,"kind":"use","pretty":"ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00016:9-38","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00017:9-42","target":1,"kind":"use","pretty":"ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00018:9-41","target":1,"kind":"use","pretty":"ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00020:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00021:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00022:10-20","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic","sym":"NS_mozilla::_ipdltest::PTestBasic"}
{"loc":"00024:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00025:0-15","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE","peekRange":"24-29"}
{"loc":"00026:22-38","target":1,"kind":"use","pretty":"mozilla::ipc::EndpointProcInfo","sym":"T_mozilla::ipc::EndpointProcInfo","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00027:22-38","target":1,"kind":"use","pretty":"mozilla::ipc::EndpointProcInfo","sym":"T_mozilla::ipc::EndpointProcInfo","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00028:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00028:53-69","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00029:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00029:53-68","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00031:25-40","target":1,"kind":"use","pretty":"mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceENS0_16EndpointProcInfoES4_PNS0_8EndpointIT_EEPNS5_IT0_EE","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00032:22-42","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00032:8-15","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00033:25-39","target":1,"kind":"use","pretty":"mozilla::ipc::EndpointProcInfo::EndpointProcInfo","sym":"_ZN7mozilla3ipc16EndpointProcInfoC1ERKS1_","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00033:8-23","target":1,"kind":"use","pretty":"mozilla::ipc::EndpointProcInfo::EndpointProcInfo","sym":"_ZN7mozilla3ipc16EndpointProcInfoC1ERKS1_","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00035:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00036:0-15","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","peekRange":"35-38"}
{"loc":"00037:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00037:53-69","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00038:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00038:53-68","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00040:25-40","target":1,"kind":"use","pretty":"mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceEPNS0_8EndpointIT_EEPNS4_IT0_EE","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00041:22-42","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00041:8-15","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00044:24-31","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00044:9-18","target":1,"kind":"use","pretty":"mozilla::UniquePtr","sym":"TA_mozilla::UniquePtr","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00045:0-9","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl","peekRange":"44-45"}
{"loc":"00045:15-22","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00045:24-33","target":1,"kind":"use","pretty":"IPC::Message::routeid_t","sym":"TA_IPC::Message::routeid_t","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:106-116","target":1,"kind":"use","pretty":"IPC::Message::NestedLevel::NOT_NESTED","sym":"E_<T_IPC::Message::NestedLevel>_NOT_NESTED","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:123-130","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:132-147","target":1,"kind":"use","pretty":"IPC::Message::PriorityValue::NORMAL_PRIORITY","sym":"E_<T_IPC::Message::PriorityValue>_NORMAL_PRIORITY","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:154-161","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:16-23","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:163-179","target":1,"kind":"use","pretty":"IPC::Message::MessageCompression::COMPRESSION_NONE","sym":"E_<T_IPC::Message::MessageCompression>_COMPRESSION_NONE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:186-193","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:195-205","target":1,"kind":"use","pretty":"IPC::Message::LazySend::EAGER_SEND","sym":"E_<T_IPC::Message::LazySend>_EAGER_SEND","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:212-219","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:221-236","target":1,"kind":"use","pretty":"IPC::Message::Constructor::NOT_CONSTRUCTOR","sym":"E_<T_IPC::Message::Constructor>_NOT_CONSTRUCTOR","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:243-250","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:25-36","target":1,"kind":"use","pretty":"IPC::Message::IPDLMessage","sym":"_ZN3IPC7Message11IPDLMessageEljjNS0_11HeaderFlagsE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:252-257","target":1,"kind":"use","pretty":"IPC::Message::Sync::ASYNC","sym":"E_<T_IPC::Message::Sync>_ASYNC","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:264-271","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:273-282","target":1,"kind":"use","pretty":"IPC::Message::Reply::NOT_REPLY","sym":"E_<T_IPC::Message::Reply>_NOT_REPLY","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:48-61","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:66-69","target":1,"kind":"use","pretty":"IPC::Message::HeaderFlags::HeaderFlags","sym":"_ZN3IPC7Message11HeaderFlagsC1ENS0_11NestedLevelENS0_13PriorityValueENS0_18MessageCompressionENS0_8LazySendENS0_11ConstructorENS0_4SyncENS0_5ReplyE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:71-78","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:80-91","target":1,"kind":"use","pretty":"IPC::Message::HeaderFlags","sym":"T_IPC::Message::HeaderFlags","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00047:97-104","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00011:9-32","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00012:9-47","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_linux64@__GENERATED__/dist/include/nsIFile@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00014:9-33","target":1,"kind":"use","pretty":"ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00015:9-45","target":1,"kind":"use","pretty":"ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00016:9-38","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00017:9-42","target":1,"kind":"use","pretty":"ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00018:9-41","target":1,"kind":"use","pretty":"ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00011:9-32","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00012:9-47","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_macosx64-aarch64-opt@__GENERATED__/dist/include/nsIFile@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00014:9-33","target":1,"kind":"use","pretty":"ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00015:9-45","target":1,"kind":"use","pretty":"ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00016:9-38","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00017:9-42","target":1,"kind":"use","pretty":"ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00018:9-41","target":1,"kind":"use","pretty":"ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00044:24-31","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00044:9-18","target":1,"kind":"use","pretty":"mozilla::UniquePtr","sym":"TA_mozilla::UniquePtr","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00045:0-9","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx","peekRange":"44-45"}
{"loc":"00045:15-22","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00045:24-33","target":1,"kind":"use","pretty":"IPC::Message::routeid_t","sym":"TA_IPC::Message::routeid_t","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:106-116","target":1,"kind":"use","pretty":"IPC::Message::NestedLevel::NOT_NESTED","sym":"E_<T_IPC::Message::NestedLevel>_NOT_NESTED","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:123-130","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:132-147","target":1,"kind":"use","pretty":"IPC::Message::PriorityValue::NORMAL_PRIORITY","sym":"E_<T_IPC::Message::PriorityValue>_NORMAL_PRIORITY","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:154-161","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:16-23","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:163-179","target":1,"kind":"use","pretty":"IPC::Message::MessageCompression::COMPRESSION_NONE","sym":"E_<T_IPC::Message::MessageCompression>_COMPRESSION_NONE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:186-193","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:195-205","target":1,"kind":"use","pretty":"IPC::Message::LazySend::EAGER_SEND","sym":"E_<T_IPC::Message::LazySend>_EAGER_SEND","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:212-219","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:221-236","target":1,"kind":"use","pretty":"IPC::Message::Constructor::NOT_CONSTRUCTOR","sym":"E_<T_IPC::Message::Constructor>_NOT_CONSTRUCTOR","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:243-250","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:25-36","target":1,"kind":"use","pretty":"IPC::Message::IPDLMessage","sym":"_ZN3IPC7Message11IPDLMessageExjjNS0_11HeaderFlagsE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:252-257","target":1,"kind":"use","pretty":"IPC::Message::Sync::ASYNC","sym":"E_<T_IPC::Message::Sync>_ASYNC","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:264-271","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:273-282","target":1,"kind":"use","pretty":"IPC::Message::Reply::NOT_REPLY","sym":"E_<T_IPC::Message::Reply>_NOT_REPLY","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:48-61","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:66-69","target":1,"kind":"use","pretty":"IPC::Message::HeaderFlags::HeaderFlags","sym":"_ZN3IPC7Message11HeaderFlagsC1ENS0_11NestedLevelENS0_13PriorityValueENS0_18MessageCompressionENS0_8LazySendENS0_11ConstructorENS0_4SyncENS0_5ReplyE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:71-78","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:80-91","target":1,"kind":"use","pretty":"IPC::Message::HeaderFlags","sym":"T_IPC::Message::HeaderFlags","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00047:97-104","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00011:9-32","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00012:9-47","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_macosx64-aarch64@__GENERATED__/dist/include/nsIFile@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00014:9-33","target":1,"kind":"use","pretty":"ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00015:9-45","target":1,"kind":"use","pretty":"ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00016:9-38","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00017:9-42","target":1,"kind":"use","pretty":"ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00018:9-41","target":1,"kind":"use","pretty":"ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00011:9-32","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00012:9-47","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_macosx64@__GENERATED__/dist/include/nsIFile@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00014:9-33","target":1,"kind":"use","pretty":"ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00015:9-45","target":1,"kind":"use","pretty":"ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00016:9-38","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00017:9-42","target":1,"kind":"use","pretty":"ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00018:9-41","target":1,"kind":"use","pretty":"ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00011:9-32","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/ipc/IPCMessageUtils.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/ipc/IPCMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00012:9-47","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/ipc/IPCMessageUtilsSpecializations.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/ipc/IPCMessageUtilsSpecializations@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/nsIFile@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00014:9-33","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/Endpoint.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/Endpoint@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00015:9-45","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/ProtocolMessageUtils.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/ProtocolMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00016:9-38","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/ProtocolUtils.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/ProtocolUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00017:9-42","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/ShmemMessageUtils.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/ShmemMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00018:9-41","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/TaintingIPCUtils.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/TaintingIPCUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00011:9-32","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/ipc/IPCMessageUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/ipc/IPCMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00012:9-47","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/ipc/IPCMessageUtilsSpecializations.h","sym":"FILE_win64@__GENERATED__/dist/include/ipc/IPCMessageUtilsSpecializations@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_win64@__GENERATED__/dist/include/nsIFile@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00014:9-33","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/Endpoint.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/Endpoint@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00015:9-45","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/ProtocolMessageUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/ProtocolMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00016:9-38","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/ProtocolUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/ProtocolUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00017:9-42","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/ShmemMessageUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/ShmemMessageUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00018:9-41","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/TaintingIPCUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/TaintingIPCUtils@2Eh","context":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00001:0","source":1,"syntax":"def,file","pretty":"file __GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_win64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_win64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_macosx64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_linux64@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_linux64-opt@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00008:9-47","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00009:9-46","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00011:9-32","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/ipc/IPCMessageUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/ipc/IPCMessageUtils@2Eh,FILE_win64-opt@__GENERATED__/dist/include/ipc/IPCMessageUtils@2Eh"}
{"loc":"00011:9-32","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh"}
{"loc":"00012:9-47","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/ipc/IPCMessageUtilsSpecializations.h","sym":"FILE_win64@__GENERATED__/dist/include/ipc/IPCMessageUtilsSpecializations@2Eh,FILE_win64-opt@__GENERATED__/dist/include/ipc/IPCMessageUtilsSpecializations@2Eh"}
{"loc":"00012:9-47","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh"}
{"loc":"00013:9-20","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/nsIFile.h","sym":"FILE_win64@__GENERATED__/dist/include/nsIFile@2Eh,FILE_win64-opt@__GENERATED__/dist/include/nsIFile@2Eh,FILE_macosx64@__GENERATED__/dist/include/nsIFile@2Eh,FILE_macosx64-aarch64@__GENERATED__/dist/include/nsIFile@2Eh,FILE_macosx64-aarch64-opt@__GENERATED__/dist/include/nsIFile@2Eh,FILE_linux64@__GENERATED__/dist/include/nsIFile@2Eh,FILE_linux64-opt@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00014:9-33","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/Endpoint.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/Endpoint@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/Endpoint@2Eh"}
{"loc":"00014:9-33","source":1,"syntax":"file,use","pretty":"file ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh"}
{"loc":"00015:9-45","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/ProtocolMessageUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/ProtocolMessageUtils@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/ProtocolMessageUtils@2Eh"}
{"loc":"00015:9-45","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh"}
{"loc":"00016:9-38","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/ProtocolUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/ProtocolUtils@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/ProtocolUtils@2Eh"}
{"loc":"00016:9-38","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh"}
{"loc":"00017:9-42","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/ShmemMessageUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/ShmemMessageUtils@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/ShmemMessageUtils@2Eh"}
{"loc":"00017:9-42","source":1,"syntax":"file,use","pretty":"file ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh"}
{"loc":"00018:9-41","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/TaintingIPCUtils.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/TaintingIPCUtils@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/TaintingIPCUtils@2Eh"}
{"loc":"00018:9-41","source":1,"syntax":"file,use","pretty":"file ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh"}
{"loc":"00020:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"20:19-52:0"}
{"loc":"00021:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"21:21-51:0"}
{"loc":"00022:10-20","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest::PTestBasic","sym":"NS_mozilla::_ipdltest::PTestBasic","nestingRange":"22:22-50:0"}
{"loc":"00024:0-8","source":1,"syntax":"type,use","pretty":"type nsresult","sym":"T_nsresult","type":"enum nsresult","typesym":"T_nsresult"}
{"loc":"00025:0-15","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE","nestingRange":"30:0-34:0","type":"nsresult (mozilla::ipc::EndpointProcInfo, mozilla::ipc::EndpointProcInfo, mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *, mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00026:22-38","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::EndpointProcInfo","sym":"T_mozilla::ipc::EndpointProcInfo","type":"struct mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00026:39-54","source":1,"syntax":"","pretty":"variable aParentDestInfo","sym":"V_b79ac543b3c7e804_c05dff1385dd6cb8,V_b106f9aba92130da_c05dff1385dd6cb8,V_83b4cc07c2e2e2de_c05dff1385dd6cb8,V_ea4aea318ebd6f55_c05dff1385dd6cb8,V_eccb11c9a613bb9f_c05dff1385dd6cb8,V_d7068c54b0e9596f_c05dff1385dd6cb8,V_d18c23978a7d7627_c05dff1385dd6cb8","no_crossref":1,"type":"mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00027:22-38","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::EndpointProcInfo","sym":"T_mozilla::ipc::EndpointProcInfo","type":"struct mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00027:39-53","source":1,"syntax":"","pretty":"variable aChildDestInfo","sym":"V_cd53d543b3c7e804_6c9b56545850b521,V_c7cef9aba92130da_6c9b56545850b521,V_997dcc07c2e2e2de_6c9b56545850b521,V_f013fa318ebd6f55_6c9b56545850b521,V_f29421c9a613bb9f_6c9b56545850b521,V_edce8c54b0e9596f_6c9b56545850b521,V_e74533978a7d7627_6c9b56545850b521","no_crossref":1,"type":"mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00028:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00028:53-69","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00028:72-79","source":1,"syntax":"","pretty":"variable aParent","sym":"V_ab2cd543b3c7e804_03dd840f0b0d,V_a5970aaba92130da_03dd840f0b0d,V_7746dc07c2e2e2de_03dd840f0b0d,V_dedbfa318ebd6f55_03dd840f0b0d,V_d06d21c9a613bb9f_03dd840f0b0d,V_cb979c54b0e9596f_03dd840f0b0d,V_c51e33978a7d7627_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00029:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00029:53-68","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00029:71-77","source":1,"syntax":"","pretty":"variable aChild","sym":"V_a1f4e543b3c7e804_ae7aa1fe256,V_ab501aaba92130da_ae7aa1fe256,V_7d0fdc07c2e2e2de_ae7aa1fe256,V_d4a40b318ebd6f55_ae7aa1fe256,V_d62631c9a613bb9f_ae7aa1fe256,V_c160ac54b0e9596f_ae7aa1fe256,V_cbd643978a7d7627_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00031:25-40","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceENS0_16EndpointProcInfoES4_PNS0_8EndpointIT_EEPNS5_IT0_EE","type":"nsresult (const PrivateIPDLInterface &, EndpointProcInfo, EndpointProcInfo, Endpoint<mozilla::_ipdltest::PTestBasicParent> *, Endpoint<mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00032:8-15","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev"}
{"loc":"00032:22-42","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","type":"struct mozilla::ipc::PrivateIPDLInterface","typesym":"T_mozilla::ipc::PrivateIPDLInterface"}
{"loc":"00033:8-23","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::ipc::EndpointProcInfo::EndpointProcInfo","sym":"_ZN7mozilla3ipc16EndpointProcInfoC1ERKS1_"}
{"loc":"00033:8-23","source":1,"syntax":"","pretty":"variable aParentDestInfo","sym":"V_b79ac543b3c7e804_c05dff1385dd6cb8,V_b106f9aba92130da_c05dff1385dd6cb8,V_83b4cc07c2e2e2de_c05dff1385dd6cb8,V_ea4aea318ebd6f55_c05dff1385dd6cb8,V_eccb11c9a613bb9f_c05dff1385dd6cb8,V_d7068c54b0e9596f_c05dff1385dd6cb8,V_d18c23978a7d7627_c05dff1385dd6cb8","no_crossref":1,"type":"mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00033:25-39","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::ipc::EndpointProcInfo::EndpointProcInfo","sym":"_ZN7mozilla3ipc16EndpointProcInfoC1ERKS1_"}
{"loc":"00033:25-39","source":1,"syntax":"","pretty":"variable aChildDestInfo","sym":"V_cd53d543b3c7e804_6c9b56545850b521,V_c7cef9aba92130da_6c9b56545850b521,V_997dcc07c2e2e2de_6c9b56545850b521,V_f013fa318ebd6f55_6c9b56545850b521,V_f29421c9a613bb9f_6c9b56545850b521,V_edce8c54b0e9596f_6c9b56545850b521,V_e74533978a7d7627_6c9b56545850b521","no_crossref":1,"type":"mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00033:41-48","source":1,"syntax":"","pretty":"variable aParent","sym":"V_ab2cd543b3c7e804_03dd840f0b0d,V_a5970aaba92130da_03dd840f0b0d,V_7746dc07c2e2e2de_03dd840f0b0d,V_dedbfa318ebd6f55_03dd840f0b0d,V_d06d21c9a613bb9f_03dd840f0b0d,V_cb979c54b0e9596f_03dd840f0b0d,V_c51e33978a7d7627_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00033:50-56","source":1,"syntax":"","pretty":"variable aChild","sym":"V_a1f4e543b3c7e804_ae7aa1fe256,V_ab501aaba92130da_ae7aa1fe256,V_7d0fdc07c2e2e2de_ae7aa1fe256,V_d4a40b318ebd6f55_ae7aa1fe256,V_d62631c9a613bb9f_ae7aa1fe256,V_c160ac54b0e9596f_ae7aa1fe256,V_cbd643978a7d7627_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00035:0-8","source":1,"syntax":"type,use","pretty":"type nsresult","sym":"T_nsresult","type":"enum nsresult","typesym":"T_nsresult"}
{"loc":"00036:0-15","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","nestingRange":"39:0-43:0","type":"nsresult (mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *, mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00037:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00037:53-69","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00037:72-79","source":1,"syntax":"","pretty":"variable aParent","sym":"V_ade4f643b3c7e804_03dd840f0b0d,V_a7502baba92130da_03dd840f0b0d,V_790fed07c2e2e2de_03dd840f0b0d,V_d0a41c318ebd6f55_03dd840f0b0d,V_d22642c9a613bb9f_03dd840f0b0d,V_cd50bd54b0e9596f_03dd840f0b0d,V_c7d654978a7d7627_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00038:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00038:53-68","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00038:71-77","source":1,"syntax":"","pretty":"variable aChild","sym":"V_a3bdf643b3c7e804_ae7aa1fe256,V_ad192baba92130da_ae7aa1fe256,V_7fc7fd07c2e2e2de_ae7aa1fe256,V_d66d1c318ebd6f55_ae7aa1fe256,V_d8ee42c9a613bb9f_ae7aa1fe256,V_c329bd54b0e9596f_ae7aa1fe256,V_cd9f54978a7d7627_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00040:25-40","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceEPNS0_8EndpointIT_EEPNS4_IT0_EE","type":"nsresult (const PrivateIPDLInterface &, Endpoint<mozilla::_ipdltest::PTestBasicParent> *, Endpoint<mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00041:8-15","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev"}
{"loc":"00041:22-42","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","type":"struct mozilla::ipc::PrivateIPDLInterface","typesym":"T_mozilla::ipc::PrivateIPDLInterface"}
{"loc":"00042:8-15","source":1,"syntax":"","pretty":"variable aParent","sym":"V_ade4f643b3c7e804_03dd840f0b0d,V_a7502baba92130da_03dd840f0b0d,V_790fed07c2e2e2de_03dd840f0b0d,V_d0a41c318ebd6f55_03dd840f0b0d,V_d22642c9a613bb9f_03dd840f0b0d,V_cd50bd54b0e9596f_03dd840f0b0d,V_c7d654978a7d7627_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00042:17-23","source":1,"syntax":"","pretty":"variable aChild","sym":"V_a3bdf643b3c7e804_ae7aa1fe256,V_ad192baba92130da_ae7aa1fe256,V_7fc7fd07c2e2e2de_ae7aa1fe256,V_d66d1c318ebd6f55_ae7aa1fe256,V_d8ee42c9a613bb9f_ae7aa1fe256,V_c329bd54b0e9596f_ae7aa1fe256,V_cd9f54978a7d7627_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00044:9-18","source":1,"syntax":"type,use","pretty":"type mozilla::UniquePtr","sym":"TA_mozilla::UniquePtr"}
{"loc":"00044:24-31","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00045:0-9","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx,_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl","nestingRange":"46:0-48:0","type":"mozilla::UniquePtr<IPC::Message> (IPC::Message::routeid_t)"}
{"loc":"00045:15-22","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00045:24-33","source":1,"syntax":"type,use","pretty":"type IPC::Message::routeid_t","sym":"TA_IPC::Message::routeid_t","type":"IPC::Message::routeid_t"}
{"loc":"00045:34-43","source":1,"syntax":"","pretty":"variable routingId","sym":"V_71e40843b3c7e804_a5670b686a7d773,V_7b403caba92130da_a5670b686a7d773,V_4dfefe07c2e2e2de_a5670b686a7d773,V_a4942d318ebd6f55_a5670b686a7d773,V_a61653c9a613bb9f_a5670b686a7d773,V_9150ce54b0e9596f_a5670b686a7d773,V_9bc665978a7d7627_a5670b686a7d773","no_crossref":1,"type":"IPC::Message::routeid_t"}
{"loc":"00047:16-23","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:25-36","source":1,"syntax":"function,use","pretty":"function IPC::Message::IPDLMessage","sym":"_ZN3IPC7Message11IPDLMessageExjjNS0_11HeaderFlagsE,_ZN3IPC7Message11IPDLMessageEljjNS0_11HeaderFlagsE","type":"mozilla::UniquePtr<Message> (routeid_t, msgid_t, uint32_t, HeaderFlags)"}
{"loc":"00047:37-46","source":1,"syntax":"","pretty":"variable routingId","sym":"V_71e40843b3c7e804_a5670b686a7d773,V_7b403caba92130da_a5670b686a7d773,V_4dfefe07c2e2e2de_a5670b686a7d773,V_a4942d318ebd6f55_a5670b686a7d773,V_a61653c9a613bb9f_a5670b686a7d773,V_9150ce54b0e9596f_a5670b686a7d773,V_9bc665978a7d7627_a5670b686a7d773","no_crossref":1,"type":"IPC::Message::routeid_t"}
{"loc":"00047:48-61","source":1,"syntax":"enum,use","pretty":"enum mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00047:66-69","source":1,"syntax":"constructor,use","pretty":"constructor IPC::Message::HeaderFlags::HeaderFlags","sym":"_ZN3IPC7Message11HeaderFlagsC1ENS0_11NestedLevelENS0_13PriorityValueENS0_18MessageCompressionENS0_8LazySendENS0_11ConstructorENS0_4SyncENS0_5ReplyE"}
{"loc":"00047:71-78","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:80-91","source":1,"syntax":"type,use","pretty":"type IPC::Message::HeaderFlags","sym":"T_IPC::Message::HeaderFlags","type":"class IPC::Message::HeaderFlags","typesym":"T_IPC::Message::HeaderFlags"}
{"loc":"00047:97-104","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:106-116","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::NestedLevel::NOT_NESTED","sym":"E_<T_IPC::Message::NestedLevel>_NOT_NESTED","type":"enum IPC::Message::NestedLevel","typesym":"T_IPC::Message::NestedLevel"}
{"loc":"00047:123-130","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:132-147","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::PriorityValue::NORMAL_PRIORITY","sym":"E_<T_IPC::Message::PriorityValue>_NORMAL_PRIORITY","type":"enum IPC::Message::PriorityValue","typesym":"T_IPC::Message::PriorityValue"}
{"loc":"00047:154-161","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:163-179","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::MessageCompression::COMPRESSION_NONE","sym":"E_<T_IPC::Message::MessageCompression>_COMPRESSION_NONE","type":"enum IPC::Message::MessageCompression","typesym":"T_IPC::Message::MessageCompression"}
{"loc":"00047:186-193","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:195-205","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::LazySend::EAGER_SEND","sym":"E_<T_IPC::Message::LazySend>_EAGER_SEND","type":"enum IPC::Message::LazySend","typesym":"T_IPC::Message::LazySend"}
{"loc":"00047:212-219","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:221-236","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::Constructor::NOT_CONSTRUCTOR","sym":"E_<T_IPC::Message::Constructor>_NOT_CONSTRUCTOR","type":"enum IPC::Message::Constructor","typesym":"T_IPC::Message::Constructor"}
{"loc":"00047:243-250","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:252-257","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::Sync::ASYNC","sym":"E_<T_IPC::Message::Sync>_ASYNC","type":"enum IPC::Message::Sync","typesym":"T_IPC::Message::Sync"}
{"loc":"00047:264-271","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:273-282","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::Reply::NOT_REPLY","sym":"E_<T_IPC::Message::Reply>_NOT_REPLY","type":"enum IPC::Message::Reply","typesym":"T_IPC::Message::Reply"}
{"loc":"00045:34-43","structured":1,"pretty":"routingId","sym":"V_4dfefe07c2e2e2de_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:34-43","structured":1,"pretty":"routingId","sym":"V_71e40843b3c7e804_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00028:72-79","structured":1,"pretty":"aParent","sym":"V_7746dc07c2e2e2de_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00037:72-79","structured":1,"pretty":"aParent","sym":"V_790fed07c2e2e2de_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:34-43","structured":1,"pretty":"routingId","sym":"V_7b403caba92130da_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00029:71-77","structured":1,"pretty":"aChild","sym":"V_7d0fdc07c2e2e2de_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00038:71-77","structured":1,"pretty":"aChild","sym":"V_7fc7fd07c2e2e2de_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00026:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_83b4cc07c2e2e2de_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:34-43","structured":1,"pretty":"routingId","sym":"V_9150ce54b0e9596f_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00027:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_997dcc07c2e2e2de_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:34-43","structured":1,"pretty":"routingId","sym":"V_9bc665978a7d7627_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00029:71-77","structured":1,"pretty":"aChild","sym":"V_a1f4e543b3c7e804_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00038:71-77","structured":1,"pretty":"aChild","sym":"V_a3bdf643b3c7e804_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:34-43","structured":1,"pretty":"routingId","sym":"V_a4942d318ebd6f55_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00028:72-79","structured":1,"pretty":"aParent","sym":"V_a5970aaba92130da_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:34-43","structured":1,"pretty":"routingId","sym":"V_a61653c9a613bb9f_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00037:72-79","structured":1,"pretty":"aParent","sym":"V_a7502baba92130da_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00028:72-79","structured":1,"pretty":"aParent","sym":"V_ab2cd543b3c7e804_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00029:71-77","structured":1,"pretty":"aChild","sym":"V_ab501aaba92130da_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00038:71-77","structured":1,"pretty":"aChild","sym":"V_ad192baba92130da_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00037:72-79","structured":1,"pretty":"aParent","sym":"V_ade4f643b3c7e804_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00026:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_b106f9aba92130da_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00026:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_b79ac543b3c7e804_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00029:71-77","structured":1,"pretty":"aChild","sym":"V_c160ac54b0e9596f_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00038:71-77","structured":1,"pretty":"aChild","sym":"V_c329bd54b0e9596f_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00028:72-79","structured":1,"pretty":"aParent","sym":"V_c51e33978a7d7627_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00027:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_c7cef9aba92130da_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00037:72-79","structured":1,"pretty":"aParent","sym":"V_c7d654978a7d7627_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00028:72-79","structured":1,"pretty":"aParent","sym":"V_cb979c54b0e9596f_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00029:71-77","structured":1,"pretty":"aChild","sym":"V_cbd643978a7d7627_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00037:72-79","structured":1,"pretty":"aParent","sym":"V_cd50bd54b0e9596f_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00027:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_cd53d543b3c7e804_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00038:71-77","structured":1,"pretty":"aChild","sym":"V_cd9f54978a7d7627_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00028:72-79","structured":1,"pretty":"aParent","sym":"V_d06d21c9a613bb9f_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00037:72-79","structured":1,"pretty":"aParent","sym":"V_d0a41c318ebd6f55_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00026:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_d18c23978a7d7627_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00037:72-79","structured":1,"pretty":"aParent","sym":"V_d22642c9a613bb9f_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00029:71-77","structured":1,"pretty":"aChild","sym":"V_d4a40b318ebd6f55_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00029:71-77","structured":1,"pretty":"aChild","sym":"V_d62631c9a613bb9f_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00038:71-77","structured":1,"pretty":"aChild","sym":"V_d66d1c318ebd6f55_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00026:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_d7068c54b0e9596f_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00038:71-77","structured":1,"pretty":"aChild","sym":"V_d8ee42c9a613bb9f_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00028:72-79","structured":1,"pretty":"aParent","sym":"V_dedbfa318ebd6f55_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00027:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_e74533978a7d7627_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00026:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_ea4aea318ebd6f55_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00026:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_eccb11c9a613bb9f_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00027:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_edce8c54b0e9596f_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00027:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_f013fa318ebd6f55_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00027:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_f29421c9a613bb9f_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc": "00025:0-15", "structured": 1, "pretty": "mozilla::_ipdltest::PTestBasic::CreateEndpoints", "sym": "_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE", "type_pretty": null, "kind": "function", "subsystem": null, "implKind": "", "sizeBytes": null, "alignmentBytes": null, "ownVFPtrBytes": null, "bindingSlots": [], "ontologySlots": [], "supers": [], "methods": [], "fields": [], "overrides": [], "props": [], "variants": [], "args": [{"name": "aParentDestInfo", "type": "mozilla::ipc::EndpointProcInfo", "typesym": "T_mozilla::ipc::EndpointProcInfo"}, {"name": "aChildDestInfo", "type": "mozilla::ipc::EndpointProcInfo", "typesym": "T_mozilla::ipc::EndpointProcInfo"}, {"name": "aParent", "type": "mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *", "typesym": "T_mozilla::ipc::Endpoint"}, {"name": "aChild", "type": "mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *", "typesym": "T_mozilla::ipc::Endpoint"}], "canGC": true, "gcPath": "uint32 mozilla::ipc::CreateEndpoints(mozilla::ipc::PrivateIPDLInterface&, mozilla::ipc::EndpointProcInfo, mozilla::ipc::EndpointProcInfo, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent>*, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild>*) [with PFooParent = mozilla::_ipdltest::PTestBasicParent; PFooChild = mozilla::_ipdltest::PTestBasicChild]\nnsID nsID::GenerateUUID()\nuint32 nsID::GenerateUUIDInPlace(nsID&)\nnsID.cpp:uint8 GenerateRandomBytesFromNSS(void*, size_t)\nPK11_GenerateRandomOnSlot\nCK_FUNCTION_LIST_3_2.C_GenerateRandom\narbitrary function pointer CK_FUNCTION_LIST_3_2.C_GenerateRandom"}
{"loc": "00036:0-15", "structured": 1, "pretty": "mozilla::_ipdltest::PTestBasic::CreateEndpoints", "sym": "_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE", "type_pretty": null, "kind": "function", "subsystem": null, "implKind": "", "sizeBytes": null, "alignmentBytes": null, "ownVFPtrBytes": null, "bindingSlots": [], "ontologySlots": [], "supers": [], "methods": [], "fields": [], "overrides": [], "props": [], "variants": [], "args": [{"name": "aParent", "type": "mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *", "typesym": "T_mozilla::ipc::Endpoint"}, {"name": "aChild", "type": "mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *", "typesym": "T_mozilla::ipc::Endpoint"}], "canGC": true, "gcPath": "uint32 mozilla::ipc::CreateEndpoints(mozilla::ipc::PrivateIPDLInterface&, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent>*, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild>*) [with PFooParent = mozilla::_ipdltest::PTestBasicParent; PFooChild = mozilla::_ipdltest::PTestBasicChild]\nnsID nsID::GenerateUUID()\nuint32 nsID::GenerateUUIDInPlace(nsID&)\nnsID.cpp:uint8 GenerateRandomBytesFromNSS(void*, size_t)\nPK11_GenerateRandomOnSlot\nCK_FUNCTION_LIST_3_2.C_GenerateRandom\narbitrary function pointer CK_FUNCTION_LIST_3_2.C_GenerateRandom"}
{"loc": "00045:0-9", "structured": 1, "pretty": "mozilla::_ipdltest::PTestBasic::Msg_Hello", "sym": "_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl", "type_pretty": null, "kind": "function", "subsystem": null, "implKind": "", "sizeBytes": null, "alignmentBytes": null, "ownVFPtrBytes": null, "bindingSlots": [], "ontologySlots": [], "supers": [], "methods": [], "fields": [], "overrides": [], "props": [], "variants": [], "args": [{"name": "routingId", "type": "IPC::Message::routeid_t"}], "canGC": false}
{"loc":"00045:0-9","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx","type_pretty":null,"kind":"function","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[],"args":[{"name":"routingId","type":"IPC::Message::routeid_t"}]}
