{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasicChild.cpp","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/PTestBasicChild@2Ecpp"}
{"loc":"00007:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00008:9-35","target":1,"kind":"use","pretty":"tools/profiler/public/ProfilerLabels.h","sym":"FILE_tools/profiler/public/ProfilerLabels@2Eh"}
{"loc":"00009:9-45","target":1,"kind":"use","pretty":"ipc/ipdl/test/gtest/TestBasicChild.h","sym":"FILE_ipc/ipdl/test/gtest/TestBasicChild@2Eh"}
{"loc":"00012:9-32","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh"}
{"loc":"00013:9-47","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh"}
{"loc":"00014:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_android-armv7@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00015:9-33","target":1,"kind":"use","pretty":"ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh"}
{"loc":"00016:9-45","target":1,"kind":"use","pretty":"ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh"}
{"loc":"00017:9-38","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh"}
{"loc":"00018:9-42","target":1,"kind":"use","pretty":"ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh"}
{"loc":"00019:9-41","target":1,"kind":"use","pretty":"ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh"}
{"loc":"00021:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00022:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00025:22-37","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::ProcessingError","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc","peekRange":"25-27"}
{"loc":"00025:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::ProcessingError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc"}
{"loc":"00026:8-14","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","context":"mozilla::_ipdltest::PTestBasicChild::ProcessingError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc"}
{"loc":"00031:22-52","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::ShouldContinueFromReplyTimeout","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild30ShouldContinueFromReplyTimeoutEv","peekRange":"31-31"}
{"loc":"00031:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::ShouldContinueFromReplyTimeout","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild30ShouldContinueFromReplyTimeoutEv"}
{"loc":"00036:0-12","target":1,"kind":"use","pretty":"MOZ_IMPLICIT","sym":"M_5f65895d5a5258f7"}
{"loc":"00036:13-28","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev"}
{"loc":"00036:30-45","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","sym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev"}
{"loc":"00037:18-35","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol","sym":"T_mozilla::ipc::IToplevelProtocol","context":"mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev"}
{"loc":"00037:4-11","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::IToplevelProtocol","sym":"_ZN7mozilla3ipc17IToplevelProtocolC1EPKc15IPCMessageStartNS0_4SideE","context":"mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev"}
{"loc":"00037:55-73","target":1,"kind":"use","pretty":"IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","context":"mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev"}
{"loc":"00037:89-98","target":1,"kind":"use","pretty":"mozilla::ipc::Side::ChildSide","sym":"E_<T_mozilla::ipc::Side>_ChildSide","context":"mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev"}
{"loc":"00039:19-34","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev"}
{"loc":"00039:4-18","target":1,"kind":"use","pretty":"MOZ_COUNT_CTOR","sym":"M_d9d58f5149d9f0f2"}
{"loc":"00042:0-15","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::~PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildD1Ev"}
{"loc":"00042:18-33","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::~PTestBasicChild","sym":"_ZN7mozilla9_ipdltest15PTestBasicChildD1Ev","peekRange":"42-42"}
{"loc":"00042:18-33","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::~PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildD1Ev"}
{"loc":"00044:19-34","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::~PTestBasicChild","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChildD1Ev"}
{"loc":"00044:4-18","target":1,"kind":"use","pretty":"MOZ_COUNT_DTOR","sym":"M_f9e8c16149d9f0f2"}
{"loc":"00047:22-38","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::AllManagedActors","sym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE","peekRange":"47-47"}
{"loc":"00047:39-47","target":1,"kind":"use","pretty":"nsTArray","sym":"T_nsTArray","context":"mozilla::_ipdltest::PTestBasicChild::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00047:48-54","target":1,"kind":"use","pretty":"RefPtr","sym":"T_RefPtr","context":"mozilla::_ipdltest::PTestBasicChild::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00047:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00047:69-88","target":1,"kind":"use","pretty":"mozilla::ipc::ActorLifecycleProxy","sym":"T_mozilla::ipc::ActorLifecycleProxy","context":"mozilla::_ipdltest::PTestBasicChild::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00049:4-12","target":1,"kind":"use","pretty":"uint32_t","sym":"T_uint32_t","context":"mozilla::_ipdltest::PTestBasicChild::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00050:10-21","target":1,"kind":"use","pretty":"nsTArray_Impl::SetCapacity","sym":"_ZN13nsTArray_Impl11SetCapacityEN13nsTArray_baseIT0_N27nsTArray_RelocationStrategyIT_E4TypeEE9size_typeE","context":"mozilla::_ipdltest::PTestBasicChild::AllManagedActors","contextsym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE"}
{"loc":"00054:22-35","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::RemoveManagee","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild13RemoveManageeEiPNS_3ipc9IProtocolE","peekRange":"54-56"}
{"loc":"00054:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::RemoveManagee","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild13RemoveManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00055:8-15","target":1,"kind":"use","pretty":"int32_t","sym":"T_int32_t","context":"mozilla::_ipdltest::PTestBasicChild::RemoveManagee","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild13RemoveManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00056:8-17","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::IProtocol","sym":"T_mozilla::_ipdltest::PTestBasicChild::IProtocol","context":"mozilla::_ipdltest::PTestBasicChild::RemoveManagee","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild13RemoveManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00058:4-14","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"mozilla::_ipdltest::PTestBasicChild::RemoveManagee","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild13RemoveManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00062:22-36","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::DeallocManagee","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14DeallocManageeEiPNS_3ipc9IProtocolE","peekRange":"62-64"}
{"loc":"00062:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::DeallocManagee","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14DeallocManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00063:8-15","target":1,"kind":"use","pretty":"int32_t","sym":"T_int32_t","context":"mozilla::_ipdltest::PTestBasicChild::DeallocManagee","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14DeallocManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00064:8-17","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::IProtocol","sym":"T_mozilla::_ipdltest::PTestBasicChild::IProtocol","context":"mozilla::_ipdltest::PTestBasicChild::DeallocManagee","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14DeallocManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00066:4-14","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"mozilla::_ipdltest::PTestBasicChild::DeallocManagee","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14DeallocManageeEiPNS_3ipc9IProtocolE"}
{"loc":"00070:22-39","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE","peekRange":"70-70"}
{"loc":"00070:46-53","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00070:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00070:65-80","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00070:82-88","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00072:18-22","target":1,"kind":"use","pretty":"IPC::Message::type","sym":"_ZNK3IPC7Message4typeEv","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00073:21-34","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00075:30-47","target":1,"kind":"use","pretty":"mozilla::ipc::LoggingEnabledFor","sym":"_ZN7mozilla3ipc17LoggingEnabledForEPKc","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00076:30-51","target":1,"kind":"use","pretty":"mozilla::ipc::LogMessageForProtocol","sym":"_ZN7mozilla3ipc21LogMessageForProtocolEPKciS2_jNS0_16MessageDirectionE","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00078:26-42","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ToplevelProtocol","sym":"_ZN7mozilla3ipc9IProtocol16ToplevelProtocolEv","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00078:46-66","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::OtherPidMaybeInvalid","sym":"_ZNK7mozilla3ipc17IToplevelProtocol20OtherPidMaybeInvalidEv","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00080:32-36","target":1,"kind":"use","pretty":"IPC::Message::type","sym":"_ZNK3IPC7Message4typeEv","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00081:34-50","target":1,"kind":"use","pretty":"mozilla::ipc::MessageDirection","sym":"T_mozilla::ipc::MessageDirection","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00081:52-62","target":1,"kind":"use","pretty":"mozilla::ipc::MessageDirection::eReceiving","sym":"E_<T_mozilla::ipc::MessageDirection>_eReceiving","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00083:12-31","target":1,"kind":"use","pretty":"AUTO_PROFILER_LABEL","sym":"M_99e0335dc782f2d6"}
{"loc":"00083:57-62","target":1,"kind":"use","pretty":"JS::ProfilingCategoryPair::OTHER","sym":"E_<T_JS::ProfilingCategoryPair>_OTHER","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00085:26-35","target":1,"kind":"use","pretty":"mozilla::ipc::IPCResult","sym":"T_mozilla::ipc::IPCResult","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00085:56-70","target":1,"kind":"use","pretty":"mozilla::_ipdltest::TestBasicChild","sym":"T_mozilla::_ipdltest::TestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00085:81-90","target":1,"kind":"use","pretty":"mozilla::_ipdltest::TestBasicChild::RecvHello","sym":"_ZN7mozilla9_ipdltest14TestBasicChild9RecvHelloEv","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00087:30-53","target":1,"kind":"use","pretty":"mozilla::ipc::ProtocolErrorBreakpoint","sym":"_ZN7mozilla3ipc23ProtocolErrorBreakpointEPKc","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00089:23-41","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgProcessingError","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgProcessingError","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00092:19-31","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgProcessed","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgProcessed","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00095:15-26","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00096:9-35","target":1,"kind":"use","pretty":"SHMEM_CREATED_MESSAGE_TYPE","sym":"E_<T_b078e220e89184de>_SHMEM_CREATED_MESSAGE_TYPE","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00098:12-22","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00099:19-30","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00101:9-37","target":1,"kind":"use","pretty":"SHMEM_DESTROYED_MESSAGE_TYPE","sym":"E_<T_b078e220e89184de>_SHMEM_DESTROYED_MESSAGE_TYPE","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00103:12-22","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00104:19-30","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00109:22-39","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","peekRange":"109-111"}
{"loc":"00109:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00110:14-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00111:18-25","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00111:40-55","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00111:57-63","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00111:8-17","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicChild::UniquePtr","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00113:4-26","target":1,"kind":"use","pretty":"MOZ_ASSERT_UNREACHABLE","sym":"M_0d9562839add515c"}
{"loc":"00114:11-22","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00117:22-36","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","peekRange":"117-119"}
{"loc":"00117:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00118:14-21","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","context":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00119:18-25","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","context":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00119:40-55","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00119:57-63","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","context":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00119:8-17","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicChild::UniquePtr","context":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00121:4-26","target":1,"kind":"use","pretty":"MOZ_ASSERT_UNREACHABLE","sym":"M_0d9562839add515c"}
{"loc":"00122:11-22","target":1,"kind":"use","pretty":"mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","context":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}
{"loc":"00125:22-36","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv","peekRange":"125-125"}
{"loc":"00125:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv"}
{"loc":"00127:19-33","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ActorDestroyReason::NormalShutdown","sym":"E_<T_mozilla::ipc::IProtocol::ActorDestroyReason>_NormalShutdown","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv"}
{"loc":"00127:4-18","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::DestroySubtree","sym":"_ZN7mozilla3ipc9IProtocol14DestroySubtreeENS1_18ActorDestroyReasonE","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv"}
{"loc":"00128:4-16","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::ClearSubtree","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild12ClearSubtreeEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv"}
{"loc":"00129:4-17","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::DeallocShmems","sym":"_ZN7mozilla3ipc17IToplevelProtocol13DeallocShmemsEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv"}
{"loc":"00130:8-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv"}
{"loc":"00131:29-36","target":1,"kind":"use","pretty":"mozilla::ipc::ActorLifecycleProxy::Release","sym":"_ZN7mozilla3ipc19ActorLifecycleProxy7ReleaseEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv"}
{"loc":"00131:8-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv"}
{"loc":"00135:22-36","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv","peekRange":"135-135"}
{"loc":"00135:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv"}
{"loc":"00137:19-35","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ActorDestroyReason::AbnormalShutdown","sym":"E_<T_mozilla::ipc::IProtocol::ActorDestroyReason>_AbnormalShutdown","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv"}
{"loc":"00137:4-18","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::DestroySubtree","sym":"_ZN7mozilla3ipc9IProtocol14DestroySubtreeENS1_18ActorDestroyReasonE","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv"}
{"loc":"00138:4-16","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild::ClearSubtree","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild12ClearSubtreeEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv"}
{"loc":"00139:4-17","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::DeallocShmems","sym":"_ZN7mozilla3ipc17IToplevelProtocol13DeallocShmemsEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv"}
{"loc":"00140:8-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv"}
{"loc":"00141:29-36","target":1,"kind":"use","pretty":"mozilla::ipc::ActorLifecycleProxy::Release","sym":"_ZN7mozilla3ipc19ActorLifecycleProxy7ReleaseEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv"}
{"loc":"00141:8-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","context":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv"}
{"loc":"00145:22-34","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasicChild::ClearSubtree","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild12ClearSubtreeEv","peekRange":"145-145"}
{"loc":"00145:5-20","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasicChild::ClearSubtree","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild12ClearSubtreeEv"}
{"loc":"00153:10-13","target":1,"kind":"def","pretty":"IPC","sym":"NS_IPC"}
{"loc":"00154:37-52","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00154:5-16","target":1,"kind":"use","pretty":"IPC::ParamTraits","sym":"T_IPC::ParamTraits","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00154:56-61","target":1,"kind":"def","pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_","peekRange":"154-156"}
{"loc":"00155:13-26","target":1,"kind":"use","pretty":"IPC::MessageWriter","sym":"T_IPC::MessageWriter","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00156:14-23","target":1,"kind":"use","pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::paramType","sym":"T_IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild_*>::paramType","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00158:4-22","target":1,"kind":"use","pretty":"MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00159:17-25","target":1,"kind":"use","pretty":"IPC::MessageWriter::GetActor","sym":"_ZNK3IPC13MessageWriter8GetActorEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00162:4-11","target":1,"kind":"use","pretty":"int32_t","sym":"T_int32_t","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00166:19-21","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::Id","sym":"_ZNK7mozilla3ipc9IProtocol2IdEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00168:18-28","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00170:8-26","target":1,"kind":"use","pretty":"MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00171:21-29","target":1,"kind":"use","pretty":"IPC::MessageWriter::GetActor","sym":"_ZNK3IPC13MessageWriter8GetActorEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00171:33-46","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::GetIPCChannel","sym":"_ZN7mozilla3ipc9IProtocol13GetIPCChannelEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00171:58-71","target":1,"kind":"use","pretty":"mozilla::ipc::IToplevelProtocol::GetIPCChannel","sym":"_ZN7mozilla3ipc17IToplevelProtocol13GetIPCChannelEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00174:8-26","target":1,"kind":"use","pretty":"MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00175:18-25","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::CanSend","sym":"_ZNK7mozilla3ipc9IProtocol7CanSendEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00179:9-19","target":1,"kind":"use","pretty":"IPC::WriteParam","sym":"_ZN3IPCL10WriteParamEPNS_13MessageWriterEOT_","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_"}
{"loc":"00182:37-52","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00182:5-16","target":1,"kind":"use","pretty":"IPC::ParamTraits","sym":"T_IPC::ParamTraits","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00182:56-60","target":1,"kind":"def","pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_","peekRange":"182-184"}
{"loc":"00183:13-26","target":1,"kind":"use","pretty":"IPC::MessageReader","sym":"T_IPC::MessageReader","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00184:8-17","target":1,"kind":"use","pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::paramType","sym":"T_IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild_*>::paramType","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00186:4-22","target":1,"kind":"use","pretty":"MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00187:17-25","target":1,"kind":"use","pretty":"IPC::MessageReader::GetActor","sym":"_ZNK3IPC13MessageReader8GetActorEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00190:13-18","target":1,"kind":"use","pretty":"mozilla::Maybe","sym":"T_mozilla::Maybe","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00190:33-42","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol","sym":"T_mozilla::ipc::IProtocol","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00191:17-25","target":1,"kind":"use","pretty":"IPC::MessageReader::GetActor","sym":"_ZNK3IPC13MessageReader8GetActorEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00191:29-38","target":1,"kind":"use","pretty":"mozilla::ipc::IProtocol::ReadActor","sym":"_ZN7mozilla3ipc9IProtocol9ReadActorEPN3IPC13MessageReaderEbPKci","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00191:68-86","target":1,"kind":"use","pretty":"IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00192:14-23","target":1,"kind":"use","pretty":"mozilla::Maybe::isNothing","sym":"_ZNK7mozilla5Maybe9isNothingEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00196:44-59","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00196:68-73","target":1,"kind":"use","pretty":"mozilla::Maybe::value","sym":"_ZNKR7mozilla5Maybe5valueEv","context":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","contextsym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasicChild.cpp","sym":"FILE_linux@__GENERATED__/ipc/ipdl/PTestBasicChild@2Ecpp"}
{"loc":"00007:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00014:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_linux@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasicChild.cpp","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/PTestBasicChild@2Ecpp"}
{"loc":"00007:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00014:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_macosx@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasicChild.cpp","sym":"FILE_windows@__GENERATED__/ipc/ipdl/PTestBasicChild@2Ecpp"}
{"loc":"00007:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00014:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_windows@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00076:30-51","target":1,"kind":"use","pretty":"mozilla::ipc::LogMessageForProtocol","sym":"_ZN7mozilla3ipc21LogMessageForProtocolEPKcmS2_jNS0_16MessageDirectionE","context":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","contextsym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE"}
{"loc":"00001:0","source":1,"syntax":"def,file","pretty":"file __GENERATED__/ipc/ipdl/PTestBasicChild.cpp","sym":"FILE_windows@__GENERATED__/ipc/ipdl/PTestBasicChild@2Ecpp,FILE_macosx@__GENERATED__/ipc/ipdl/PTestBasicChild@2Ecpp,FILE_linux@__GENERATED__/ipc/ipdl/PTestBasicChild@2Ecpp,FILE_android-armv7@__GENERATED__/ipc/ipdl/PTestBasicChild@2Ecpp"}
{"loc":"00007:9-46","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00008:9-35","source":1,"syntax":"file,use","pretty":"file tools/profiler/public/ProfilerLabels.h","sym":"FILE_tools/profiler/public/ProfilerLabels@2Eh"}
{"loc":"00009:9-45","source":1,"syntax":"file,use","pretty":"file ipc/ipdl/test/gtest/TestBasicChild.h","sym":"FILE_ipc/ipdl/test/gtest/TestBasicChild@2Eh"}
{"loc":"00012:9-32","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh"}
{"loc":"00013:9-47","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh"}
{"loc":"00014:9-20","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/nsIFile.h","sym":"FILE_windows@__GENERATED__/dist/include/nsIFile@2Eh,FILE_macosx@__GENERATED__/dist/include/nsIFile@2Eh,FILE_linux@__GENERATED__/dist/include/nsIFile@2Eh,FILE_android-armv7@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00015:9-33","source":1,"syntax":"file,use","pretty":"file ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh"}
{"loc":"00016:9-45","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh"}
{"loc":"00017:9-38","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh"}
{"loc":"00018:9-42","source":1,"syntax":"file,use","pretty":"file ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh"}
{"loc":"00019:9-41","source":1,"syntax":"file,use","pretty":"file ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh"}
{"loc":"00021:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"21:19-152:0"}
{"loc":"00022:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"22:21-151:0"}
{"loc":"00025:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00025:22-37","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::ProcessingError","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc","nestingRange":"28:0-29:0","type":"auto (enum mozilla::ipc::HasResultCodes::Result, const char *) -> void"}
{"loc":"00026:8-14","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00026:15-20","source":1,"syntax":"","pretty":"variable aCode","sym":"V_c40c7ee2992e95a8_1ebe00f013,V_c01ac2d45ee2a132_1ebe00f013,V_13c625cddce69744_1ebe00f013,V_c35edacf7266e66e_1ebe00f013","no_crossref":1,"type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00027:20-27","source":1,"syntax":"","pretty":"variable aReason","sym":"V_9cc48ee2992e95a8_ea97235f0b0d,V_98d2d2d45ee2a132_ea97235f0b0d,V_ea8f25cddce69744_ea97235f0b0d,V_9b17eacf7266e66e_ea97235f0b0d","no_crossref":1,"type":"const char *"}
{"loc":"00031:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00031:22-52","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::ShouldContinueFromReplyTimeout","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild30ShouldContinueFromReplyTimeoutEv","nestingRange":"32:0-34:0","type":"auto (void) -> _Bool"}
{"loc":"00036:0-12","source":1,"syntax":"macro,use","pretty":"macro MOZ_IMPLICIT","sym":"M_5f65895d5a5258f7"}
{"loc":"00036:13-28","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00036:30-45","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","sym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev","nestingRange":"38:0-40:0","type":"void (void)"}
{"loc":"00037:4-11","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::ipc::IToplevelProtocol::IToplevelProtocol","sym":"_ZN7mozilla3ipc17IToplevelProtocolC1EPKc15IPCMessageStartNS0_4SideE"}
{"loc":"00037:18-35","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::IToplevelProtocol","sym":"T_mozilla::ipc::IToplevelProtocol","type":"class mozilla::ipc::IToplevelProtocol","typesym":"T_mozilla::ipc::IToplevelProtocol"}
{"loc":"00037:55-73","source":1,"syntax":"enum,use","pretty":"enum IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","type":"enum IPCMessageStart","typesym":"T_IPCMessageStart"}
{"loc":"00037:89-98","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::Side::ChildSide","sym":"E_<T_mozilla::ipc::Side>_ChildSide","type":"enum mozilla::ipc::Side","typesym":"T_mozilla::ipc::Side"}
{"loc":"00039:4-18","source":1,"syntax":"macro,use","pretty":"macro MOZ_COUNT_CTOR","sym":"M_d9d58f5149d9f0f2"}
{"loc":"00039:19-34","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00042:0-15","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00042:18-33","source":1,"syntax":"def,destructor","pretty":"destructor mozilla::_ipdltest::PTestBasicChild::~PTestBasicChild","sym":"_ZN7mozilla9_ipdltest15PTestBasicChildD1Ev","nestingRange":"43:0-45:0","type":"void (void) noexcept"}
{"loc":"00042:18-33","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00044:4-18","source":1,"syntax":"macro,use","pretty":"macro MOZ_COUNT_DTOR","sym":"M_f9e8c16149d9f0f2"}
{"loc":"00044:19-34","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00047:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00047:22-38","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::AllManagedActors","sym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE","nestingRange":"48:0-52:0","type":"auto (nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy> > &) const -> void"}
{"loc":"00047:39-47","source":1,"syntax":"type,use","pretty":"type nsTArray","sym":"T_nsTArray"}
{"loc":"00047:48-54","source":1,"syntax":"type,use","pretty":"type RefPtr","sym":"T_RefPtr"}
{"loc":"00047:69-88","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::ActorLifecycleProxy","sym":"T_mozilla::ipc::ActorLifecycleProxy","type":"class mozilla::ipc::ActorLifecycleProxy","typesym":"T_mozilla::ipc::ActorLifecycleProxy"}
{"loc":"00047:92-97","source":1,"syntax":"","pretty":"variable arr__","sym":"V_4be7c0f2992e95a8_8cdba1f013,V_47f515d45ee2a132_8cdba1f013,V_99a277cddce69744_8cdba1f013,V_4a3a2dcf7266e66e_8cdba1f013","no_crossref":1,"type":"nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy> > &"}
{"loc":"00049:4-12","source":1,"syntax":"type,use","pretty":"type uint32_t","sym":"T_uint32_t","type":"uint32_t"}
{"loc":"00049:13-18","source":1,"syntax":"","pretty":"variable total","sym":"V_f669d0f2992e95a8_903f070113,V_f27725d45ee2a132_903f070113,V_452487cddce69744_903f070113,V_f5bb3dcf7266e66e_903f070113","no_crossref":1,"type":"uint32_t"}
{"loc":"00050:4-9","source":1,"syntax":"","pretty":"variable arr__","sym":"V_4be7c0f2992e95a8_8cdba1f013,V_47f515d45ee2a132_8cdba1f013,V_99a277cddce69744_8cdba1f013,V_4a3a2dcf7266e66e_8cdba1f013","no_crossref":1,"type":"nsTArray<RefPtr<mozilla::ipc::ActorLifecycleProxy> > &"}
{"loc":"00050:10-21","source":1,"syntax":"function,use","pretty":"function nsTArray_Impl::SetCapacity","sym":"_ZN13nsTArray_Impl11SetCapacityEN13nsTArray_baseIT0_N27nsTArray_RelocationStrategyIT_E4TypeEE9size_typeE","type":"typename struct nsTArrayInfallibleAllocator::ResultType"}
{"loc":"00050:22-27","source":1,"syntax":"","pretty":"variable total","sym":"V_f669d0f2992e95a8_903f070113,V_f27725d45ee2a132_903f070113,V_452487cddce69744_903f070113,V_f5bb3dcf7266e66e_903f070113","no_crossref":1,"type":"uint32_t"}
{"loc":"00054:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00054:22-35","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::RemoveManagee","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild13RemoveManageeEiPNS_3ipc9IProtocolE","nestingRange":"57:0-60:0","type":"auto (int32_t, mozilla::_ipdltest::PTestBasicChild::IProtocol *) -> void"}
{"loc":"00055:8-15","source":1,"syntax":"type,use","pretty":"type int32_t","sym":"T_int32_t","type":"int32_t"}
{"loc":"00055:16-27","source":1,"syntax":"","pretty":"variable aProtocolId","sym":"V_f6d7d1f2992e95a8_542cb52f47aba60c,V_f2e526d45ee2a132_542cb52f47aba60c,V_459288cddce69744_542cb52f47aba60c,V_f52a3ecf7266e66e_542cb52f47aba60c","no_crossref":1,"type":"int32_t"}
{"loc":"00056:8-17","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::IProtocol","sym":"T_mozilla::_ipdltest::PTestBasicChild::IProtocol","type":"mozilla::_ipdltest::PTestBasicChild::IProtocol","typesym":"T_mozilla::ipc::IProtocol"}
{"loc":"00056:19-28","source":1,"syntax":"","pretty":"variable aListener","sym":"V_3d90e1f2992e95a8_c681f10e880c773,V_39ae26d45ee2a132_c681f10e880c773,V_8b5b88cddce69744_c681f10e880c773,V_3ce24ecf7266e66e_c681f10e880c773","no_crossref":1,"type":"mozilla::_ipdltest::PTestBasicChild::IProtocol *"}
{"loc":"00058:4-14","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00062:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00062:22-36","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::DeallocManagee","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14DeallocManageeEiPNS_3ipc9IProtocolE","nestingRange":"65:0-68:0","type":"auto (int32_t, mozilla::_ipdltest::PTestBasicChild::IProtocol *) -> void"}
{"loc":"00063:8-15","source":1,"syntax":"type,use","pretty":"type int32_t","sym":"T_int32_t","type":"int32_t"}
{"loc":"00063:16-27","source":1,"syntax":"","pretty":"variable aProtocolId","sym":"V_e2d7e2f2992e95a8_542cb52f47aba60c,V_eed537d45ee2a132_542cb52f47aba60c,V_319299cddce69744_542cb52f47aba60c,V_e12a4fcf7266e66e_542cb52f47aba60c","no_crossref":1,"type":"int32_t"}
{"loc":"00064:8-17","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::IProtocol","sym":"T_mozilla::_ipdltest::PTestBasicChild::IProtocol","type":"mozilla::_ipdltest::PTestBasicChild::IProtocol","typesym":"T_mozilla::ipc::IProtocol"}
{"loc":"00064:19-28","source":1,"syntax":"","pretty":"variable aListener","sym":"V_2990f2f2992e95a8_c681f10e880c773,V_25ae37d45ee2a132_c681f10e880c773,V_775b99cddce69744_c681f10e880c773,V_28e25fcf7266e66e_c681f10e880c773","no_crossref":1,"type":"mozilla::_ipdltest::PTestBasicChild::IProtocol *"}
{"loc":"00066:4-14","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00070:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00070:22-39","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE","nestingRange":"71:0-107:0","type":"auto (const mozilla::_ipdltest::PTestBasicChild::Message &) -> class PTestBasicChild::Result"}
{"loc":"00070:46-53","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","type":"mozilla::_ipdltest::PTestBasicChild::Message","typesym":"T_IPC::Message"}
{"loc":"00070:55-60","source":1,"syntax":"","pretty":"variable msg__","sym":"V_f01fe3f2992e95a8_a6144ff013,V_fc1d38d45ee2a132_a6144ff013,V_4fc99acddce69744_a6144ff013,V_ff5150df7266e66e_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicChild::Message &"}
{"loc":"00070:65-80","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00070:82-88","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00072:12-17","source":1,"syntax":"","pretty":"variable msg__","sym":"V_f01fe3f2992e95a8_a6144ff013,V_fc1d38d45ee2a132_a6144ff013,V_4fc99acddce69744_a6144ff013,V_ff5150df7266e66e_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicChild::Message &"}
{"loc":"00072:18-22","source":1,"syntax":"function,use","pretty":"function IPC::Message::type","sym":"_ZNK3IPC7Message4typeEv","type":"IPC::Message::msgid_t"}
{"loc":"00073:21-34","source":1,"syntax":"enum,use","pretty":"enum mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00075:30-47","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::LoggingEnabledFor","sym":"_ZN7mozilla3ipc17LoggingEnabledForEPKc","type":"_Bool (const char *)"}
{"loc":"00076:30-51","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::LogMessageForProtocol","sym":"_ZN7mozilla3ipc21LogMessageForProtocolEPKcmS2_jNS0_16MessageDirectionE,_ZN7mozilla3ipc21LogMessageForProtocolEPKciS2_jNS0_16MessageDirectionE","type":"void (const char *, base::ProcessId, const char *, uint32_t, enum mozilla::ipc::MessageDirection)"}
{"loc":"00078:26-42","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::ToplevelProtocol","sym":"_ZN7mozilla3ipc9IProtocol16ToplevelProtocolEv","type":"class mozilla::ipc::IToplevelProtocol *"}
{"loc":"00078:46-66","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IToplevelProtocol::OtherPidMaybeInvalid","sym":"_ZNK7mozilla3ipc17IToplevelProtocol20OtherPidMaybeInvalidEv","type":"base::ProcessId"}
{"loc":"00080:23-28","source":1,"syntax":"","pretty":"variable msg__","sym":"V_f01fe3f2992e95a8_a6144ff013,V_fc1d38d45ee2a132_a6144ff013,V_4fc99acddce69744_a6144ff013,V_ff5150df7266e66e_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicChild::Message &"}
{"loc":"00080:32-36","source":1,"syntax":"function,use","pretty":"function IPC::Message::type","sym":"_ZNK3IPC7Message4typeEv","type":"IPC::Message::msgid_t"}
{"loc":"00081:34-50","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::MessageDirection","sym":"T_mozilla::ipc::MessageDirection","type":"enum mozilla::ipc::MessageDirection","typesym":"T_mozilla::ipc::MessageDirection"}
{"loc":"00081:52-62","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::MessageDirection::eReceiving","sym":"E_<T_mozilla::ipc::MessageDirection>_eReceiving","type":"enum mozilla::ipc::MessageDirection","typesym":"T_mozilla::ipc::MessageDirection"}
{"loc":"00083:12-31","source":1,"syntax":"macro,use","pretty":"macro AUTO_PROFILER_LABEL","sym":"M_99e0335dc782f2d6"}
{"loc":"00083:12-31","source":1,"syntax":"","pretty":"variable raiiObject83","sym":"V_5e5b2_c869d3b76a0990ad","no_crossref":1,"type":"mozilla::AutoProfilerLabel","typesym":"T_mozilla::AutoProfilerLabel"}
{"loc":"00083:57-62","source":1,"syntax":"enum,use","pretty":"enum JS::ProfilingCategoryPair::OTHER","sym":"E_<T_JS::ProfilingCategoryPair>_OTHER","type":"enum JS::ProfilingCategoryPair","typesym":"T_JS::ProfilingCategoryPair"}
{"loc":"00085:26-35","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::IPCResult","sym":"T_mozilla::ipc::IPCResult","type":"class mozilla::ipc::IPCResult","typesym":"T_mozilla::ipc::IPCResult"}
{"loc":"00085:36-40","source":1,"syntax":"","pretty":"variable __ok","sym":"V_437c35f2992e95a8_d5ac29c71,V_4f7a89d45ee2a132_d5ac29c71,V_9137ebcddce69744_d5ac29c71,V_42ce91df7266e66e_d5ac29c71","no_crossref":1,"type":"mozilla::ipc::IPCResult","typesym":"T_mozilla::ipc::IPCResult"}
{"loc":"00085:56-70","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::TestBasicChild","sym":"T_mozilla::_ipdltest::TestBasicChild","type":"class mozilla::_ipdltest::TestBasicChild","typesym":"T_mozilla::_ipdltest::TestBasicChild"}
{"loc":"00085:81-90","source":1,"syntax":"function,use","pretty":"function mozilla::_ipdltest::TestBasicChild::RecvHello","sym":"_ZN7mozilla9_ipdltest14TestBasicChild9RecvHelloEv","type":"mozilla::ipc::IPCResult","typesym":"T_mozilla::ipc::IPCResult"}
{"loc":"00086:19-23","source":1,"syntax":"","pretty":"variable __ok","sym":"V_437c35f2992e95a8_d5ac29c71,V_4f7a89d45ee2a132_d5ac29c71,V_9137ebcddce69744_d5ac29c71,V_42ce91df7266e66e_d5ac29c71","no_crossref":1,"type":"mozilla::ipc::IPCResult","typesym":"T_mozilla::ipc::IPCResult"}
{"loc":"00087:30-53","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::ProtocolErrorBreakpoint","sym":"_ZN7mozilla3ipc23ProtocolErrorBreakpointEPKc","type":"void (const char *)"}
{"loc":"00089:23-41","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgProcessingError","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgProcessingError","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00092:19-31","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgProcessed","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgProcessed","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00095:15-26","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00096:9-35","source":1,"syntax":"enum,use","pretty":"enum SHMEM_CREATED_MESSAGE_TYPE","sym":"E_<T_b078e220e89184de>_SHMEM_CREATED_MESSAGE_TYPE","type":"enum (anonymous namespace)::(unnamed at /builds/worker/workspace/obj-build/dist/include/mozilla/ipc/ProtocolUtils.h:57:1)","typesym":"T_b078e220e89184de"}
{"loc":"00098:12-22","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00099:19-30","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00101:9-37","source":1,"syntax":"enum,use","pretty":"enum SHMEM_DESTROYED_MESSAGE_TYPE","sym":"E_<T_b078e220e89184de>_SHMEM_DESTROYED_MESSAGE_TYPE","type":"enum (anonymous namespace)::(unnamed at /builds/worker/workspace/obj-build/dist/include/mozilla/ipc/ProtocolUtils.h:57:1)","typesym":"T_b078e220e89184de"}
{"loc":"00103:12-22","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00104:19-30","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00109:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00109:22-39","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","nestingRange":"112:0-115:0","type":"auto (const mozilla::_ipdltest::PTestBasicChild::Message &, UniquePtr<mozilla::_ipdltest::PTestBasicChild::Message> &) -> class PTestBasicChild::Result"}
{"loc":"00110:14-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","type":"mozilla::_ipdltest::PTestBasicChild::Message","typesym":"T_IPC::Message"}
{"loc":"00110:23-28","source":1,"syntax":"","pretty":"variable msg__","sym":"V_54687213992e95a8_a6144ff013,V_5076c6f45ee2a132_a6144ff013,V_a22329eddce69744_a6144ff013,V_53badeef7266e66e_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicChild::Message &"}
{"loc":"00111:8-17","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicChild::UniquePtr"}
{"loc":"00111:18-25","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","type":"mozilla::_ipdltest::PTestBasicChild::Message","typesym":"T_IPC::Message"}
{"loc":"00111:28-35","source":1,"syntax":"","pretty":"variable reply__","sym":"V_ba218213992e95a8_f83bfee36b0d,V_b63fc6f45ee2a132_f83bfee36b0d,V_09eb29eddce69744_f83bfee36b0d,V_b973eeef7266e66e_f83bfee36b0d","no_crossref":1,"type":"UniquePtr<mozilla::_ipdltest::PTestBasicChild::Message> &"}
{"loc":"00111:40-55","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00111:57-63","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00113:4-26","source":1,"syntax":"macro,use","pretty":"macro MOZ_ASSERT_UNREACHABLE","sym":"M_0d9562839add515c"}
{"loc":"00114:11-22","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00117:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00117:22-36","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::OnCallReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","nestingRange":"120:0-123:0","type":"auto (const mozilla::_ipdltest::PTestBasicChild::Message &, UniquePtr<mozilla::_ipdltest::PTestBasicChild::Message> &) -> class PTestBasicChild::Result"}
{"loc":"00118:14-21","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","type":"mozilla::_ipdltest::PTestBasicChild::Message","typesym":"T_IPC::Message"}
{"loc":"00118:23-28","source":1,"syntax":"","pretty":"variable msg__","sym":"V_d49eb213992e95a8_a6144ff013,V_d0ac07f45ee2a132_a6144ff013,V_235969eddce69744_a6144ff013,V_d3e02fef7266e66e_a6144ff013","no_crossref":1,"type":"const mozilla::_ipdltest::PTestBasicChild::Message &"}
{"loc":"00119:8-17","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::UniquePtr","sym":"T_mozilla::_ipdltest::PTestBasicChild::UniquePtr"}
{"loc":"00119:18-25","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild::Message","sym":"T_mozilla::_ipdltest::PTestBasicChild::Message","type":"mozilla::_ipdltest::PTestBasicChild::Message","typesym":"T_IPC::Message"}
{"loc":"00119:28-35","source":1,"syntax":"","pretty":"variable reply__","sym":"V_3b57c213992e95a8_f83bfee36b0d,V_376517f45ee2a132_f83bfee36b0d,V_891279eddce69744_f83bfee36b0d,V_3aa92fef7266e66e_f83bfee36b0d","no_crossref":1,"type":"UniquePtr<mozilla::_ipdltest::PTestBasicChild::Message> &"}
{"loc":"00119:40-55","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00119:57-63","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::HasResultCodes::Result","sym":"T_mozilla::ipc::HasResultCodes::Result","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00121:4-26","source":1,"syntax":"macro,use","pretty":"macro MOZ_ASSERT_UNREACHABLE","sym":"M_0d9562839add515c"}
{"loc":"00122:11-22","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::HasResultCodes::Result::MsgNotKnown","sym":"E_<T_mozilla::ipc::HasResultCodes::Result>_MsgNotKnown","type":"enum mozilla::ipc::HasResultCodes::Result","typesym":"T_mozilla::ipc::HasResultCodes::Result"}
{"loc":"00125:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00125:22-36","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::OnChannelClose","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv","nestingRange":"126:0-133:0","type":"auto (void) -> void"}
{"loc":"00127:4-18","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::DestroySubtree","sym":"_ZN7mozilla3ipc9IProtocol14DestroySubtreeENS1_18ActorDestroyReasonE","type":"void"}
{"loc":"00127:19-33","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::IProtocol::ActorDestroyReason::NormalShutdown","sym":"E_<T_mozilla::ipc::IProtocol::ActorDestroyReason>_NormalShutdown","type":"enum mozilla::ipc::IProtocol::ActorDestroyReason","typesym":"T_mozilla::ipc::IProtocol::ActorDestroyReason"}
{"loc":"00128:4-16","source":1,"syntax":"function,use","pretty":"function mozilla::_ipdltest::PTestBasicChild::ClearSubtree","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild12ClearSubtreeEv","type":"void"}
{"loc":"00129:4-17","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IToplevelProtocol::DeallocShmems","sym":"_ZN7mozilla3ipc17IToplevelProtocol13DeallocShmemsEv","type":"void"}
{"loc":"00130:8-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","type":"class mozilla::ipc::ActorLifecycleProxy *"}
{"loc":"00131:8-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","type":"class mozilla::ipc::ActorLifecycleProxy *"}
{"loc":"00131:29-36","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::ActorLifecycleProxy::Release","sym":"_ZN7mozilla3ipc19ActorLifecycleProxy7ReleaseEv","type":"MozExternalRefCountType"}
{"loc":"00135:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00135:22-36","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::OnChannelError","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv","nestingRange":"136:0-143:0","type":"auto (void) -> void"}
{"loc":"00137:4-18","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::DestroySubtree","sym":"_ZN7mozilla3ipc9IProtocol14DestroySubtreeENS1_18ActorDestroyReasonE","type":"void"}
{"loc":"00137:19-35","source":1,"syntax":"enum,use","pretty":"enum mozilla::ipc::IProtocol::ActorDestroyReason::AbnormalShutdown","sym":"E_<T_mozilla::ipc::IProtocol::ActorDestroyReason>_AbnormalShutdown","type":"enum mozilla::ipc::IProtocol::ActorDestroyReason","typesym":"T_mozilla::ipc::IProtocol::ActorDestroyReason"}
{"loc":"00138:4-16","source":1,"syntax":"function,use","pretty":"function mozilla::_ipdltest::PTestBasicChild::ClearSubtree","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild12ClearSubtreeEv","type":"void"}
{"loc":"00139:4-17","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IToplevelProtocol::DeallocShmems","sym":"_ZN7mozilla3ipc17IToplevelProtocol13DeallocShmemsEv","type":"void"}
{"loc":"00140:8-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","type":"class mozilla::ipc::ActorLifecycleProxy *"}
{"loc":"00141:8-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetLifecycleProxy","sym":"_ZN7mozilla3ipc9IProtocol17GetLifecycleProxyEv","type":"class mozilla::ipc::ActorLifecycleProxy *"}
{"loc":"00141:29-36","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::ActorLifecycleProxy::Release","sym":"_ZN7mozilla3ipc19ActorLifecycleProxy7ReleaseEv","type":"MozExternalRefCountType"}
{"loc":"00145:5-20","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00145:22-34","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasicChild::ClearSubtree","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild12ClearSubtreeEv","nestingRange":"146:0-147:0","type":"auto (void) -> void"}
{"loc":"00153:10-13","source":1,"syntax":"def,namespace","pretty":"namespace IPC","sym":"NS_IPC","nestingRange":"153:15-200:0"}
{"loc":"00154:5-16","source":1,"syntax":"type,use","pretty":"type IPC::ParamTraits","sym":"T_IPC::ParamTraits"}
{"loc":"00154:37-52","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00154:56-61","source":1,"syntax":"def,function","pretty":"function IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_","nestingRange":"157:0-180:0","type":"auto (IPC::MessageWriter *, const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType &) -> void"}
{"loc":"00155:13-26","source":1,"syntax":"type,use","pretty":"type IPC::MessageWriter","sym":"T_IPC::MessageWriter","type":"class IPC::MessageWriter","typesym":"T_IPC::MessageWriter"}
{"loc":"00155:28-35","source":1,"syntax":"","pretty":"variable aWriter","sym":"V_336a2713992e95a8_369ebc101b0d,V_3f687bf45ee2a132_369ebc101b0d,V_8125ddeddce69744_369ebc101b0d,V_32bc83ff7266e66e_369ebc101b0d","no_crossref":1,"type":"IPC::MessageWriter *"}
{"loc":"00156:14-23","source":1,"syntax":"type,use","pretty":"type IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::paramType","sym":"T_IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild_*>::paramType","type":"IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType"}
{"loc":"00156:25-29","source":1,"syntax":"","pretty":"variable aVar","sym":"V_19233713992e95a8_f0bb39c71,V_15318bf45ee2a132_f0bb39c71,V_67edddeddce69744_f0bb39c71,V_187593ff7266e66e_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType &"}
{"loc":"00158:4-22","source":1,"syntax":"macro,use","pretty":"macro MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00159:8-15","source":1,"syntax":"","pretty":"variable aWriter","sym":"V_336a2713992e95a8_369ebc101b0d,V_3f687bf45ee2a132_369ebc101b0d,V_8125ddeddce69744_369ebc101b0d,V_32bc83ff7266e66e_369ebc101b0d","no_crossref":1,"type":"IPC::MessageWriter *"}
{"loc":"00159:17-25","source":1,"syntax":"function,use","pretty":"function IPC::MessageWriter::GetActor","sym":"_ZNK3IPC13MessageWriter8GetActorEv","type":"mozilla::ipc::IProtocol *"}
{"loc":"00162:4-11","source":1,"syntax":"type,use","pretty":"type int32_t","sym":"T_int32_t","type":"int32_t"}
{"loc":"00162:12-14","source":1,"syntax":"","pretty":"variable id","sym":"V_a6913813992e95a8_238795,V_a2af7cf45ee2a132_238795,V_f45cdeeddce69744_238795,V_a5e394ff7266e66e_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00163:9-13","source":1,"syntax":"","pretty":"variable aVar","sym":"V_19233713992e95a8_f0bb39c71,V_15318bf45ee2a132_f0bb39c71,V_67edddeddce69744_f0bb39c71,V_187593ff7266e66e_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType &"}
{"loc":"00164:8-10","source":1,"syntax":"","pretty":"variable id","sym":"V_a6913813992e95a8_238795,V_a2af7cf45ee2a132_238795,V_f45cdeeddce69744_238795,V_a5e394ff7266e66e_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00166:8-10","source":1,"syntax":"","pretty":"variable id","sym":"V_a6913813992e95a8_238795,V_a2af7cf45ee2a132_238795,V_f45cdeeddce69744_238795,V_a5e394ff7266e66e_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00166:13-17","source":1,"syntax":"","pretty":"variable aVar","sym":"V_19233713992e95a8_f0bb39c71,V_15318bf45ee2a132_f0bb39c71,V_67edddeddce69744_f0bb39c71,V_187593ff7266e66e_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType &"}
{"loc":"00166:19-21","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::Id","sym":"_ZNK7mozilla3ipc9IProtocol2IdEv","type":"int32_t"}
{"loc":"00167:12-14","source":1,"syntax":"","pretty":"variable id","sym":"V_a6913813992e95a8_238795,V_a2af7cf45ee2a132_238795,V_f45cdeeddce69744_238795,V_a5e394ff7266e66e_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00168:12-16","source":1,"syntax":"","pretty":"variable aVar","sym":"V_19233713992e95a8_f0bb39c71,V_15318bf45ee2a132_f0bb39c71,V_67edddeddce69744_f0bb39c71,V_187593ff7266e66e_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType &"}
{"loc":"00168:18-28","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::FatalError","sym":"_ZNK7mozilla3ipc9IProtocol10FatalErrorEPKc","type":"void"}
{"loc":"00170:8-26","source":1,"syntax":"macro,use","pretty":"macro MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00171:12-19","source":1,"syntax":"","pretty":"variable aWriter","sym":"V_336a2713992e95a8_369ebc101b0d,V_3f687bf45ee2a132_369ebc101b0d,V_8125ddeddce69744_369ebc101b0d,V_32bc83ff7266e66e_369ebc101b0d","no_crossref":1,"type":"IPC::MessageWriter *"}
{"loc":"00171:21-29","source":1,"syntax":"function,use","pretty":"function IPC::MessageWriter::GetActor","sym":"_ZNK3IPC13MessageWriter8GetActorEv","type":"mozilla::ipc::IProtocol *"}
{"loc":"00171:33-46","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::GetIPCChannel","sym":"_ZN7mozilla3ipc9IProtocol13GetIPCChannelEv","type":"class mozilla::ipc::MessageChannel *"}
{"loc":"00171:52-56","source":1,"syntax":"","pretty":"variable aVar","sym":"V_19233713992e95a8_f0bb39c71,V_15318bf45ee2a132_f0bb39c71,V_67edddeddce69744_f0bb39c71,V_187593ff7266e66e_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType &"}
{"loc":"00171:58-71","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IToplevelProtocol::GetIPCChannel","sym":"_ZN7mozilla3ipc17IToplevelProtocol13GetIPCChannelEv","type":"class mozilla::ipc::MessageChannel *"}
{"loc":"00174:8-26","source":1,"syntax":"macro,use","pretty":"macro MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00175:12-16","source":1,"syntax":"","pretty":"variable aVar","sym":"V_19233713992e95a8_f0bb39c71,V_15318bf45ee2a132_f0bb39c71,V_67edddeddce69744_f0bb39c71,V_187593ff7266e66e_f0bb39c71","no_crossref":1,"type":"const IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType &"}
{"loc":"00175:18-25","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::CanSend","sym":"_ZNK7mozilla3ipc9IProtocol7CanSendEv","type":"_Bool"}
{"loc":"00179:9-19","source":1,"syntax":"function,use","pretty":"function IPC::WriteParam","sym":"_ZN3IPCL10WriteParamEPNS_13MessageWriterEOT_","type":"void (class IPC::MessageWriter *, int &)"}
{"loc":"00179:20-27","source":1,"syntax":"","pretty":"variable aWriter","sym":"V_336a2713992e95a8_369ebc101b0d,V_3f687bf45ee2a132_369ebc101b0d,V_8125ddeddce69744_369ebc101b0d,V_32bc83ff7266e66e_369ebc101b0d","no_crossref":1,"type":"IPC::MessageWriter *"}
{"loc":"00179:29-31","source":1,"syntax":"","pretty":"variable id","sym":"V_a6913813992e95a8_238795,V_a2af7cf45ee2a132_238795,V_f45cdeeddce69744_238795,V_a5e394ff7266e66e_238795","no_crossref":1,"type":"int32_t"}
{"loc":"00182:5-16","source":1,"syntax":"type,use","pretty":"type IPC::ParamTraits","sym":"T_IPC::ParamTraits"}
{"loc":"00182:37-52","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00182:56-60","source":1,"syntax":"def,function","pretty":"function IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_","nestingRange":"185:0-198:0","type":"auto (IPC::MessageReader *, IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType *) -> _Bool"}
{"loc":"00183:13-26","source":1,"syntax":"type,use","pretty":"type IPC::MessageReader","sym":"T_IPC::MessageReader","type":"class IPC::MessageReader","typesym":"T_IPC::MessageReader"}
{"loc":"00183:28-35","source":1,"syntax":"","pretty":"variable aReader","sym":"V_4f6d7a13992e95a8_9983235f0b0d,V_4b7bcef45ee2a132_9983235f0b0d,V_9d2821fddce69744_9983235f0b0d,V_4ebfd6ff7266e66e_9983235f0b0d","no_crossref":1,"type":"IPC::MessageReader *"}
{"loc":"00184:8-17","source":1,"syntax":"type,use","pretty":"type IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::paramType","sym":"T_IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild_*>::paramType","type":"IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType"}
{"loc":"00184:19-23","source":1,"syntax":"","pretty":"variable aVar","sym":"V_53368a13992e95a8_f0bb39c71,V_5f34def45ee2a132_f0bb39c71,V_a1f031fddce69744_f0bb39c71,V_5288e6ff7266e66e_f0bb39c71","no_crossref":1,"type":"IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType *"}
{"loc":"00186:4-22","source":1,"syntax":"macro,use","pretty":"macro MOZ_RELEASE_ASSERT","sym":"M_96f821839add515c"}
{"loc":"00187:8-15","source":1,"syntax":"","pretty":"variable aReader","sym":"V_4f6d7a13992e95a8_9983235f0b0d,V_4b7bcef45ee2a132_9983235f0b0d,V_9d2821fddce69744_9983235f0b0d,V_4ebfd6ff7266e66e_9983235f0b0d","no_crossref":1,"type":"IPC::MessageReader *"}
{"loc":"00187:17-25","source":1,"syntax":"function,use","pretty":"function IPC::MessageReader::GetActor","sym":"_ZNK3IPC13MessageReader8GetActorEv","type":"mozilla::ipc::IProtocol *"}
{"loc":"00190:13-18","source":1,"syntax":"type,use","pretty":"type mozilla::Maybe","sym":"T_mozilla::Maybe"}
{"loc":"00190:33-42","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::IProtocol","sym":"T_mozilla::ipc::IProtocol","type":"class mozilla::ipc::IProtocol","typesym":"T_mozilla::ipc::IProtocol"}
{"loc":"00190:45-50","source":1,"syntax":"","pretty":"variable actor","sym":"V_19a48b13992e95a8_ebe821f013,V_15b2dff45ee2a132_ebe821f013,V_676f22fddce69744_ebe821f013,V_18f6e7ff7266e66e_ebe821f013","no_crossref":1,"type":"mozilla::Maybe<mozilla::ipc::IProtocol *>","typesym":"T_mozilla::Maybe"}
{"loc":"00191:8-15","source":1,"syntax":"","pretty":"variable aReader","sym":"V_4f6d7a13992e95a8_9983235f0b0d,V_4b7bcef45ee2a132_9983235f0b0d,V_9d2821fddce69744_9983235f0b0d,V_4ebfd6ff7266e66e_9983235f0b0d","no_crossref":1,"type":"IPC::MessageReader *"}
{"loc":"00191:17-25","source":1,"syntax":"function,use","pretty":"function IPC::MessageReader::GetActor","sym":"_ZNK3IPC13MessageReader8GetActorEv","type":"mozilla::ipc::IProtocol *"}
{"loc":"00191:29-38","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::IProtocol::ReadActor","sym":"_ZN7mozilla3ipc9IProtocol9ReadActorEPN3IPC13MessageReaderEbPKci","type":"Maybe<class mozilla::ipc::IProtocol *>","typesym":"T_mozilla::Maybe"}
{"loc":"00191:39-46","source":1,"syntax":"","pretty":"variable aReader","sym":"V_4f6d7a13992e95a8_9983235f0b0d,V_4b7bcef45ee2a132_9983235f0b0d,V_9d2821fddce69744_9983235f0b0d,V_4ebfd6ff7266e66e_9983235f0b0d","no_crossref":1,"type":"IPC::MessageReader *"}
{"loc":"00191:68-86","source":1,"syntax":"enum,use","pretty":"enum IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","type":"enum IPCMessageStart","typesym":"T_IPCMessageStart"}
{"loc":"00192:8-13","source":1,"syntax":"","pretty":"variable actor","sym":"V_19a48b13992e95a8_ebe821f013,V_15b2dff45ee2a132_ebe821f013,V_676f22fddce69744_ebe821f013,V_18f6e7ff7266e66e_ebe821f013","no_crossref":1,"type":"mozilla::Maybe<mozilla::ipc::IProtocol *>","typesym":"T_mozilla::Maybe"}
{"loc":"00192:14-23","source":1,"syntax":"function,use","pretty":"function mozilla::Maybe::isNothing","sym":"_ZNK7mozilla5Maybe9isNothingEv","type":"_Bool"}
{"loc":"00196:5-9","source":1,"syntax":"","pretty":"variable aVar","sym":"V_53368a13992e95a8_f0bb39c71,V_5f34def45ee2a132_f0bb39c71,V_a1f031fddce69744_f0bb39c71,V_5288e6ff7266e66e_f0bb39c71","no_crossref":1,"type":"IPC::ParamTraits<class mozilla::_ipdltest::PTestBasicChild *>::paramType *"}
{"loc":"00196:44-59","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00196:62-67","source":1,"syntax":"","pretty":"variable actor","sym":"V_19a48b13992e95a8_ebe821f013,V_15b2dff45ee2a132_ebe821f013,V_676f22fddce69744_ebe821f013,V_18f6e7ff7266e66e_ebe821f013","no_crossref":1,"type":"mozilla::Maybe<mozilla::ipc::IProtocol *>","typesym":"T_mozilla::Maybe"}
{"loc":"00196:68-73","source":1,"syntax":"function,use","pretty":"function mozilla::Maybe::value","sym":"_ZNKR7mozilla5Maybe5valueEv","type":"class mozilla::ipc::IProtocol *"}
{"loc":"00182:56-60","structured":1,"pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Read","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE4ReadEPNS_13MessageReaderEPS4_","kind":"method","parentsym":"T_IPC::ParamTraits","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["static","user"]}
{"loc":"00154:56-61","structured":1,"pretty":"IPC::ParamTraits<mozilla::_ipdltest::PTestBasicChild *>::Write","sym":"_ZN3IPC11ParamTraitsIPN7mozilla9_ipdltest15PTestBasicChildEE5WriteEPNS_13MessageWriterERKS4_","kind":"method","parentsym":"T_IPC::ParamTraits","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["static","user"]}
{"loc":"00145:22-34","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::ClearSubtree","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild12ClearSubtreeEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["instance","user"]}
{"loc":"00054:22-35","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::RemoveManagee","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild13RemoveManageeEiPNS_3ipc9IProtocolE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::RemoveManagee","sym":"_ZN7mozilla3ipc9IProtocol13RemoveManageeEiPS1_"}],"props":["instance","virtual","user"]}
{"loc":"00062:22-36","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::DeallocManagee","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14DeallocManageeEiPNS_3ipc9IProtocolE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::DeallocManagee","sym":"_ZN7mozilla3ipc9IProtocol14DeallocManageeEiPS1_"}],"props":["instance","virtual","user"]}
{"loc":"00117:22-36","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::OnCallReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::OnCallReceived","sym":"_ZN7mozilla3ipc9IProtocol14OnCallReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}],"props":["instance","virtual","user"]}
{"loc":"00125:22-36","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::OnChannelClose","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelCloseEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::OnChannelClose","sym":"_ZN7mozilla3ipc17IToplevelProtocol14OnChannelCloseEv"}],"props":["instance","virtual","user"]}
{"loc":"00135:22-36","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::OnChannelError","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild14OnChannelErrorEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::OnChannelError","sym":"_ZN7mozilla3ipc17IToplevelProtocol14OnChannelErrorEv"}],"props":["instance","virtual","user"]}
{"loc":"00025:22-37","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::ProcessingError","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild15ProcessingErrorENS_3ipc14HasResultCodes6ResultEPKc","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::ProcessingError","sym":"_ZN7mozilla3ipc17IToplevelProtocol15ProcessingErrorENS0_14HasResultCodes6ResultEPKc"}],"props":["instance","virtual","user"]}
{"loc":"00070:22-39","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::OnMessageReceived","sym":"_ZN7mozilla3ipc9IProtocol17OnMessageReceivedERKN3IPC7MessageE"}],"props":["instance","virtual","user"]}
{"loc":"00109:22-39","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::OnMessageReceived","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::OnMessageReceived","sym":"_ZN7mozilla3ipc9IProtocol17OnMessageReceivedERKN3IPC7MessageERNS_9UniquePtrIS3_NS_13DefaultDeleteIS3_EEEE"}],"props":["instance","virtual","user"]}
{"loc":"00031:22-52","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::ShouldContinueFromReplyTimeout","sym":"_ZN7mozilla9_ipdltest15PTestBasicChild30ShouldContinueFromReplyTimeoutEv","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::ShouldContinueFromReplyTimeout","sym":"_ZN7mozilla3ipc17IToplevelProtocol30ShouldContinueFromReplyTimeoutEv"}],"props":["instance","virtual","user"]}
{"loc":"00036:30-45","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::PTestBasicChild","sym":"_ZN7mozilla9_ipdltest15PTestBasicChildC1Ev","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":["instance","user"]}
{"loc":"00042:18-33","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::~PTestBasicChild","sym":"_ZN7mozilla9_ipdltest15PTestBasicChildD1Ev","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IToplevelProtocol::~IToplevelProtocol","sym":"_ZN7mozilla3ipc17IToplevelProtocolD1Ev"}],"props":["instance","virtual","user"]}
{"loc":"00047:22-38","structured":1,"pretty":"mozilla::_ipdltest::PTestBasicChild::AllManagedActors","sym":"_ZNK7mozilla9_ipdltest15PTestBasicChild16AllManagedActorsER8nsTArrayI6RefPtrINS_3ipc19ActorLifecycleProxyEEE","kind":"method","parentsym":"T_mozilla::_ipdltest::PTestBasicChild","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[{"pretty":"mozilla::ipc::IProtocol::AllManagedActors","sym":"_ZNK7mozilla3ipc9IProtocol16AllManagedActorsER8nsTArrayI6RefPtrINS0_19ActorLifecycleProxyEEE"}],"props":["instance","virtual","user"]}
