{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00011:9-32","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh"}
{"loc":"00012:9-47","target":1,"kind":"use","pretty":"ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_android-armv7@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00014:9-33","target":1,"kind":"use","pretty":"ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh"}
{"loc":"00015:9-45","target":1,"kind":"use","pretty":"ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh"}
{"loc":"00016:9-38","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh"}
{"loc":"00017:9-42","target":1,"kind":"use","pretty":"ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh"}
{"loc":"00018:9-41","target":1,"kind":"use","pretty":"ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh"}
{"loc":"00020:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00021:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00022:10-20","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic","sym":"NS_mozilla::_ipdltest::PTestBasic"}
{"loc":"00024:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00025:0-15","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","peekRange":"24-29"}
{"loc":"00026:14-23","target":1,"kind":"use","pretty":"base::ProcessId","sym":"T_base::ProcessId","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00027:14-23","target":1,"kind":"use","pretty":"base::ProcessId","sym":"T_base::ProcessId","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00028:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00028:51-67","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00029:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00029:51-66","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00031:25-40","target":1,"kind":"use","pretty":"mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceEiiPNS0_8EndpointIT_EEPNS4_IT0_EE","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00032:22-42","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00032:8-15","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00035:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00036:0-15","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","peekRange":"35-38"}
{"loc":"00037:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00037:51-67","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00038:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00038:51-66","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00040:25-40","target":1,"kind":"use","pretty":"mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceEPNS0_8EndpointIT_EEPNS4_IT0_EE","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00041:22-42","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00041:8-15","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00044:24-31","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00044:9-18","target":1,"kind":"use","pretty":"mozilla::UniquePtr","sym":"T_mozilla::UniquePtr","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00045:0-9","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi","peekRange":"44-45"}
{"loc":"00045:10-17","target":1,"kind":"use","pretty":"int32_t","sym":"T_int32_t","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:106-116","target":1,"kind":"use","pretty":"IPC::Message::NestedLevel::NOT_NESTED","sym":"E_<T_IPC::Message::NestedLevel>_NOT_NESTED","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:123-130","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:132-147","target":1,"kind":"use","pretty":"IPC::Message::PriorityValue::NORMAL_PRIORITY","sym":"E_<T_IPC::Message::PriorityValue>_NORMAL_PRIORITY","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:154-161","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:16-23","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:163-179","target":1,"kind":"use","pretty":"IPC::Message::MessageCompression::COMPRESSION_NONE","sym":"E_<T_IPC::Message::MessageCompression>_COMPRESSION_NONE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:186-193","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:195-210","target":1,"kind":"use","pretty":"IPC::Message::Constructor::NOT_CONSTRUCTOR","sym":"E_<T_IPC::Message::Constructor>_NOT_CONSTRUCTOR","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:217-224","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:226-231","target":1,"kind":"use","pretty":"IPC::Message::Sync::ASYNC","sym":"E_<T_IPC::Message::Sync>_ASYNC","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:238-245","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:247-256","target":1,"kind":"use","pretty":"IPC::Message::Reply::NOT_REPLY","sym":"E_<T_IPC::Message::Reply>_NOT_REPLY","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:25-36","target":1,"kind":"use","pretty":"IPC::Message::IPDLMessage","sym":"_ZN3IPC7Message11IPDLMessageEijjNS0_11HeaderFlagsE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:48-61","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:66-69","target":1,"kind":"use","pretty":"IPC::Message::HeaderFlags::HeaderFlags","sym":"_ZN3IPC7Message11HeaderFlagsC1ENS0_11NestedLevelENS0_13PriorityValueENS0_18MessageCompressionENS0_11ConstructorENS0_4SyncENS0_5ReplyE","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:71-78","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:80-91","target":1,"kind":"use","pretty":"IPC::Message::HeaderFlags","sym":"T_IPC::Message::HeaderFlags","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00047:97-104","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_linux@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_linux@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_macosx@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_windows@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00008:9-47","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00009:9-46","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00013:9-20","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsIFile.h","sym":"FILE_windows@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00024:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00025:0-15","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","peekRange":"24-29"}
{"loc":"00026:14-23","target":1,"kind":"use","pretty":"base::ProcessId","sym":"T_base::ProcessId","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00027:14-23","target":1,"kind":"use","pretty":"base::ProcessId","sym":"T_base::ProcessId","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00028:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00028:51-67","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00029:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00029:51-66","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00031:25-40","target":1,"kind":"use","pretty":"mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceEmmPNS0_8EndpointIT_EEPNS4_IT0_EE","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00032:22-42","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00032:8-15","target":1,"kind":"use","pretty":"mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00001:0","source":1,"syntax":"def,file","pretty":"file __GENERATED__/ipc/ipdl/PTestBasic.cpp","sym":"FILE_windows@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_macosx@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_linux@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp,FILE_android-armv7@__GENERATED__/ipc/ipdl/PTestBasic@2Ecpp"}
{"loc":"00007:9-41","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00008:9-47","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh,FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicParent@2Eh"}
{"loc":"00009:9-46","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh,FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasicChild@2Eh"}
{"loc":"00011:9-32","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCMessageUtils.h","sym":"FILE_ipc/glue/IPCMessageUtils@2Eh"}
{"loc":"00012:9-47","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCMessageUtilsSpecializations.h","sym":"FILE_ipc/glue/IPCMessageUtilsSpecializations@2Eh"}
{"loc":"00013:9-20","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/nsIFile.h","sym":"FILE_windows@__GENERATED__/dist/include/nsIFile@2Eh,FILE_macosx@__GENERATED__/dist/include/nsIFile@2Eh,FILE_linux@__GENERATED__/dist/include/nsIFile@2Eh,FILE_android-armv7@__GENERATED__/dist/include/nsIFile@2Eh"}
{"loc":"00014:9-33","source":1,"syntax":"file,use","pretty":"file ipc/glue/Endpoint.h","sym":"FILE_ipc/glue/Endpoint@2Eh"}
{"loc":"00015:9-45","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolMessageUtils.h","sym":"FILE_ipc/glue/ProtocolMessageUtils@2Eh"}
{"loc":"00016:9-38","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolUtils.h","sym":"FILE_ipc/glue/ProtocolUtils@2Eh"}
{"loc":"00017:9-42","source":1,"syntax":"file,use","pretty":"file ipc/glue/ShmemMessageUtils.h","sym":"FILE_ipc/glue/ShmemMessageUtils@2Eh"}
{"loc":"00018:9-41","source":1,"syntax":"file,use","pretty":"file ipc/glue/TaintingIPCUtils.h","sym":"FILE_ipc/glue/TaintingIPCUtils@2Eh"}
{"loc":"00020:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"20:19-52:0"}
{"loc":"00021:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"21:21-51:0"}
{"loc":"00022:10-20","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest::PTestBasic","sym":"NS_mozilla::_ipdltest::PTestBasic","nestingRange":"22:22-50:0"}
{"loc":"00024:0-8","source":1,"syntax":"type,use","pretty":"type nsresult","sym":"T_nsresult","type":"enum nsresult","typesym":"T_nsresult"}
{"loc":"00025:0-15","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE,_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","nestingRange":"30:0-34:0","type":"enum nsresult (base::ProcessId, base::ProcessId, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00026:14-23","source":1,"syntax":"type,use","pretty":"type base::ProcessId","sym":"T_base::ProcessId","type":"base::ProcessId"}
{"loc":"00026:24-38","source":1,"syntax":"","pretty":"variable aParentDestPid","sym":"V_86052b1c8f905ba9_d1259d65da7e98a3,V_829b7740f87a9861_d1259d65da7e98a3,V_d29b37a6c76a5f4d_d1259d65da7e98a3,V_85f91e7333aa66e3_d1259d65da7e98a3","no_crossref":1,"type":"base::ProcessId"}
{"loc":"00027:14-23","source":1,"syntax":"type,use","pretty":"type base::ProcessId","sym":"T_base::ProcessId","type":"base::ProcessId"}
{"loc":"00027:24-37","source":1,"syntax":"","pretty":"variable aChildDestPid","sym":"V_9ccd2b1c8f905ba9_797885af5cc6dac7,V_98548740f87a9861_797885af5cc6dac7,V_e85447a6c76a5f4d_797885af5cc6dac7,V_9bb22e7333aa66e3_797885af5cc6dac7","no_crossref":1,"type":"base::ProcessId"}
{"loc":"00028:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00028:51-67","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00028:70-77","source":1,"syntax":"","pretty":"variable aParent","sym":"V_bc963b1c8f905ba9_03dd840f0b0d,V_b82d8740f87a9861_03dd840f0b0d,V_092d47a6c76a5f4d_03dd840f0b0d,V_bb8b2e7333aa66e3_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *"}
{"loc":"00029:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00029:51-66","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00029:69-75","source":1,"syntax":"","pretty":"variable aChild","sym":"V_416f3b1c8f905ba9_ae7aa1fe256,V_4de59740f87a9861_ae7aa1fe256,V_9de557a6c76a5f4d_ae7aa1fe256,V_40543e7333aa66e3_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *"}
{"loc":"00031:25-40","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceEmmPNS0_8EndpointIT_EEPNS4_IT0_EE,_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceEiiPNS0_8EndpointIT_EEPNS4_IT0_EE","type":"enum nsresult (const struct mozilla::ipc::PrivateIPDLInterface &, base::ProcessId, base::ProcessId, Endpoint<class mozilla::_ipdltest::PTestBasicParent> *, Endpoint<class mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00032:8-15","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev"}
{"loc":"00032:22-42","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","type":"struct mozilla::ipc::PrivateIPDLInterface","typesym":"T_mozilla::ipc::PrivateIPDLInterface"}
{"loc":"00033:8-22","source":1,"syntax":"","pretty":"variable aParentDestPid","sym":"V_86052b1c8f905ba9_d1259d65da7e98a3,V_829b7740f87a9861_d1259d65da7e98a3,V_d29b37a6c76a5f4d_d1259d65da7e98a3,V_85f91e7333aa66e3_d1259d65da7e98a3","no_crossref":1,"type":"base::ProcessId"}
{"loc":"00033:24-37","source":1,"syntax":"","pretty":"variable aChildDestPid","sym":"V_9ccd2b1c8f905ba9_797885af5cc6dac7,V_98548740f87a9861_797885af5cc6dac7,V_e85447a6c76a5f4d_797885af5cc6dac7,V_9bb22e7333aa66e3_797885af5cc6dac7","no_crossref":1,"type":"base::ProcessId"}
{"loc":"00033:39-46","source":1,"syntax":"","pretty":"variable aParent","sym":"V_bc963b1c8f905ba9_03dd840f0b0d,V_b82d8740f87a9861_03dd840f0b0d,V_092d47a6c76a5f4d_03dd840f0b0d,V_bb8b2e7333aa66e3_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *"}
{"loc":"00033:48-54","source":1,"syntax":"","pretty":"variable aChild","sym":"V_416f3b1c8f905ba9_ae7aa1fe256,V_4de59740f87a9861_ae7aa1fe256,V_9de557a6c76a5f4d_ae7aa1fe256,V_40543e7333aa66e3_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *"}
{"loc":"00035:0-8","source":1,"syntax":"type,use","pretty":"type nsresult","sym":"T_nsresult","type":"enum nsresult","typesym":"T_nsresult"}
{"loc":"00036:0-15","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","nestingRange":"39:0-43:0","type":"enum nsresult (mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00037:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00037:51-67","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00037:70-77","source":1,"syntax":"","pretty":"variable aParent","sym":"V_be5f4c1c8f905ba9_03dd840f0b0d,V_bae5a840f87a9861_03dd840f0b0d,V_0be568a6c76a5f4d_03dd840f0b0d,V_bd444f7333aa66e3_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *"}
{"loc":"00038:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00038:51-66","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00038:69-75","source":1,"syntax":"","pretty":"variable aChild","sym":"V_43285c1c8f905ba9_ae7aa1fe256,V_4faea840f87a9861_ae7aa1fe256,V_9fae68a6c76a5f4d_ae7aa1fe256,V_421d4f7333aa66e3_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *"}
{"loc":"00040:25-40","source":1,"syntax":"function,use","pretty":"function mozilla::ipc::CreateEndpoints","sym":"_ZN7mozilla3ipc15CreateEndpointsERKNS0_20PrivateIPDLInterfaceEPNS0_8EndpointIT_EEPNS4_IT0_EE","type":"enum nsresult (const struct mozilla::ipc::PrivateIPDLInterface &, Endpoint<class mozilla::_ipdltest::PTestBasicParent> *, Endpoint<class mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00041:8-15","source":1,"syntax":"constructor,use","pretty":"constructor mozilla::ipc::PrivateIPDLInterface::PrivateIPDLInterface","sym":"_ZN7mozilla3ipc20PrivateIPDLInterfaceC1Ev"}
{"loc":"00041:22-42","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::PrivateIPDLInterface","sym":"T_mozilla::ipc::PrivateIPDLInterface","type":"struct mozilla::ipc::PrivateIPDLInterface","typesym":"T_mozilla::ipc::PrivateIPDLInterface"}
{"loc":"00042:8-15","source":1,"syntax":"","pretty":"variable aParent","sym":"V_be5f4c1c8f905ba9_03dd840f0b0d,V_bae5a840f87a9861_03dd840f0b0d,V_0be568a6c76a5f4d_03dd840f0b0d,V_bd444f7333aa66e3_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *"}
{"loc":"00042:17-23","source":1,"syntax":"","pretty":"variable aChild","sym":"V_43285c1c8f905ba9_ae7aa1fe256,V_4faea840f87a9861_ae7aa1fe256,V_9fae68a6c76a5f4d_ae7aa1fe256,V_421d4f7333aa66e3_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *"}
{"loc":"00044:9-18","source":1,"syntax":"type,use","pretty":"type mozilla::UniquePtr","sym":"T_mozilla::UniquePtr"}
{"loc":"00044:24-31","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00045:0-9","source":1,"syntax":"def,function","pretty":"function mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi","nestingRange":"46:0-48:0","type":"mozilla::UniquePtr<IPC::Message> (int32_t)"}
{"loc":"00045:10-17","source":1,"syntax":"type,use","pretty":"type int32_t","sym":"T_int32_t","type":"int32_t"}
{"loc":"00045:18-27","source":1,"syntax":"","pretty":"variable routingId","sym":"V_ce4f5d1c8f905ba9_a5670b686a7d773,V_cad5b940f87a9861_a5670b686a7d773,V_1bd579a6c76a5f4d_a5670b686a7d773,V_cd34508333aa66e3_a5670b686a7d773","no_crossref":1,"type":"int32_t"}
{"loc":"00047:16-23","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:25-36","source":1,"syntax":"function,use","pretty":"function IPC::Message::IPDLMessage","sym":"_ZN3IPC7Message11IPDLMessageEijjNS0_11HeaderFlagsE","type":"mozilla::UniquePtr<Message> (int32_t, IPC::Message::msgid_t, uint32_t, class IPC::Message::HeaderFlags)"}
{"loc":"00047:37-46","source":1,"syntax":"","pretty":"variable routingId","sym":"V_ce4f5d1c8f905ba9_a5670b686a7d773,V_cad5b940f87a9861_a5670b686a7d773,V_1bd579a6c76a5f4d_a5670b686a7d773,V_cd34508333aa66e3_a5670b686a7d773","no_crossref":1,"type":"int32_t"}
{"loc":"00047:48-61","source":1,"syntax":"enum,use","pretty":"enum mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00047:66-69","source":1,"syntax":"constructor,use","pretty":"constructor IPC::Message::HeaderFlags::HeaderFlags","sym":"_ZN3IPC7Message11HeaderFlagsC1ENS0_11NestedLevelENS0_13PriorityValueENS0_18MessageCompressionENS0_11ConstructorENS0_4SyncENS0_5ReplyE"}
{"loc":"00047:71-78","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:80-91","source":1,"syntax":"type,use","pretty":"type IPC::Message::HeaderFlags","sym":"T_IPC::Message::HeaderFlags","type":"class IPC::Message::HeaderFlags","typesym":"T_IPC::Message::HeaderFlags"}
{"loc":"00047:97-104","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:106-116","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::NestedLevel::NOT_NESTED","sym":"E_<T_IPC::Message::NestedLevel>_NOT_NESTED","type":"enum IPC::Message::NestedLevel","typesym":"T_IPC::Message::NestedLevel"}
{"loc":"00047:123-130","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:132-147","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::PriorityValue::NORMAL_PRIORITY","sym":"E_<T_IPC::Message::PriorityValue>_NORMAL_PRIORITY","type":"enum IPC::Message::PriorityValue","typesym":"T_IPC::Message::PriorityValue"}
{"loc":"00047:154-161","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:163-179","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::MessageCompression::COMPRESSION_NONE","sym":"E_<T_IPC::Message::MessageCompression>_COMPRESSION_NONE","type":"enum IPC::Message::MessageCompression","typesym":"T_IPC::Message::MessageCompression"}
{"loc":"00047:186-193","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:195-210","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::Constructor::NOT_CONSTRUCTOR","sym":"E_<T_IPC::Message::Constructor>_NOT_CONSTRUCTOR","type":"enum IPC::Message::Constructor","typesym":"T_IPC::Message::Constructor"}
{"loc":"00047:217-224","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:226-231","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::Sync::ASYNC","sym":"E_<T_IPC::Message::Sync>_ASYNC","type":"enum IPC::Message::Sync","typesym":"T_IPC::Message::Sync"}
{"loc":"00047:238-245","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00047:247-256","source":1,"syntax":"enum,use","pretty":"enum IPC::Message::Reply::NOT_REPLY","sym":"E_<T_IPC::Message::Reply>_NOT_REPLY","type":"enum IPC::Message::Reply","typesym":"T_IPC::Message::Reply"}
{"loc":"00036:0-15","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","kind":"function","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":[]}
{"loc":"00025:0-15","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","kind":"function","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":[]}
{"loc":"00025:0-15","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","kind":"function","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":[]}
{"loc":"00045:0-9","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi","kind":"function","implKind":"","sizeBytes":null,"supers":[],"methods":[],"fields":[],"overrides":[],"props":[]}
