#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

rm -f $INDEX_ROOT/searchfox

mkdir -p $BLAME_ROOT
git init $BLAME_ROOT
$MOZSEARCH_PATH/tools/target/release/build-blame $GIT_ROOT $BLAME_ROOT

# Link over the fake metadata and test file information as well.
ln -s -f $CONFIG_REPO/searchfox/metadata/code-coverage-report.json $INDEX_ROOT