//
// Automatically generated by ipdlc.
// Edit at your own risk
//


#include "mozilla/_ipdltest/PTestBasicChild.h"
#include "mozilla/ProfilerLabels.h"
#include "mozilla/_ipdltest/TestBasicChild.h"


#include "ipc/IPCMessageUtils.h"
#include "ipc/IPCMessageUtilsSpecializations.h"
#include "nsIFile.h"
#include "mozilla/ipc/Endpoint.h"
#include "mozilla/ipc/ProtocolMessageUtils.h"
#include "mozilla/ipc/ProtocolUtils.h"
#include "mozilla/ipc/ShmemMessageUtils.h"
#include "mozilla/ipc/TaintingIPCUtils.h"

namespace mozilla {
namespace _ipdltest {


auto PTestBasicChild::ProcessingError(
        Result aCode,
        const char* aReason) -> void
{
}

auto PTestBasicChild::ShouldContinueFromReplyTimeout() -> bool
{
    return true;
}

MOZ_IMPLICIT PTestBasicChild::PTestBasicChild() :
    mozilla::ipc::IToplevelProtocol("PTestBasicChild", kProtocolId, mozilla::ipc::ChildSide)
{
    MOZ_COUNT_CTOR(PTestBasicChild);
}

PTestBasicChild::~PTestBasicChild()
{
    MOZ_COUNT_DTOR(PTestBasicChild);
}

auto PTestBasicChild::ActorAlloc() -> void
{
    AddRef();
}

auto PTestBasicChild::ActorDealloc() -> void
{
    Release();
}

auto PTestBasicChild::ManagedProtocolIds() const -> mozilla::Span<mozilla::ipc::ProtocolId const>
{
    return {};
}

auto PTestBasicChild::GetManagedActors(mozilla::ipc::ProtocolId aProtocol) -> UntypedManagedContainer*
{
    switch (aProtocol) {
    default:
        return nullptr;
    }
}

auto PTestBasicChild::DeallocManagee(
        mozilla::ipc::ProtocolId aProtocolId,
        IProtocol* aListener) -> void
{
    FatalError("unreached");
    return;
}

auto PTestBasicChild::OnMessageReceived(const Message& msg__) -> PTestBasicChild::Result
{
    if (!CanSend()) {
        if (mozilla::ipc::LoggingEnabledFor("PTestBasic", mozilla::ipc::ChildSide)) {
            mozilla::ipc::LogMessageForProtocol(
                "PTestBasicChild",
                this->ToplevelProtocol()->OtherPidMaybeInvalid(),
                "Ignored message for dead actor",
                (&(msg__))->type(),
                mozilla::ipc::MessageDirection::eSending);
        }
        return MsgProcessed;

    }
    switch (msg__.type()) {
    case PTestBasic::Msg_Hello__ID:
        {
            if (mozilla::ipc::LoggingEnabledFor("PTestBasic", mozilla::ipc::ChildSide)) {
                mozilla::ipc::LogMessageForProtocol(
                    "PTestBasicChild",
                    this->ToplevelProtocol()->OtherPidMaybeInvalid(),
                    "Received ",
                    (&(msg__))->type(),
                    mozilla::ipc::MessageDirection::eReceiving);
            }
            AUTO_PROFILER_LABEL("PTestBasic::Msg_Hello", OTHER);

            mozilla::ipc::IPCResult __ok = (static_cast<TestBasicChild*>(this))->RecvHello();
            if ((!(__ok))) {
                mozilla::ipc::ProtocolErrorBreakpoint("Handler returned error code!");
                // Error handled in mozilla::ipc::IPCResult
                return MsgProcessingError;
            }

            return MsgProcessed;
        }
    default:
        return MsgNotKnown;
    case SHMEM_CREATED_MESSAGE_TYPE:
        {
            if (!ShmemCreated(msg__)) {
                return MsgPayloadError;
            }
            return MsgProcessed;
        }
    case SHMEM_DESTROYED_MESSAGE_TYPE:
        {
            if (!ShmemDestroyed(msg__)) {
                return MsgPayloadError;
            }
            return MsgProcessed;
        }
    }
}

auto PTestBasicChild::OnMessageReceived(
        const Message& msg__,
        UniquePtr<Message>& reply__) -> PTestBasicChild::Result
{
    if (!CanSend()) {
        return MsgDropped;

    }
    MOZ_ASSERT_UNREACHABLE("message protocol not supported");
    return MsgNotKnown;
}



} // namespace _ipdltest
} // namespace mozilla
namespace IPC {
auto ParamTraits<::mozilla::_ipdltest::PTestBasicChild*>::Write(
        IPC::MessageWriter* aWriter,
        const paramType& aVar) -> void
{
    IPC::WriteParam(aWriter, static_cast<mozilla::ipc::IProtocol*>(aVar));
    // Sentinel = 'PTestBasic'
    (aWriter)->WriteSentinel(343868371);
}

auto ParamTraits<::mozilla::_ipdltest::PTestBasicChild*>::Read(IPC::MessageReader* aReader) -> IPC::ReadResult<paramType>
{
    auto maybe__actor = IPC::ReadParam<mozilla::ipc::IProtocol*>(aReader);
    if (!maybe__actor) {
        aReader->FatalError("Error deserializing managed PTestBasic actor");
        return {};

    }
    auto& actor = *maybe__actor;
    // Sentinel = 'PTestBasic'
    if ((!((aReader)->ReadSentinel(343868371)))) {
        mozilla::ipc::SentinelReadError("Error deserializing managed PTestBasic actor");
        return {};
    }

    if (actor && actor->GetProtocolId() != PTestBasicMsgStart) {
        aReader->FatalError("Unexpected actor type (expected PTestBasic)");

        return {};
    }
    return static_cast<::mozilla::_ipdltest::PTestBasicChild*>(actor);
}

} // namespace IPC
