#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

mkdir -p $OBJDIR

# Add the special clang flags.
$MOZSEARCH_PATH/scripts/indexer-setup.py >> $INDEX_ROOT/config
source $INDEX_ROOT/config

cd $INDEX_ROOT/files
for f in *.cpp
do
  $CXX $f -std=c++14 -c -o $OBJDIR/${f%%.cpp}.o -Wall
done
