#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

# We are passed in the name of the helper script to invoke to run each check.
# The syntax is:
#   "$@" <searchfox user exposed path> <canonical symbol name as found in data-symbols>
#
# Note that "$@" is used because the command is expected to have curried
# arguments.

### Rust
## direct source
"$@" "simple.rs" "simple::Loader"

## dependency
"$@" "test_rust_dependency/src/lib.rs" "test_rust_dependency::MyType"

## generated
"$@" "__GENERATED__/__RUST_BUILD_SCRIPT__/files/generated.rs" "simple::build_time_generated::GeneratedType"

### C++
## Include statement
"$@" "big_cpp.cpp" "FILE_big_header@2Eh"

## File definition. These are zero-length symbols and so won't actually
## show up in any data-symbols attribute in the HTML. We still want
## to check that it ends up in the analysis data though.
CHECK_SKIP_DATA_SYMBOL=1 "$@" "big_header.h" "FILE_big_header@2Eh"
