#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# Note that this symlink potentially creates edge-cases related to logic that
# canonicalizes paths and thereby resolves symlinks.  So far this has only been
# an issue with ipdl-analyze and we addressed that by running the FILES_ROOT
# through `realpath`.  If we see more problems like this, that's probably the
# most practical course of action, because usually the scripts just want to have
# a prefix they can strip off and so it's just a case of making sure the prefix
# is consistent.
ln -s -f $CONFIG_REPO/tests/files $INDEX_ROOT

# Link over the fake metadata and test file information as well.
ln -s -f $CONFIG_REPO/tests/metadata/bugzilla-components.json $INDEX_ROOT
ln -s -f $CONFIG_REPO/tests/metadata/test-info-all-tests.json $INDEX_ROOT
ln -s -f $CONFIG_REPO/tests/metadata/wpt-manifest.json $INDEX_ROOT
ln -s -f $CONFIG_REPO/tests/metadata/wpt-mozilla-manifest.json $INDEX_ROOT
ln -s -f $CONFIG_REPO/tests/metadata/wpt-metadata-summary.json $INDEX_ROOT
ln -s -f $CONFIG_REPO/tests/metadata/code-coverage-report.json $INDEX_ROOT
ln -s -f $CONFIG_REPO/tests/metadata/test.chrome-map.json $INDEX_ROOT
ln -s -f $CONFIG_REPO/tests/metadata/test2.chrome-map.json $INDEX_ROOT
