#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

rm -f $INDEX_ROOT/tests
ln -s -f $CONFIG_REPO/tests/files $INDEX_ROOT
