/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JavaTest {
    @Test void someJavaLibraryMethodReturnsTrue() {
        JavaLibrary classUnderTest = new JavaLibrary();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void someKotlinLibraryMethodReturnsTrue() {
        KotlinLibrary classUnderTest = new KotlinLibrary();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
