[term.C]
alias = "context"

[term.context]
[[term.context.group.display]]
command = "show-html"
args.context = "$0"

# The default term is what gets applied to things without a term.  It can also
# be explicitly referenced by other terms.
[term.default]
[[term.default.expand]]
term = "file"
[[term.default.expand]]
term = "idprefix"
[[term.default.expand]]
term = "text"

[term.file]
[[term.file.group.file-search]]
command = "search-files"
args.positional = "$0"

[term.id]
# We can't do this and `idprefix` in the same command and it's not clear it's
# worth the effort to support both simultaneously.
conflicts = ["idprefix"]
[[term.id.group.semantic-search]]
command = "search-identifiers"
args.positional = "$0"
args.exact_match = true

[term.idprefix]
[[term.idprefix.group.semantic-search]]
command = "search-identifiers"
args.positional = "$0"
args.exact_match = false


[term.pathre]
[[term.pathre.group.file-search]]
command = "search-files"
args.pathre = "$0"
[[term.pathre.group.semantic-search]]
command = "filter-crossref"
args.pathre = "$0"
[[term.pathre.group.text-search]]
command = "search-text"
args.pathre = "$0"

[term.p]
alias = "path"

[term.path]
[[term.path.expand]]
term = "pathre"
transforms = ["path_glob"]

[term.re]
[[term.re.group.text-search]]
command = "search-text"
args.re = "$0"

[term.sym]
alias = "symbol"

[term.symbol]
[[term.symbol.group.semantic-search]]
command = "search-identifiers"
args.add_sym = "$0"

[term.text]
[[term.text.expand]]
term = "re"
transforms = ["regexp_escape"]

[group.file-search]
output = "file-search"
junction = "compile"

[group.semantic-search]
output = "semantic-search"
junction = "compile"

[group.text-search]
output = "text-search"
junction = "compile"

[junction.compile]
command = "compile-results"
output = "compiled"
next = "display"

[group.display]
output = "result"
[[group.display.commands]]
command = "show-html"
