/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sample

import kotlin.test.Test
import kotlin.test.assertTrue

class KotlinTest {
    @Test fun someJavaLibraryMethodReturnsTrue() {
        val classUnderTest = JavaLibrary()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
    @Test fun someKotlinLibraryMethodReturnsTrue() {
        val classUnderTest = KotlinLibrary()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
