#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

ANALYSIS_FILES_PATH=$1

# Find the files to replace aliases.
#
# NOTE: analysis-files.list is not useful for this purpose; it only exists for
#       gecko trees and only reflects the analysis files present after running
#       process-tc-artifacts.sh for all platforms, not new analysis files
#       generated by mkindex.sh. (We leave it around on disk to help debug
#       anything that went wrong.)
cd $INDEX_ROOT/analysis
find . -type f | cut -c 3- > $ANALYSIS_FILES_PATH
cd -
