#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

DIAGS_DIR=$INDEX_ROOT/diags/replace-aliases
mkdir -p $DIAGS_DIR
# clean up the directory since in the VM this can persist.
rm -f $DIAGS_DIR/*

JOBLOG_PATH=${DIAGS_DIR}/replace-aliases.joblog
TMPDIR_PATH=${DIAGS_DIR}

# Find the files to replace aliases.
#
# NOTE: analysis-files.list is not useful for this purpose; it only exists for
#       gecko trees and only reflects the analysis files present after running
#       process-tc-artifacts.sh for all platforms, not new analysis files
#       generated by mkindex.sh. (We leave it around on disk to help debug
#       anything that went wrong.)
cd $INDEX_ROOT/analysis
find . -type f | cut -c 3- > ${TMPDIR:-/tmp}/files
cd -

parallel --jobs 8 --pipepart -a ${TMPDIR:-/tmp}/files --files --joblog $JOBLOG_PATH --tmpdir $TMPDIR_PATH \
    --block -1 --halt 2 \
    "$MOZSEARCH_PATH/scripts/replace-aliases.py $INDEX_ROOT/analysis $INDEX_ROOT/aliases/url-map.json"
