{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_efbf4ce848c2a2e1"}
{"loc":"00009:9-31","target":1,"kind":"use","pretty":"mfbt/Attributes.h","sym":"FILE_mfbt/Attributes@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00011:9-27","target":1,"kind":"use","pretty":"mfbt/RefPtr.h","sym":"FILE_mfbt/RefPtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00012:9-21","target":1,"kind":"use","pretty":"xpcom/string/nsString.h","sym":"FILE_xpcom/string/nsString@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00013:9-21","target":1,"kind":"use","pretty":"xpcom/ds/nsTArray.h","sym":"FILE_xpcom/ds/nsTArray@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00014:9-25","target":1,"kind":"use","pretty":"xpcom/ds/nsTHashtable.h","sym":"FILE_xpcom/ds/nsTHashtable@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00015:9-31","target":1,"kind":"use","pretty":"xpcom/threads/MozPromise.h","sym":"FILE_xpcom/threads/MozPromise@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00016:9-42","target":1,"kind":"use","pretty":"mfbt/OperatorNewExtensions.h","sym":"FILE_mfbt/OperatorNewExtensions@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00017:9-30","target":1,"kind":"use","pretty":"mfbt/UniquePtr.h","sym":"FILE_mfbt/UniquePtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00018:9-32","target":1,"kind":"use","pretty":"ipc/glue/ByteBuf.h","sym":"FILE_ipc/glue/ByteBuf@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00019:9-39","target":1,"kind":"use","pretty":"ipc/glue/FileDescriptor.h","sym":"FILE_ipc/glue/FileDescriptor@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00020:9-36","target":1,"kind":"use","pretty":"ipc/glue/IPCForwards.h","sym":"FILE_ipc/glue/IPCForwards@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00021:9-30","target":1,"kind":"use","pretty":"ipc/glue/Shmem.h","sym":"FILE_ipc/glue/Shmem@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00023:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00024:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00025:6-22","target":1,"kind":"forward","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00028:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00029:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00030:6-21","target":1,"kind":"forward","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00037:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00038:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00039:10-20","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic","sym":"NS_mozilla::_ipdltest::PTestBasic"}
{"loc":"00041:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00042:0-15","target":1,"kind":"decl","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE","peekRange":"41-46"}
{"loc":"00043:22-38","target":1,"kind":"use","pretty":"mozilla::ipc::EndpointProcInfo","sym":"T_mozilla::ipc::EndpointProcInfo","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00044:22-38","target":1,"kind":"use","pretty":"mozilla::ipc::EndpointProcInfo","sym":"T_mozilla::ipc::EndpointProcInfo","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00045:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00045:53-69","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00046:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00046:53-68","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE"}
{"loc":"00048:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00049:0-15","target":1,"kind":"decl","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","peekRange":"48-51"}
{"loc":"00050:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00050:53-69","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00051:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00051:53-68","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00053:5-16","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::MessageType","sym":"T_mozilla::_ipdltest::PTestBasic::MessageType","peekRange":"53-53"}
{"loc":"00054:22-40","target":1,"kind":"use","pretty":"IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","context":"mozilla::_ipdltest::PTestBasic::MessageType","contextsym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00054:4-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicStart","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicStart","context":"mozilla::_ipdltest::PTestBasic::MessageType","contextsym":"T_mozilla::_ipdltest::PTestBasic::MessageType","peekRange":"54-54"}
{"loc":"00055:4-17","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","context":"mozilla::_ipdltest::PTestBasic::MessageType","contextsym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00056:4-17","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicEnd","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicEnd","context":"mozilla::_ipdltest::PTestBasic::MessageType","contextsym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00059:24-31","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00059:9-18","target":1,"kind":"use","pretty":"mozilla::UniquePtr","sym":"TA_mozilla::UniquePtr","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00060:0-9","target":1,"kind":"decl","pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl","peekRange":"59-60"}
{"loc":"00060:15-22","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00060:24-33","target":1,"kind":"use","pretty":"IPC::Message::routeid_t","sym":"TA_IPC::Message::routeid_t","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_e54e62b42202e917"}
{"loc":"00009:9-31","target":1,"kind":"use","pretty":"mfbt/Attributes.h","sym":"FILE_mfbt/Attributes@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00011:9-27","target":1,"kind":"use","pretty":"mfbt/RefPtr.h","sym":"FILE_mfbt/RefPtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00012:9-21","target":1,"kind":"use","pretty":"xpcom/string/nsString.h","sym":"FILE_xpcom/string/nsString@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00013:9-21","target":1,"kind":"use","pretty":"xpcom/ds/nsTArray.h","sym":"FILE_xpcom/ds/nsTArray@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00014:9-25","target":1,"kind":"use","pretty":"xpcom/ds/nsTHashtable.h","sym":"FILE_xpcom/ds/nsTHashtable@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00015:9-31","target":1,"kind":"use","pretty":"xpcom/threads/MozPromise.h","sym":"FILE_xpcom/threads/MozPromise@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00016:9-42","target":1,"kind":"use","pretty":"mfbt/OperatorNewExtensions.h","sym":"FILE_mfbt/OperatorNewExtensions@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00017:9-30","target":1,"kind":"use","pretty":"mfbt/UniquePtr.h","sym":"FILE_mfbt/UniquePtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00018:9-32","target":1,"kind":"use","pretty":"ipc/glue/ByteBuf.h","sym":"FILE_ipc/glue/ByteBuf@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00019:9-39","target":1,"kind":"use","pretty":"ipc/glue/FileDescriptor.h","sym":"FILE_ipc/glue/FileDescriptor@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00020:9-36","target":1,"kind":"use","pretty":"ipc/glue/IPCForwards.h","sym":"FILE_ipc/glue/IPCForwards@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00021:9-30","target":1,"kind":"use","pretty":"ipc/glue/Shmem.h","sym":"FILE_ipc/glue/Shmem@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_f24c7609783a9c5"}
{"loc":"00009:9-31","target":1,"kind":"use","pretty":"mfbt/Attributes.h","sym":"FILE_mfbt/Attributes@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00011:9-27","target":1,"kind":"use","pretty":"mfbt/RefPtr.h","sym":"FILE_mfbt/RefPtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00012:9-21","target":1,"kind":"use","pretty":"xpcom/string/nsString.h","sym":"FILE_xpcom/string/nsString@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00013:9-21","target":1,"kind":"use","pretty":"xpcom/ds/nsTArray.h","sym":"FILE_xpcom/ds/nsTArray@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00014:9-25","target":1,"kind":"use","pretty":"xpcom/ds/nsTHashtable.h","sym":"FILE_xpcom/ds/nsTHashtable@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00015:9-31","target":1,"kind":"use","pretty":"xpcom/threads/MozPromise.h","sym":"FILE_xpcom/threads/MozPromise@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00016:9-42","target":1,"kind":"use","pretty":"mfbt/OperatorNewExtensions.h","sym":"FILE_mfbt/OperatorNewExtensions@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00017:9-30","target":1,"kind":"use","pretty":"mfbt/UniquePtr.h","sym":"FILE_mfbt/UniquePtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00018:9-32","target":1,"kind":"use","pretty":"ipc/glue/ByteBuf.h","sym":"FILE_ipc/glue/ByteBuf@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00019:9-39","target":1,"kind":"use","pretty":"ipc/glue/FileDescriptor.h","sym":"FILE_ipc/glue/FileDescriptor@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00020:9-36","target":1,"kind":"use","pretty":"ipc/glue/IPCForwards.h","sym":"FILE_ipc/glue/IPCForwards@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00021:9-30","target":1,"kind":"use","pretty":"ipc/glue/Shmem.h","sym":"FILE_ipc/glue/Shmem@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00059:24-31","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00059:9-18","target":1,"kind":"use","pretty":"mozilla::UniquePtr","sym":"TA_mozilla::UniquePtr","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00060:0-9","target":1,"kind":"decl","pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx","peekRange":"59-60"}
{"loc":"00060:15-22","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00060:24-33","target":1,"kind":"use","pretty":"IPC::Message::routeid_t","sym":"TA_IPC::Message::routeid_t","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_f0c33f39f43a0827"}
{"loc":"00009:9-31","target":1,"kind":"use","pretty":"mfbt/Attributes.h","sym":"FILE_mfbt/Attributes@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00011:9-27","target":1,"kind":"use","pretty":"mfbt/RefPtr.h","sym":"FILE_mfbt/RefPtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00012:9-21","target":1,"kind":"use","pretty":"xpcom/string/nsString.h","sym":"FILE_xpcom/string/nsString@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00013:9-21","target":1,"kind":"use","pretty":"xpcom/ds/nsTArray.h","sym":"FILE_xpcom/ds/nsTArray@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00014:9-25","target":1,"kind":"use","pretty":"xpcom/ds/nsTHashtable.h","sym":"FILE_xpcom/ds/nsTHashtable@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00015:9-31","target":1,"kind":"use","pretty":"xpcom/threads/MozPromise.h","sym":"FILE_xpcom/threads/MozPromise@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00016:9-42","target":1,"kind":"use","pretty":"mfbt/OperatorNewExtensions.h","sym":"FILE_mfbt/OperatorNewExtensions@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00017:9-30","target":1,"kind":"use","pretty":"mfbt/UniquePtr.h","sym":"FILE_mfbt/UniquePtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00018:9-32","target":1,"kind":"use","pretty":"ipc/glue/ByteBuf.h","sym":"FILE_ipc/glue/ByteBuf@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00019:9-39","target":1,"kind":"use","pretty":"ipc/glue/FileDescriptor.h","sym":"FILE_ipc/glue/FileDescriptor@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00020:9-36","target":1,"kind":"use","pretty":"ipc/glue/IPCForwards.h","sym":"FILE_ipc/glue/IPCForwards@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00021:9-30","target":1,"kind":"use","pretty":"ipc/glue/Shmem.h","sym":"FILE_ipc/glue/Shmem@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_995d254a6dc68209"}
{"loc":"00009:9-31","target":1,"kind":"use","pretty":"mfbt/Attributes.h","sym":"FILE_mfbt/Attributes@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00011:9-27","target":1,"kind":"use","pretty":"mfbt/RefPtr.h","sym":"FILE_mfbt/RefPtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00012:9-21","target":1,"kind":"use","pretty":"xpcom/string/nsString.h","sym":"FILE_xpcom/string/nsString@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00013:9-21","target":1,"kind":"use","pretty":"xpcom/ds/nsTArray.h","sym":"FILE_xpcom/ds/nsTArray@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00014:9-25","target":1,"kind":"use","pretty":"xpcom/ds/nsTHashtable.h","sym":"FILE_xpcom/ds/nsTHashtable@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00015:9-31","target":1,"kind":"use","pretty":"xpcom/threads/MozPromise.h","sym":"FILE_xpcom/threads/MozPromise@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00016:9-42","target":1,"kind":"use","pretty":"mfbt/OperatorNewExtensions.h","sym":"FILE_mfbt/OperatorNewExtensions@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00017:9-30","target":1,"kind":"use","pretty":"mfbt/UniquePtr.h","sym":"FILE_mfbt/UniquePtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00018:9-32","target":1,"kind":"use","pretty":"ipc/glue/ByteBuf.h","sym":"FILE_ipc/glue/ByteBuf@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00019:9-39","target":1,"kind":"use","pretty":"ipc/glue/FileDescriptor.h","sym":"FILE_ipc/glue/FileDescriptor@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00020:9-36","target":1,"kind":"use","pretty":"ipc/glue/IPCForwards.h","sym":"FILE_ipc/glue/IPCForwards@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00021:9-30","target":1,"kind":"use","pretty":"ipc/glue/Shmem.h","sym":"FILE_ipc/glue/Shmem@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_cfcbdc19ecd98941"}
{"loc":"00009:9-31","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/Attributes.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/Attributes@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00011:9-27","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/RefPtr.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/RefPtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00012:9-21","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsString.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/nsString@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00013:9-21","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsTArray.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/nsTArray@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00014:9-25","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsTHashtable.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/nsTHashtable@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00015:9-31","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/MozPromise.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/MozPromise@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00016:9-42","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/OperatorNewExtensions.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/OperatorNewExtensions@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00017:9-30","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/UniquePtr.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/UniquePtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00018:9-32","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/ByteBuf.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/ByteBuf@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00019:9-39","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/FileDescriptor.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/FileDescriptor@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00020:9-36","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/IPCForwards.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/IPCForwards@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00021:9-30","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/Shmem.h","sym":"FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/Shmem@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_c56daa9a99ff4493"}
{"loc":"00009:9-31","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/Attributes.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/Attributes@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00011:9-27","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/RefPtr.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/RefPtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00012:9-21","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsString.h","sym":"FILE_win64@__GENERATED__/dist/include/nsString@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00013:9-21","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsTArray.h","sym":"FILE_win64@__GENERATED__/dist/include/nsTArray@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00014:9-25","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/nsTHashtable.h","sym":"FILE_win64@__GENERATED__/dist/include/nsTHashtable@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00015:9-31","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/MozPromise.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/MozPromise@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00016:9-42","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/OperatorNewExtensions.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/OperatorNewExtensions@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00017:9-30","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/UniquePtr.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/UniquePtr@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00018:9-32","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/ByteBuf.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/ByteBuf@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00019:9-39","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/FileDescriptor.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/FileDescriptor@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00020:9-36","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/IPCForwards.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/IPCForwards@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00021:9-30","target":1,"kind":"use","pretty":"__GENERATED__/dist/include/mozilla/ipc/Shmem.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/Shmem@2Eh","context":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","contextsym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00001:0","source":1,"syntax":"def,file","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","source":1,"syntax":"def,macro","pretty":"macro PTestBasic_h","sym":"M_c56daa9a99ff4493,M_cfcbdc19ecd98941,M_995d254a6dc68209,M_f0c33f39f43a0827,M_f24c7609783a9c5,M_e54e62b42202e917,M_efbf4ce848c2a2e1"}
{"loc":"00009:9-31","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/Attributes.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/Attributes@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/Attributes@2Eh"}
{"loc":"00009:9-31","source":1,"syntax":"file,use","pretty":"file mfbt/Attributes.h","sym":"FILE_mfbt/Attributes@2Eh"}
{"loc":"00010:9-28","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_win64@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_win64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_macosx64@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_macosx64-aarch64@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_macosx64-aarch64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_linux64@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_linux64-opt@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh"}
{"loc":"00011:9-27","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/RefPtr.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/RefPtr@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/RefPtr@2Eh"}
{"loc":"00011:9-27","source":1,"syntax":"file,use","pretty":"file mfbt/RefPtr.h","sym":"FILE_mfbt/RefPtr@2Eh"}
{"loc":"00012:9-21","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/nsString.h","sym":"FILE_win64@__GENERATED__/dist/include/nsString@2Eh,FILE_win64-opt@__GENERATED__/dist/include/nsString@2Eh"}
{"loc":"00012:9-21","source":1,"syntax":"file,use","pretty":"file xpcom/string/nsString.h","sym":"FILE_xpcom/string/nsString@2Eh"}
{"loc":"00013:9-21","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/nsTArray.h","sym":"FILE_win64@__GENERATED__/dist/include/nsTArray@2Eh,FILE_win64-opt@__GENERATED__/dist/include/nsTArray@2Eh"}
{"loc":"00013:9-21","source":1,"syntax":"file,use","pretty":"file xpcom/ds/nsTArray.h","sym":"FILE_xpcom/ds/nsTArray@2Eh"}
{"loc":"00014:9-25","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/nsTHashtable.h","sym":"FILE_win64@__GENERATED__/dist/include/nsTHashtable@2Eh,FILE_win64-opt@__GENERATED__/dist/include/nsTHashtable@2Eh"}
{"loc":"00014:9-25","source":1,"syntax":"file,use","pretty":"file xpcom/ds/nsTHashtable.h","sym":"FILE_xpcom/ds/nsTHashtable@2Eh"}
{"loc":"00015:9-31","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/MozPromise.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/MozPromise@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/MozPromise@2Eh"}
{"loc":"00015:9-31","source":1,"syntax":"file,use","pretty":"file xpcom/threads/MozPromise.h","sym":"FILE_xpcom/threads/MozPromise@2Eh"}
{"loc":"00016:9-42","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/OperatorNewExtensions.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/OperatorNewExtensions@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/OperatorNewExtensions@2Eh"}
{"loc":"00016:9-42","source":1,"syntax":"file,use","pretty":"file mfbt/OperatorNewExtensions.h","sym":"FILE_mfbt/OperatorNewExtensions@2Eh"}
{"loc":"00017:9-30","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/UniquePtr.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/UniquePtr@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/UniquePtr@2Eh"}
{"loc":"00017:9-30","source":1,"syntax":"file,use","pretty":"file mfbt/UniquePtr.h","sym":"FILE_mfbt/UniquePtr@2Eh"}
{"loc":"00018:9-32","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/ByteBuf.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/ByteBuf@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/ByteBuf@2Eh"}
{"loc":"00018:9-32","source":1,"syntax":"file,use","pretty":"file ipc/glue/ByteBuf.h","sym":"FILE_ipc/glue/ByteBuf@2Eh"}
{"loc":"00019:9-39","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/FileDescriptor.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/FileDescriptor@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/FileDescriptor@2Eh"}
{"loc":"00019:9-39","source":1,"syntax":"file,use","pretty":"file ipc/glue/FileDescriptor.h","sym":"FILE_ipc/glue/FileDescriptor@2Eh"}
{"loc":"00020:9-36","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/IPCForwards.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/IPCForwards@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/IPCForwards@2Eh"}
{"loc":"00020:9-36","source":1,"syntax":"file,use","pretty":"file ipc/glue/IPCForwards.h","sym":"FILE_ipc/glue/IPCForwards@2Eh"}
{"loc":"00021:9-30","source":1,"syntax":"file,use","pretty":"file __GENERATED__/dist/include/mozilla/ipc/Shmem.h","sym":"FILE_win64@__GENERATED__/dist/include/mozilla/ipc/Shmem@2Eh,FILE_win64-opt@__GENERATED__/dist/include/mozilla/ipc/Shmem@2Eh"}
{"loc":"00021:9-30","source":1,"syntax":"file,use","pretty":"file ipc/glue/Shmem.h","sym":"FILE_ipc/glue/Shmem@2Eh"}
{"loc":"00023:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"23:19-27:0"}
{"loc":"00024:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"24:21-26:0"}
{"loc":"00025:6-22","source":1,"syntax":"forward,type","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00028:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"28:19-32:0"}
{"loc":"00029:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"29:21-31:0"}
{"loc":"00030:6-21","source":1,"syntax":"forward,type","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00037:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"37:19-66:0"}
{"loc":"00038:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"38:21-65:0"}
{"loc":"00039:10-20","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest::PTestBasic","sym":"NS_mozilla::_ipdltest::PTestBasic","nestingRange":"39:22-64:0"}
{"loc":"00041:0-8","source":1,"syntax":"type,use","pretty":"type nsresult","sym":"T_nsresult","type":"enum nsresult","typesym":"T_nsresult"}
{"loc":"00042:0-15","source":1,"syntax":"decl,function","pretty":"function mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsENS_3ipc16EndpointProcInfoES3_PNS2_8EndpointINS0_16PTestBasicParentEEEPNS4_INS0_15PTestBasicChildEEE","type":"nsresult (mozilla::ipc::EndpointProcInfo, mozilla::ipc::EndpointProcInfo, mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *, mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00043:22-38","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::EndpointProcInfo","sym":"T_mozilla::ipc::EndpointProcInfo","type":"struct mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00043:39-54","source":1,"syntax":"","pretty":"variable aParentDestInfo","sym":"V_0f1db4fdec2f4e16_c05dff1385dd6cb8,V_09c8bcbc0a75ca7a_c05dff1385dd6cb8,V_dc8b3fe2ba706359_c05dff1385dd6cb8,V_30ee0a2124d0592c_c05dff1385dd6cb8,V_32a76ad99741efeb_c05dff1385dd6cb8,V_230a940bb642265a_c05dff1385dd6cb8,V_2dbaaa7661dbf63e_c05dff1385dd6cb8","no_crossref":1,"type":"mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00044:22-38","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::EndpointProcInfo","sym":"T_mozilla::ipc::EndpointProcInfo","type":"struct mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00044:39-53","source":1,"syntax":"","pretty":"variable aChildDestInfo","sym":"V_15e5c4fdec2f4e16_6c9b56545850b521,V_1f81ccbc0a75ca7a_6c9b56545850b521,V_e2544fe2ba706359_6c9b56545850b521,V_46a71a2124d0592c_6c9b56545850b521,V_48607ad99741efeb_6c9b56545850b521,V_39c2a40bb642265a_6c9b56545850b521,V_3383ba7661dbf63e_6c9b56545850b521","no_crossref":1,"type":"mozilla::ipc::EndpointProcInfo","typesym":"T_mozilla::ipc::EndpointProcInfo"}
{"loc":"00045:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00045:53-69","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00045:72-79","source":1,"syntax":"","pretty":"variable aParent","sym":"V_f2bec4fdec2f4e16_03dd840f0b0d,V_fc5accbc0a75ca7a_03dd840f0b0d,V_c02d4fe2ba706359_03dd840f0b0d,V_24702a2124d0592c_03dd840f0b0d,V_26397ad99741efeb_03dd840f0b0d,V_179ba40bb642265a_03dd840f0b0d,V_115cba7661dbf63e_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00046:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00046:53-68","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00046:71-77","source":1,"syntax":"","pretty":"variable aChild","sym":"V_f877d4fdec2f4e16_ae7aa1fe256,V_f223dcbc0a75ca7a_ae7aa1fe256,V_c6e55fe2ba706359_ae7aa1fe256,V_2a392a2124d0592c_ae7aa1fe256,V_2cf18ad99741efeb_ae7aa1fe256,V_1d54b40bb642265a_ae7aa1fe256,V_1715ca7661dbf63e_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00048:0-8","source":1,"syntax":"type,use","pretty":"type nsresult","sym":"T_nsresult","type":"enum nsresult","typesym":"T_nsresult"}
{"loc":"00049:0-15","source":1,"syntax":"decl,function","pretty":"function mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","type":"nsresult (mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *, mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00050:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00050:53-69","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00050:72-79","source":1,"syntax":"","pretty":"variable aParent","sym":"V_bc54c5fdec2f4e16_03dd840f0b0d,V_b600cdbc0a75ca7a_03dd840f0b0d,V_8ac240f2ba706359_03dd840f0b0d,V_ed161b2124d0592c_03dd840f0b0d,V_efde6bd99741efeb_03dd840f0b0d,V_d041a50bb642265a_03dd840f0b0d,V_daf1bb7661dbf63e_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicParent> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00051:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00051:53-68","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00051:71-77","source":1,"syntax":"","pretty":"variable aChild","sym":"V_b22dc5fdec2f4e16_ae7aa1fe256,V_bcc8cdbc0a75ca7a_ae7aa1fe256,V_809b40f2ba706359_ae7aa1fe256,V_e3ee1b2124d0592c_ae7aa1fe256,V_e5a77bd99741efeb_ae7aa1fe256,V_d60aa50bb642265a_ae7aa1fe256,V_d0cabb7661dbf63e_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint< ::mozilla::_ipdltest::PTestBasicChild> *","typesym":"T_mozilla::ipc::Endpoint"}
{"loc":"00053:5-16","source":1,"syntax":"def,type","pretty":"type mozilla::_ipdltest::PTestBasic::MessageType","sym":"T_mozilla::_ipdltest::PTestBasic::MessageType","nestingRange":"53:17-57:0"}
{"loc":"00054:4-19","source":1,"syntax":"def,enum constant","pretty":"enum constant mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicStart","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicStart","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00054:22-40","source":1,"syntax":"enum,use","pretty":"enum IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","type":"enum IPCMessageStart","typesym":"T_IPCMessageStart"}
{"loc":"00055:4-17","source":1,"syntax":"def,enum constant","pretty":"enum constant mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00056:4-17","source":1,"syntax":"def,enum constant","pretty":"enum constant mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicEnd","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicEnd","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00059:9-18","source":1,"syntax":"type,use","pretty":"type mozilla::UniquePtr","sym":"TA_mozilla::UniquePtr"}
{"loc":"00059:24-31","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00060:0-9","source":1,"syntax":"decl,function","pretty":"function mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEx,_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEl","type":"mozilla::UniquePtr<IPC::Message> (IPC::Message::routeid_t)"}
{"loc":"00060:15-22","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00060:24-33","source":1,"syntax":"type,use","pretty":"type IPC::Message::routeid_t","sym":"TA_IPC::Message::routeid_t","type":"IPC::Message::routeid_t"}
{"loc":"00060:34-43","source":1,"syntax":"","pretty":"variable routingId","sym":"V_acd5e6fdec2f4e16_a5670b686a7d773,V_a681eebc0a75ca7a_a5670b686a7d773,V_7a4461f2ba706359_a5670b686a7d773,V_dd973c2124d0592c_a5670b686a7d773,V_df509cd99741efeb_a5670b686a7d773,V_c0c2c60bb642265a_a5670b686a7d773,V_ca73dc7661dbf63e_a5670b686a7d773","no_crossref":1,"type":"IPC::Message::routeid_t"}
{"loc":"00055:4-17","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","type_pretty":null,"kind":"enumConstant","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00056:4-17","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicEnd","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicEnd","type_pretty":null,"kind":"enumConstant","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00054:4-19","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicStart","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicStart","type_pretty":null,"kind":"enumConstant","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00053:5-16","structured":1,"pretty":"mozilla::_ipdltest::PTestBasic::MessageType","sym":"T_mozilla::_ipdltest::PTestBasic::MessageType","type_pretty":null,"kind":"enum","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00043:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_09c8bcbc0a75ca7a_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00043:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_0f1db4fdec2f4e16_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:72-79","structured":1,"pretty":"aParent","sym":"V_115cba7661dbf63e_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00044:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_15e5c4fdec2f4e16_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00046:71-77","structured":1,"pretty":"aChild","sym":"V_1715ca7661dbf63e_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:72-79","structured":1,"pretty":"aParent","sym":"V_179ba40bb642265a_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00046:71-77","structured":1,"pretty":"aChild","sym":"V_1d54b40bb642265a_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00044:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_1f81ccbc0a75ca7a_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00043:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_230a940bb642265a_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:72-79","structured":1,"pretty":"aParent","sym":"V_24702a2124d0592c_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:72-79","structured":1,"pretty":"aParent","sym":"V_26397ad99741efeb_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00046:71-77","structured":1,"pretty":"aChild","sym":"V_2a392a2124d0592c_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00046:71-77","structured":1,"pretty":"aChild","sym":"V_2cf18ad99741efeb_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00043:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_2dbaaa7661dbf63e_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00043:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_30ee0a2124d0592c_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00043:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_32a76ad99741efeb_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00044:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_3383ba7661dbf63e_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00044:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_39c2a40bb642265a_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00044:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_46a71a2124d0592c_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00044:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_48607ad99741efeb_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00060:34-43","structured":1,"pretty":"routingId","sym":"V_7a4461f2ba706359_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00051:71-77","structured":1,"pretty":"aChild","sym":"V_809b40f2ba706359_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00050:72-79","structured":1,"pretty":"aParent","sym":"V_8ac240f2ba706359_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00060:34-43","structured":1,"pretty":"routingId","sym":"V_a681eebc0a75ca7a_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00060:34-43","structured":1,"pretty":"routingId","sym":"V_acd5e6fdec2f4e16_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00051:71-77","structured":1,"pretty":"aChild","sym":"V_b22dc5fdec2f4e16_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00050:72-79","structured":1,"pretty":"aParent","sym":"V_b600cdbc0a75ca7a_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00050:72-79","structured":1,"pretty":"aParent","sym":"V_bc54c5fdec2f4e16_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00051:71-77","structured":1,"pretty":"aChild","sym":"V_bcc8cdbc0a75ca7a_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:72-79","structured":1,"pretty":"aParent","sym":"V_c02d4fe2ba706359_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00060:34-43","structured":1,"pretty":"routingId","sym":"V_c0c2c60bb642265a_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00046:71-77","structured":1,"pretty":"aChild","sym":"V_c6e55fe2ba706359_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00060:34-43","structured":1,"pretty":"routingId","sym":"V_ca73dc7661dbf63e_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00050:72-79","structured":1,"pretty":"aParent","sym":"V_d041a50bb642265a_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00051:71-77","structured":1,"pretty":"aChild","sym":"V_d0cabb7661dbf63e_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00051:71-77","structured":1,"pretty":"aChild","sym":"V_d60aa50bb642265a_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00050:72-79","structured":1,"pretty":"aParent","sym":"V_daf1bb7661dbf63e_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00043:39-54","structured":1,"pretty":"aParentDestInfo","sym":"V_dc8b3fe2ba706359_c05dff1385dd6cb8","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00060:34-43","structured":1,"pretty":"routingId","sym":"V_dd973c2124d0592c_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00060:34-43","structured":1,"pretty":"routingId","sym":"V_df509cd99741efeb_a5670b686a7d773","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00044:39-53","structured":1,"pretty":"aChildDestInfo","sym":"V_e2544fe2ba706359_6c9b56545850b521","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00051:71-77","structured":1,"pretty":"aChild","sym":"V_e3ee1b2124d0592c_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00051:71-77","structured":1,"pretty":"aChild","sym":"V_e5a77bd99741efeb_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00050:72-79","structured":1,"pretty":"aParent","sym":"V_ed161b2124d0592c_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00050:72-79","structured":1,"pretty":"aParent","sym":"V_efde6bd99741efeb_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00046:71-77","structured":1,"pretty":"aChild","sym":"V_f223dcbc0a75ca7a_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:72-79","structured":1,"pretty":"aParent","sym":"V_f2bec4fdec2f4e16_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00046:71-77","structured":1,"pretty":"aChild","sym":"V_f877d4fdec2f4e16_ae7aa1fe256","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
{"loc":"00045:72-79","structured":1,"pretty":"aParent","sym":"V_fc5accbc0a75ca7a_03dd840f0b0d","type_pretty":null,"kind":"parameter","subsystem":null,"implKind":"","sizeBytes":null,"alignmentBytes":null,"ownVFPtrBytes":null,"bindingSlots":[],"ontologySlots":[],"supers":[],"methods":[],"fields":[],"overrides":[],"props":[],"variants":[]}
