{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_fde80d1f1072afec"}
{"loc":"00009:9-31","target":1,"kind":"use","pretty":"mfbt/Attributes.h","sym":"FILE_mfbt/Attributes@2Eh"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh"}
{"loc":"00011:9-27","target":1,"kind":"use","pretty":"mfbt/RefPtr.h","sym":"FILE_mfbt/RefPtr@2Eh"}
{"loc":"00012:9-21","target":1,"kind":"use","pretty":"xpcom/string/nsString.h","sym":"FILE_xpcom/string/nsString@2Eh"}
{"loc":"00013:9-21","target":1,"kind":"use","pretty":"xpcom/ds/nsTArray.h","sym":"FILE_xpcom/ds/nsTArray@2Eh"}
{"loc":"00014:9-25","target":1,"kind":"use","pretty":"xpcom/ds/nsTHashtable.h","sym":"FILE_xpcom/ds/nsTHashtable@2Eh"}
{"loc":"00015:9-31","target":1,"kind":"use","pretty":"xpcom/threads/MozPromise.h","sym":"FILE_xpcom/threads/MozPromise@2Eh"}
{"loc":"00016:9-42","target":1,"kind":"use","pretty":"mfbt/OperatorNewExtensions.h","sym":"FILE_mfbt/OperatorNewExtensions@2Eh"}
{"loc":"00017:9-30","target":1,"kind":"use","pretty":"mfbt/UniquePtr.h","sym":"FILE_mfbt/UniquePtr@2Eh"}
{"loc":"00018:9-32","target":1,"kind":"use","pretty":"ipc/glue/ByteBuf.h","sym":"FILE_ipc/glue/ByteBuf@2Eh"}
{"loc":"00019:9-39","target":1,"kind":"use","pretty":"ipc/glue/FileDescriptor.h","sym":"FILE_ipc/glue/FileDescriptor@2Eh"}
{"loc":"00020:9-41","target":1,"kind":"use","pretty":"ipc/glue/ProtocolUtilsFwd.h","sym":"FILE_ipc/glue/ProtocolUtilsFwd@2Eh"}
{"loc":"00021:9-30","target":1,"kind":"use","pretty":"ipc/glue/Shmem.h","sym":"FILE_ipc/glue/Shmem@2Eh"}
{"loc":"00023:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00024:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00025:6-22","target":1,"kind":"forward","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00028:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00029:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00030:6-21","target":1,"kind":"forward","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00037:10-17","target":1,"kind":"def","pretty":"mozilla","sym":"NS_mozilla"}
{"loc":"00038:10-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest"}
{"loc":"00039:10-20","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic","sym":"NS_mozilla::_ipdltest::PTestBasic"}
{"loc":"00041:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00042:0-15","target":1,"kind":"decl","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","peekRange":"41-46"}
{"loc":"00043:14-23","target":1,"kind":"use","pretty":"base::ProcessId","sym":"T_base::ProcessId","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00044:14-23","target":1,"kind":"use","pretty":"base::ProcessId","sym":"T_base::ProcessId","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00045:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00045:51-67","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00046:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00046:51-66","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00048:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00049:0-15","target":1,"kind":"decl","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","peekRange":"48-51"}
{"loc":"00050:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00050:51-67","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00051:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00051:51-66","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00053:5-16","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::MessageType","sym":"T_mozilla::_ipdltest::PTestBasic::MessageType","peekRange":"53-53"}
{"loc":"00054:22-40","target":1,"kind":"use","pretty":"IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","context":"mozilla::_ipdltest::PTestBasic::MessageType","contextsym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00054:4-19","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicStart","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicStart","context":"mozilla::_ipdltest::PTestBasic::MessageType","contextsym":"T_mozilla::_ipdltest::PTestBasic::MessageType","peekRange":"54-54"}
{"loc":"00055:4-17","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","context":"mozilla::_ipdltest::PTestBasic::MessageType","contextsym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00056:4-17","target":1,"kind":"def","pretty":"mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicEnd","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicEnd","context":"mozilla::_ipdltest::PTestBasic::MessageType","contextsym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00059:24-31","target":1,"kind":"use","pretty":"IPC::Message","sym":"T_IPC::Message","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00059:9-18","target":1,"kind":"use","pretty":"mozilla::UniquePtr","sym":"T_mozilla::UniquePtr","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00060:0-9","target":1,"kind":"decl","pretty":"mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi","peekRange":"59-60"}
{"loc":"00060:10-17","target":1,"kind":"use","pretty":"int32_t","sym":"T_int32_t","context":"mozilla::_ipdltest::PTestBasic::Msg_Hello","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_43a1d9252c3248e9"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_fa0851c6a0ebef37"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh"}
{"loc":"00001:0","target":1,"kind":"def","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","target":1,"kind":"def","pretty":"PTestBasic_h","sym":"M_fe7733305eb29afd"}
{"loc":"00010:9-28","target":1,"kind":"use","pretty":"__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh"}
{"loc":"00041:0-8","target":1,"kind":"use","pretty":"nsresult","sym":"T_nsresult","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00042:0-15","target":1,"kind":"decl","pretty":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","peekRange":"41-46"}
{"loc":"00043:14-23","target":1,"kind":"use","pretty":"base::ProcessId","sym":"T_base::ProcessId","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00044:14-23","target":1,"kind":"use","pretty":"base::ProcessId","sym":"T_base::ProcessId","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00045:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00045:51-67","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00046:22-30","target":1,"kind":"use","pretty":"mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00046:51-66","target":1,"kind":"use","pretty":"mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","context":"mozilla::_ipdltest::PTestBasic::CreateEndpoints","contextsym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE"}
{"loc":"00001:0","source":1,"syntax":"def,file","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh,FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/mozilla/_ipdltest/PTestBasic@2Eh"}
{"loc":"00007:8-20","source":1,"syntax":"def,macro","pretty":"macro PTestBasic_h","sym":"M_fe7733305eb29afd,M_fa0851c6a0ebef37,M_43a1d9252c3248e9,M_fde80d1f1072afec"}
{"loc":"00009:9-31","source":1,"syntax":"file,use","pretty":"file mfbt/Attributes.h","sym":"FILE_mfbt/Attributes@2Eh"}
{"loc":"00010:9-28","source":1,"syntax":"file,use","pretty":"file __GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart.h","sym":"FILE_windows@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_macosx@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_linux@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh,FILE_android-armv7@__GENERATED__/ipc/ipdl/_ipdlheaders/IPCMessageStart@2Eh"}
{"loc":"00011:9-27","source":1,"syntax":"file,use","pretty":"file mfbt/RefPtr.h","sym":"FILE_mfbt/RefPtr@2Eh"}
{"loc":"00012:9-21","source":1,"syntax":"file,use","pretty":"file xpcom/string/nsString.h","sym":"FILE_xpcom/string/nsString@2Eh"}
{"loc":"00013:9-21","source":1,"syntax":"file,use","pretty":"file xpcom/ds/nsTArray.h","sym":"FILE_xpcom/ds/nsTArray@2Eh"}
{"loc":"00014:9-25","source":1,"syntax":"file,use","pretty":"file xpcom/ds/nsTHashtable.h","sym":"FILE_xpcom/ds/nsTHashtable@2Eh"}
{"loc":"00015:9-31","source":1,"syntax":"file,use","pretty":"file xpcom/threads/MozPromise.h","sym":"FILE_xpcom/threads/MozPromise@2Eh"}
{"loc":"00016:9-42","source":1,"syntax":"file,use","pretty":"file mfbt/OperatorNewExtensions.h","sym":"FILE_mfbt/OperatorNewExtensions@2Eh"}
{"loc":"00017:9-30","source":1,"syntax":"file,use","pretty":"file mfbt/UniquePtr.h","sym":"FILE_mfbt/UniquePtr@2Eh"}
{"loc":"00018:9-32","source":1,"syntax":"file,use","pretty":"file ipc/glue/ByteBuf.h","sym":"FILE_ipc/glue/ByteBuf@2Eh"}
{"loc":"00019:9-39","source":1,"syntax":"file,use","pretty":"file ipc/glue/FileDescriptor.h","sym":"FILE_ipc/glue/FileDescriptor@2Eh"}
{"loc":"00020:9-41","source":1,"syntax":"file,use","pretty":"file ipc/glue/ProtocolUtilsFwd.h","sym":"FILE_ipc/glue/ProtocolUtilsFwd@2Eh"}
{"loc":"00021:9-30","source":1,"syntax":"file,use","pretty":"file ipc/glue/Shmem.h","sym":"FILE_ipc/glue/Shmem@2Eh"}
{"loc":"00023:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"23:19-27:0"}
{"loc":"00024:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"24:21-26:0"}
{"loc":"00025:6-22","source":1,"syntax":"forward,type","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00028:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"28:19-32:0"}
{"loc":"00029:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"29:21-31:0"}
{"loc":"00030:6-21","source":1,"syntax":"forward,type","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00037:10-17","source":1,"syntax":"def,namespace","pretty":"namespace mozilla","sym":"NS_mozilla","nestingRange":"37:19-66:0"}
{"loc":"00038:10-19","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest","sym":"NS_mozilla::_ipdltest","nestingRange":"38:21-65:0"}
{"loc":"00039:10-20","source":1,"syntax":"def,namespace","pretty":"namespace mozilla::_ipdltest::PTestBasic","sym":"NS_mozilla::_ipdltest::PTestBasic","nestingRange":"39:22-64:0"}
{"loc":"00041:0-8","source":1,"syntax":"type,use","pretty":"type nsresult","sym":"T_nsresult","type":"enum nsresult","typesym":"T_nsresult"}
{"loc":"00042:0-15","source":1,"syntax":"decl,function","pretty":"function mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEmmPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE,_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEiiPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","type":"enum nsresult (base::ProcessId, base::ProcessId, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00043:14-23","source":1,"syntax":"type,use","pretty":"type base::ProcessId","sym":"T_base::ProcessId","type":"base::ProcessId"}
{"loc":"00043:24-38","source":1,"syntax":"","pretty":"variable aParentDestPid","sym":"V_db5a8e96588aec4d_d1259d65da7e98a3,V_d76cb0fe75f76d3f_d1259d65da7e98a3,V_2a09686ac0c980f6_d1259d65da7e98a3,V_daa982c20470f3ea_d1259d65da7e98a3","no_crossref":1,"type":"base::ProcessId"}
{"loc":"00044:14-23","source":1,"syntax":"type,use","pretty":"type base::ProcessId","sym":"T_base::ProcessId","type":"base::ProcessId"}
{"loc":"00044:24-37","source":1,"syntax":"","pretty":"variable aChildDestPid","sym":"V_e1239e96588aec4d_797885af5cc6dac7,V_ed25c0fe75f76d3f_797885af5cc6dac7,V_30d1786ac0c980f6_797885af5cc6dac7,V_e07292c20470f3ea_797885af5cc6dac7","no_crossref":1,"type":"base::ProcessId"}
{"loc":"00045:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00045:51-67","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00045:70-77","source":1,"syntax":"","pretty":"variable aParent","sym":"V_02fb9e96588aec4d_03dd840f0b0d,V_0efdc0fe75f76d3f_03dd840f0b0d,V_50aa786ac0c980f6_03dd840f0b0d,V_014b92c20470f3ea_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *"}
{"loc":"00046:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00046:51-66","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00046:69-75","source":1,"syntax":"","pretty":"variable aChild","sym":"V_96b4ae96588aec4d_ae7aa1fe256,V_92c6d0fe75f76d3f_ae7aa1fe256,V_e463886ac0c980f6_ae7aa1fe256,V_9504a2c20470f3ea_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *"}
{"loc":"00048:0-8","source":1,"syntax":"type,use","pretty":"type nsresult","sym":"T_nsresult","type":"enum nsresult","typesym":"T_nsresult"}
{"loc":"00049:0-15","source":1,"syntax":"decl,function","pretty":"function mozilla::_ipdltest::PTestBasic::CreateEndpoints","sym":"_ZN7mozilla9_ipdltest10PTestBasic15CreateEndpointsEPNS_3ipc8EndpointINS0_16PTestBasicParentEEEPNS3_INS0_15PTestBasicChildEEE","type":"enum nsresult (mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *, mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *)"}
{"loc":"00050:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00050:51-67","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicParent","sym":"T_mozilla::_ipdltest::PTestBasicParent","type":"class mozilla::_ipdltest::PTestBasicParent","typesym":"T_mozilla::_ipdltest::PTestBasicParent"}
{"loc":"00050:70-77","source":1,"syntax":"","pretty":"variable aParent","sym":"V_cb919f96588aec4d_03dd840f0b0d,V_c7a3c1fe75f76d3f_03dd840f0b0d,V_1a40796ac0c980f6_03dd840f0b0d,V_cae093c20470f3ea_03dd840f0b0d","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicParent> *"}
{"loc":"00051:22-30","source":1,"syntax":"type,use","pretty":"type mozilla::ipc::Endpoint","sym":"T_mozilla::ipc::Endpoint"}
{"loc":"00051:51-66","source":1,"syntax":"type,use","pretty":"type mozilla::_ipdltest::PTestBasicChild","sym":"T_mozilla::_ipdltest::PTestBasicChild","type":"class mozilla::_ipdltest::PTestBasicChild","typesym":"T_mozilla::_ipdltest::PTestBasicChild"}
{"loc":"00051:69-75","source":1,"syntax":"","pretty":"variable aChild","sym":"V_506a9f96588aec4d_ae7aa1fe256,V_5c6cc1fe75f76d3f_ae7aa1fe256,V_ae09796ac0c980f6_ae7aa1fe256,V_5fa993c20470f3ea_ae7aa1fe256","no_crossref":1,"type":"mozilla::ipc::Endpoint<mozilla::_ipdltest::PTestBasicChild> *"}
{"loc":"00053:5-16","source":1,"syntax":"def,type","pretty":"type mozilla::_ipdltest::PTestBasic::MessageType","sym":"T_mozilla::_ipdltest::PTestBasic::MessageType","nestingRange":"53:17-57:0"}
{"loc":"00054:4-19","source":1,"syntax":"def,enum constant","pretty":"enum constant mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicStart","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicStart","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00054:22-40","source":1,"syntax":"enum,use","pretty":"enum IPCMessageStart::PTestBasicMsgStart","sym":"E_<T_IPCMessageStart>_PTestBasicMsgStart","type":"enum IPCMessageStart","typesym":"T_IPCMessageStart"}
{"loc":"00055:4-17","source":1,"syntax":"def,enum constant","pretty":"enum constant mozilla::_ipdltest::PTestBasic::MessageType::Msg_Hello__ID","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_Msg_Hello__ID","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00056:4-17","source":1,"syntax":"def,enum constant","pretty":"enum constant mozilla::_ipdltest::PTestBasic::MessageType::PTestBasicEnd","sym":"E_<T_mozilla::_ipdltest::PTestBasic::MessageType>_PTestBasicEnd","type":"enum mozilla::_ipdltest::PTestBasic::MessageType","typesym":"T_mozilla::_ipdltest::PTestBasic::MessageType"}
{"loc":"00059:9-18","source":1,"syntax":"type,use","pretty":"type mozilla::UniquePtr","sym":"T_mozilla::UniquePtr"}
{"loc":"00059:24-31","source":1,"syntax":"type,use","pretty":"type IPC::Message","sym":"T_IPC::Message","type":"class IPC::Message","typesym":"T_IPC::Message"}
{"loc":"00060:0-9","source":1,"syntax":"decl,function","pretty":"function mozilla::_ipdltest::PTestBasic::Msg_Hello","sym":"_ZN7mozilla9_ipdltest10PTestBasic9Msg_HelloEi","type":"mozilla::UniquePtr<IPC::Message> (int32_t)"}
{"loc":"00060:10-17","source":1,"syntax":"type,use","pretty":"type int32_t","sym":"T_int32_t","type":"int32_t"}
{"loc":"00060:18-27","source":1,"syntax":"","pretty":"variable routingId","sym":"V_f713b0a6588aec4d_a5670b686a7d773,V_f325e2fe75f76d3f_a5670b686a7d773,V_46c19a6ac0c980f6_a5670b686a7d773,V_f662b4c20470f3ea_a5670b686a7d773","no_crossref":1,"type":"int32_t"}
