/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;

public class JavaLibrary {
    public boolean someLibraryMethod() {
        return true;
    }

    interface B extends A {}
    interface A {}
}
